### ISSUE TITLE
Not able to run in eclipse

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#100]
Hello kaaes, We are developing an application which is using spotify. As a SDK we are using other library also which is not supported to android studio. We is their any version or help you can provide to make it possible.

thanks

**Comment by nikreiman** [comment]
Hi @deepakvvdn, we don't support Eclipse and recommend migrating to Android Studio, since this is Google's preferred environment for developing Android applications. However, if you cannot migrate to AS, there are some unofficial instructions for using AARs in Eclipse in issue #74.

**Comment by kaaes** [comment]
I'm closing this issue as it has been answered in #74
