### ISSUE TITLE
Managing buffering issues

### ISSUE THREAD

**Issue by jlitjens** [spotify/android-sdk#102]
Hi there,

Firstly, thanks for the commitment to creating this brilliant SDK.

Are there any suggestions on how to manage buffering issues, particularly on (but not limited to) bad internet connections? The SDK is sometimes running into frequent buffer underrun states, causing the audio to cut out and stutter (whilst the official Spotify app seems to be able to continue without issue). 

At the moment I am trying to manually catch these occurrences by watching playerState.positionInMs to see if the song stops playing and then pausing for 5 seconds to hopefully allow the buffer to refill. However this is unreliable and is sometimes gives undesired results.

In a previous project, using libSpotify (in Python) I avoided the issue altogether by prefetching the upcoming track, but this doesn't seem possible in the Android SDK?

Cheers,
James

**Comment by kaaes** [comment]
The "real" way to solve this issue would be to implement prefetching. This is something we'd like to add to the SDK but it is not planned to be a part of closest releases.
I'll bring this issue up with the team and we'll discuss if there's anything else we can do to improve the experience. Thank you for the report!

**Comment by jlitjens** [comment]
Hi Kasia,

Thanks for including this in the Beta10 SDK. I recently updated it in my [social jukebox app Jukestar](http://jukestar.mobi/), and it is much more reliable now!

Cheers,
James

**Comment by kaaes** [comment]
@jlitjens great to hear it's working better now! Do you think we could close this issue?

**Comment by kaaes** [comment]
I am going to close this issue. If you'll see it happening again we can reopen
