### ISSUE TITLE
Volume fadeIn and fadeOut.

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#103]
Hi I want to fade out the volume of player while other like navigation voice is coming or other notification comes, and fade in again while navigation voice ends. how can i manage this please write the correct solution..

Is it possible to do with current beta version of spotify spotify-auth-1.0.0-beta9.aar,spotify-player-1.0.0-beta9.aar?

**Comment by nikreiman** [comment]
You can do it by intercepting the PCM samples (you basically must provide your own `AudioController` interface which you set to the `Player`). From here, you can do whatever you want to the samples, including decreasing the volume when a system notification is received. That's probably the only way to achieve a gentle fade in/out effect.

If you just want to drop the volume when a certain event occurs, you can probably just set the stream volume directly (the SDK of course uses the `AudioManager.STREAM_MUSIC` stream by default). See http://stackoverflow.com/a/4179507/14302 for more details.

**Comment by deepakvvdn** [comment]
MediaPlayer localMediaPlayer;
i just want something like
 localMediaPlayer.setVolume(lVolume, rVolume) is their any way for player?

**Comment by nikreiman** [comment]
Yes, see the StackOverflow answer link that I posted:

```java
AudioManager audioManager = 
    (AudioManager)getSystemService(Context.AUDIO_SERVICE);

audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, volume, 0);
```

**Comment by deepakvvdn** [comment]
But this will low the volume of my phone i think so? whole phone volume will be down if i will down by audio manager rgt?

**Comment by xplodwild** [comment]
@nikreiman I wouldn't do it that way, as some apps (I think even Google Maps) use STREAM_MUSIC for voice instructions. Reducing STREAM_MUSIC would cause those sounds to be reduced as well, nulling out the ducking expected. I think this can be easily reproduced using Google Now.

I'd suggest a "setVolume" method on the default SDK player

**Comment by deepakvvdn** [comment]
yaa @xplodwild , i am totally agree with you. I expect the same. setVolume method sholud be part of default spotify sdk player.

**Comment by nikreiman** [comment]
If you don't want to modify the the system `STREAM_MUSIC` stream, then you are of course free to intercept the PCM samples and set the gain there. :) I think that the conflict between voice instructions in Maps can be avoided by requesting a focus change (see http://stackoverflow.com/questions/18279998/how-to-make-my-tts-not-overlap-with-google-map-voice-for-driving-direction).

That said, we will consider adding a `setVolume` method.

**Comment by xplodwild** [comment]
@nikreiman Indeed that's a solution, however it'll be easier with a `setVolume` method (especially considering that if you're using `AudioTrack` behind it, that's a one line call) :)
I guess there was a misunderstanding, as I wasn't talking about conflict between two streams. Voice instructions, just like music itself, goes through `STREAM_MUSIC`, so if you reduce the `STREAM_MUSIC` volume when the Maps app requests the focus for TTS, you will reduce both the currently playing music as well as the TTS, which is not the desired effect

**Comment by deepakvvdn** [comment]
yes @nikreiman i have used with focus change listner with the voice but could not get the desired effect. 

for example if the navigation like audio advice is coming and music is running. If i try to reduce the volume of audio manager then audio advice volume is also affected which is not required. Only required is to low the running music and keep the audio advice same for navigational data.

**Comment by ckoessler** [comment]
I am facing a similar issue. 
In my app I have a text to speech feature and I would like the spotify player to duck when the tts starts to speak. I'm also looking for a way to have the spotify player to stop playing during a phone call.

**Comment by d-kunin** [comment]
fadeIn/out is not something we might implement in the SDK. Please report ducking as a separate issue if necessary.
