### ISSUE TITLE
Callback in case of slow internet.

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#106]
If In the case I have slow internet speed network. Music is breaking in between. Is their any callback that alert me to show the progress to user.

When running music breaks in between i got some logs like 

releaseBuffer() track 0x5ffd3a48 name=0x1 disabled, restarting???

**Comment by jhmacdon** [comment]
I am getting the same issue, but I am on quick internet. Ideas?

**Comment by d-kunin** [comment]
Please check for beta 21 and reopen if makes sense.
