### ISSUE TITLE
Verify user without activity.

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#107]
Hi team,

I have another question for you if I want to login or validate the user without activity, Is it possible?

I want to do login via just android java class. please refer the solution.

**Comment by kaaes** [comment]
SDK only supports authentication through the LoginActivity. If you'd like to implement custom behaviour you can check the  [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/) for details of the auth process
