### ISSUE TITLE
Log out / in

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/android-sdk#108]
I am not sure if this is just the way that I have implemented the SDK; but when I log out, I cannot get the log in page to show again. All that appears is the loading icon and then nothing. I am guessing this is because I checked the remember me option on the log in page the first time.

While this is nice not having to show the log in when re-authenticating; it would be good to be able to force the log in screen to show so that users can change their details.

Thanks

**Comment by kaaes** [comment]
Logging out from the Player won't automatically log user out of Spotify (for the reason you mentioned).
You can force the login page to show in two ways:
* By logging user out with [`AuthenticationClient#logout`](https://developer.spotify.com/android-sdk-docs/authentication/com/spotify/sdk/android/authentication/AuthenticationClient.html#logout-android.content.Context-) method. This will remove all active sessions and user will have to login next time they want to use the SDK
* By [setting `setShowDialog` to `true`](https://developer.spotify.com/android-sdk-docs/authentication/com/spotify/sdk/android/authentication/AuthenticationRequest.Builder.html#setShowDialog-boolean-) when building the `AuthenticationRequest`. This won't automatically log user out but  will give them an option to do that by clicking the link on the site.

**Comment by Brad-Jackson** [comment]
Thanks for the information.

**Comment by Lokesh-speakmusic** [comment]
Hi Team,

I found that this method was only in auth-lib, not found in Spotify  beta23 sdk, is their any change in beta 23 Sdk for this particular method if change , the please help me with this. what we are using currently after this.

Thanks

**Comment by ryandt** [comment]
@kaaes It looks like `AuthenticationClient#logout` doesn't currently exist anymore. Is there an alternative method that can be called in the latest SDK to logout the user and force the login screen to show at login time? Setting `AuthenticationRequest.setShowDialog(true)` didn't do the trick for me.
