### ISSUE TITLE
Are you know this issue?

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#110]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.spotify.sdk:spotify-auth:1.0.0-beta9.
     Required by:
         SpotifyTesting:app:unspecified > SpotifyTesting:spotifysdk:unspecified
   > Could not find com.spotify.sdk:spotify-player:1.0.0-beta9.
     Required by:
         SpotifyTesting:app:unspecified > SpotifyTesting:spotifysdk:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 39.907 secs

**Comment by Wolftein** [comment]
Could you write down your build.gradle? it seems you forgot to add the lib folder as a maven repository in gradle.

**Comment by deepakvvdn** [comment]
apply plugin: 'com.android.application'
buildscript {
    repositories {
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
    }
}
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}


dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile fileTree(dir: "$buildDir", include: 'native-libs.jar')
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile project(':sdktools')

    // This library handles authentication and authorization
    compile 'com.spotify.sdk:spotify-auth-1.0.0-beta9@aar'
    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player-1.0.0-beta9@aar'

    // All other dependencies for your app should also be here:
    compile files('libs/spotify-web-api-android-master-all-0.1.0.jar')


}

android {
    compileSdkVersion 21
    buildToolsVersion "20.0.0"
    compileOptions {
        sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_6
        targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_6
    }
    lintOptions {
        abortOnError false
        ignoreWarnings true
        quiet true
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }

}

**Comment by deepakvvdn** [comment]
apply plugin: 'com.android.application'
buildscript {
    repositories {
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
    }
}
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}


dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile fileTree(dir: "$buildDir", include: 'native-libs.jar')
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile project(':sdktools')

    // This library handles authentication and authorization
    compile 'com.spotify.sdk:spotify-auth-1.0.0-beta9@aar'
    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player-1.0.0-beta9@aar'

    // All other dependencies for your app should also be here:
    compile files('libs/spotify-web-api-android-master-all-0.1.0.jar')


}

android {
    compileSdkVersion 21
    buildToolsVersion "20.0.0"
    compileOptions {
        sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_6
        targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_6
    }
    lintOptions {
        abortOnError false
        ignoreWarnings true
        quiet true
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }

}

**Comment by deepakvvdn** [comment]
names of my .jar files as  : spotify-auth-1.0.0-beta9.aar
spotify-player-1.0.0-beta9.aar
spotify-web-api-android-master-all-0.1.0.jar

I tried  by both included the .aar files in build.gradle like :: 

compile 'com.spotify.sdk:spotify-auth-1.0.0-beta9@aar'
// This library handles music playback
compile 'com.spotify.sdk:spotify-player-1.0.0-beta9@aar'


and 
As mention in tutorial and given the manifest entry also in the manifest file for login activity.

compile 'com.spotify.sdk:spotify-auth:1.0.0-beta9@aar'
// This library handles music playback
compile 'com.spotify.sdk:spotify-player:1.0.0-beta9@aar'

thanks.

**Comment by deepakvvdn** [comment]
any valuable help pls?

**Comment by Wolftein** [comment]
Are you linking those AAR though another library?, let say Library A compiles spotify's aar and then Application B compiles A, in that case its a common gradle issue, that requires to add the compile line and the lib folder in B (AAR its not transitive).

**Comment by deepakvvdn** [comment]
No I'm directly using in a project. I'm not using this   by compiling from other library.

**Comment by deepakvvdn** [comment]
Few days back the same code was working fine for me but rgt now suddenly I'm facing this strange issue

**Comment by kaaes** [comment]
Are you sure that nothing changed in your code? It seems very unlikely that this would just stop working if it worked before. You could try cleaning your project or invalidate caches in Android Studio (File > Invalidate caches /restart)

**Comment by deepakvvdn** [comment]
OK kasia I can try more time to get this work.

**Comment by deepakvvdn** [comment]
thanks a lot for your valuable support quickly!!! :-)
