### ISSUE TITLE
login activity is not opening!!! (16-04-2015)

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#111]
Hi I am trying to login, in my working code!! its showing error login activity not found, have you declared  in manifest!!!

and application is getting crashed!!! please give the solution what is the issue!!!!

I have also chaked in iOS same issue is their login page is not opening in applications!!!

**Comment by xplodwild** [comment]
...Did you declare the activity in the manifest?
...Did you read the beginner guide at https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/, especially the part "Updating the Application Manifest"?

**Comment by deepakvvdn** [comment]
till yesterday it was working fine !! i have playing many times but from today morning its getting trouble and application makes crahed!!

**Comment by xplodwild** [comment]
That still doesn't answer the "Did you declare the activity in the manifest" question. If it worked yesterday, then it was pure luck or you removed something you shouldn't have since (like the activity declaration in the manifest).

**Comment by deepakvvdn** [comment]
Yes manifest entry is their for login activity also. It may the problem from my side but I'm surprised with this thing I have make a scratch demo application that is also not working.. We can suppose my issue from android side but iOS side login activity is also not opening.why???

**Comment by xplodwild** [comment]
iOS probably works differently so I'm not even going to bother checking. It would probably help to see your source code, but it's out of the scope of this issue tracker as it's not a library issue. Take it to StackOverflow.

**Comment by deepakvvdn** [comment]
OK thanks a lot for valuable time.
