### ISSUE TITLE
When InitializationObserver do not produce callback (.onIntialized, nor .onError)

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#112]
The .onInitialized is normally received and things work fine. However, in a seemingly random fashion, sometimes neither of the callbacks are received, causing the app to "hang". The Spotify.getPlayer(...) operation is done directly after reception of a proper token. Is there a typical blunder to make that would cause this erratic behavior?

**Comment by kaaes** [comment]
@chjan some questions to narrow it down:
* which version of the SDK are you using?
* Is there anything relevant in the logcat when it happens?
* Does this happen when the player is created for the first time, when the second instance of the player is created or when it's recreated after destroying?

**Comment by chjan** [comment]
- Version: Beta8-2
- Nothing in logcat stemming from activities outside our own app. What happens, when it happens, is that the Spotify.getPlayer never returns. The only option is to kill the app. It appears kind of random.
- Yes, on first creation directly subsequent to authorization and reception of token in .onActivityForResult.
- The app do not create a second instance of the (Singleton?) player. Are you pointing to earlier versions of SDK?

**Comment by kaaes** [comment]
Does that mean that the app freezes when it happens?
I have some ideas why this might be happening but would only occur if there's more than one reference to the player. That's why I suspect it is happening not on the first creation on the player but rather on re-creation when player is still destroying or when getting another reference when it's still initialising.
Is it possible that this is your case? Calling `getPlayer` more than once or calling it immediately after `destroy`?

**Comment by chjan** [comment]
OK, while I write, I understand your question in a better way. You are perhaps wondering if I do the correct .destroy when the app is exiting ? Yes, I do that according to descriptions in tutorial, but on the other hand, I am in a testing phase meaning that if the app is exiting subject to an exception, there might be a service leak related to the player? This is then causing the situation you describe as I immediately thereafter restart the app? 

If so, this is interesting. How to prevent this scenario in a commercial situation?

Anyway,  .getPlayer is only called once during app startup.

Yes, the app used to freeze, but not anymore as I moved the whole .getPlayer code to a working thread. It means that the app will try again and again to .getPlayer, but it can be observed that once the first request was unsuccessful, then the subsequent request will also be unsuccessful, even minutes later. The hang is eternal.

From this I at least deducted that the cause of error was not related to .getPlayer being called on the UI thread, perhaps a non-optimal solution.

I have looked for JNI messages or similar in logcat, but there is utter silencium.

**Comment by chjan** [comment]
OK, while I write, I understand your question in a better way. You are perhaps wondering if I do the correct .destroy when the app is exiting ? Yes, I do that according to descriptions in tutorial, but on the other hand, I am in a testing phase meaning that if the app is exiting subject to an exception, there might be a service leak related to the player? This is then causing the situation you describe as I immediately thereafter restart the app? 

If so, this is interesting. How to prevent this scenario in a commercial situation?

Anyway,  .getPlayer is only called once during app startup.

Yes, the app used to freeze, but not anymore as I moved the whole .getPlayer code to a working thread. It means that the app will try again and again to .getPlayer, but it can be observed that once the first request was unsuccessful, then the subsequent request will also be unsuccessful, even minutes later. The hang is eternal.

From this I at least deducted that the cause of error was not related to .getPlayer being called on the UI thread, perhaps a non-optimal solution.

I have looked for JNI messages or similar in logcat, but there is utter silencium.

**Comment by kaaes** [comment]
Can you try it with the latest release? (1.0.0-beta10)

**Comment by chjan** [comment]
I read the changeLog and are confident the issue are fixed. Just now busy, but I shall report as I upgrade in the near future.

**Comment by kaaes** [comment]
I am going to close this issue as it should not happen anymore. Please let us know in case we need to reopen it.
