### ISSUE TITLE
Spotty network conditions cause playback to fail, even after improving.

### ISSUE THREAD

**Issue by eldad-cc** [spotify/android-sdk#113]
For testing purposes I've set up a wi-fi network with 15% packet loss using the Network Link Conditioner utility.

After a while, playback stops / fails, which is to be expected.

What I didn't expect is that when trying to play the track again by calling creating a new Player and calling the play method, I'd get a MediaError.PLAYBACK_ERROR immediately, even after switching back to the "real" (no packet loss) wi-fi network, but it looks like that's what's happening.

**Comment by kaaes** [comment]
@eldad-cc is that something you can easily reproduce or does it happen intermittently?

You can try using [`Player#setConnectivityStatus`] (https://developer.spotify.com/android-sdk-docs/player/com/spotify/sdk/android/player/Player.html#setConnectivityStatus-com.spotify.sdk.android.player.Connectivity-) to pass information about current connectivity to the player after it's created. There's an example how to do it in the `DemoActivity` inside the zip with the libraries.

**Comment by eldad-cc** [comment]
It happened consistently. Reproducing it involves setting up a network with a high packet loss and waiting a few minutes.

I'm not sure setConnectivityStatus would make a difference - when should I tell the player "the network is no longer reliable" or "the network is reliable again"? I'm trying to simulate real-world variable location-dependent connectivity. And the player is the one responsible for the bulk of the network activity.

As for the DemoActivity, I have located the .java files, but not the resources it uses (layout, strings).

**Comment by kaaes** [comment]
I tested it and reproduced the behaviour you described. This bug originates in the native library the SDK is using so I passed it to the team responsible for it.
Thanks for the report!

**Comment by d-kunin** [comment]
Please verify for beta21 and reopen if it makes sense.
