### ISSUE TITLE
Duplicate files during packaging of APK.

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#114]
I'm trying to use Facebook's Fresco with SpotifySDK but i cannot compile due to:

```
Error:duplicate files during packaging of APK 
	Path in archive: lib/armeabi/libgnustl_shared.so
	Origin 1: \build\intermediates\exploded-aar\com.spotify.sdk\spotify-player\1.0.0-beta9\jni\armeabi\libgnustl_shared.so
	Origin 2: \build\intermediates\exploded-aar\com.facebook.fresco\imagepipeline\0.1.0\jni\armeabi\libgnustl_shared.so
```

It's there any way to fix this?

Thanks!

**Comment by nikreiman** [comment]
http://stackoverflow.com/a/20675331/14302

This refers to a super old version of the android gradle plugin, but it will probably still work.

**Comment by nikreiman** [comment]
Bah, it seems that this trick doesn't work for AAR files....

**Comment by kaaes** [comment]
I tried a brute force solution and repackaged the `aar` to remove the `libgnustl` files.
I'm not convinced if this is the way to go, but it worked :)
Seems like this feature is still missing from gradle android plugin: https://code.google.com/p/android/issues/detail?id=158630

**Comment by Wolftein** [comment]
Would you provide a separated aar without libgnustl?, if i remove the duplicated file from the current AAR would it work? (Loading fresco first before spotify's sdk).

**Comment by kaaes** [comment]
What I did was unzipping the player `aar`, removing libraries and zipping it up again. After that my test app worked.

**Comment by Wolftein** [comment]
The fix is coming in the new Gradle version 1.3 https://android-review.googlesource.com/#/c/148755/

I'll close, thanks for all the help.

**Comment by kaaes** [comment]
Great to hear! Looking forward to the new version

**Comment by leon-misfit** [comment]
Does gradle 1.3.0 actually resolved this problem? I still have it!!!
