### ISSUE TITLE
What to do on AUDIOFOCUS_LOSS?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/android-sdk#115]
My App plays music and an other app requests AudioFocus. At the moment i am only pausing the current song with mPlayer.pause(). Amazons Review Process reports some issues and it seems that the app is still buffering in the background. 

so what should i do if i am loosing the AUDIOFOCUS? should i shutdown the Player?
If so, do i have to recreate a new Player if my activity starts again? 

any tips would be great

thx
Alex

**Comment by digitaldesaster** [comment]
So destroying the Player and recreating it seems to work fine

try {
       Spotify.awaitDestroyPlayer(this, 5000L, TimeUnit.MILLISECONDS);
    } catch (InterruptedException ignored) {}

**Comment by kaaes** [comment]
Does destroying the player work for you or do you need more help regarding this issue?

**Comment by digitaldesaster** [comment]
Yes it works, everything seems to be fine. Amazon has approved my latest build. Thanks
