### ISSUE TITLE
My app has received Playback event "BECAME_ACTIVE",but can not play track

### ISSUE THREAD

**Issue by start-light** [spotify/android-sdk#116]
My app has received Playback event "BECAME_ACTIVE",but can not play track.
" 
  365-377/? I/ActivityManager﹕ START u0 {cmp=com.example.lyx.mycdplayer/com.spotify.sdk.android.authentication.LoginActivity (has extras)} from pid 3430
04-30 08:46:30.381      733-735/? D/dalvikvm﹕ GC_CONCURRENT freed 141K, 22% free 9477K/12148K, paused 3ms+12ms, total 71ms
04-30 08:46:30.411    3430-3430/? D/libEGL﹕ loaded /system/lib/egl/libEGL_mali.so
04-30 08:46:30.411    3430-3430/? D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_mali.so
04-30 08:46:30.421    3430-3430/? D/libEGL﹕ loaded /system/lib/egl/libGLESv2_mali.so
04-30 08:46:30.441      733-918/? D/dalvikvm﹕ GC_FOR_ALLOC freed 2606K, 35% free 7969K/12148K, paused 29ms, total 29ms
04-30 08:46:30.451    3430-3430/? D/OpenGLRenderer﹕ Enabling debug mode 0
04-30 08:46:30.511      733-735/? D/dalvikvm﹕ GC_CONCURRENT freed 434K, 28% free 8814K/12148K, paused 3ms+4ms, total 43ms
04-30 08:46:30.511     733-1367/? D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 31ms
04-30 08:46:30.511     733-1367/? I/dalvikvm-heap﹕ Grow heap (frag case) to 10.175MB for 1614608-byte allocation
04-30 08:46:30.551      733-746/? D/dalvikvm﹕ GC_FOR_ALLOC freed 988K, 32% free 9403K/13728K, paused 34ms, total 34ms
04-30 08:46:30.591      733-735/? D/dalvikvm﹕ GC_CONCURRENT freed 1K, 31% free 9481K/13728K, paused 4ms+4ms, total 37ms
04-30 08:46:30.621    3430-3447/? V/WebRequest﹕ WebRequest::WebRequest, setPriority = 1
04-30 08:46:30.641      365-381/? I/ActivityManager﹕ Displayed com.example.lyx.mycdplayer/.MainActivity: +469ms
04-30 08:46:30.731    3430-3432/? D/dalvikvm﹕ GC_CONCURRENT freed 120K, 4% free 4459K/4612K, paused 3ms+3ms, total 21ms
04-30 08:46:30.821      365-381/? I/ActivityManager﹕ Displayed com.example.lyx.mycdplayer/com.spotify.sdk.android.authentication.LoginActivity: +448ms
04-30 08:46:32.881      365-534/? D/dalvikvm﹕ GC_FOR_ALLOC freed 450K, 19% free 9672K/11908K, paused 57ms, total 57ms
04-30 08:46:32.911    3430-3430/? D/dalvikvm﹕ DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
04-30 08:46:32.911    3430-3430/? W/dalvikvm﹕ VFY: unable to resolve static field 70 (SUPPORTED_ABIS) in Landroid/os/Build;
04-30 08:46:32.911    3430-3430/? D/dalvikvm﹕ VFY: replacing opcode 0x62 at 0x000d
04-30 08:46:32.911    3430-3430/? D/dalvikvm﹕ DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
04-30 08:46:32.911    3430-3430/? I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x0046 at 0x17 in Lcom/spotify/sdk/android/player/Config;.createOsVersionString
04-30 08:46:32.921    3430-3430/? I/dalvikvm﹕ Could not find method android.media.AudioTrack.setVolume, referenced from method com.spotify.sdk.android.player.AudioTrackController.createAudioTrack
04-30 08:46:32.921    3430-3430/? W/dalvikvm﹕ VFY: unable to resolve virtual method 615: Landroid/media/AudioTrack;.setVolume (F)I
04-30 08:46:32.921    3430-3430/? D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x004c
04-30 08:46:32.921    3430-3430/? D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example.lyx.mycdplayer-2/libgnustl_shared.so 0x411001c0
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ Added shared lib /data/app-lib/com.example.lyx.mycdplayer-2/libgnustl_shared.so 0x411001c0
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.example.lyx.mycdplayer-2/libgnustl_shared.so 0x411001c0, skipping init
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example.lyx.mycdplayer-2/libspotify_embedded_shared.so 0x411001c0
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ Added shared lib /data/app-lib/com.example.lyx.mycdplayer-2/libspotify_embedded_shared.so 0x411001c0
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.example.lyx.mycdplayer-2/libspotify_embedded_shared.so 0x411001c0, skipping init
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example.lyx.mycdplayer-2/libspotify_sdk.so 0x411001c0
04-30 08:46:32.931    3430-3430/? D/dalvikvm﹕ Added shared lib /data/app-lib/com.example.lyx.mycdplayer-2/libspotify_sdk.so 0x411001c0
04-30 08:46:32.951    3430-3432/? D/dalvikvm﹕ GC_CONCURRENT freed 175K, 5% free 4706K/4912K, paused 2ms+4ms, total 25ms
04-30 08:46:33.001    3430-3460/? D/SpotifySDK﹕ Use diskcache: true
04-30 08:46:33.001    3430-3460/? I/SpotifySDK﹕ Got notification: Became active playing device
04-30 08:46:33.011    3430-3460/? I/SpotifySDK﹕ playbackCallbackOnSeek (to 0ms)
04-30 08:46:33.011    3430-3430/? D/MainActivity﹕ Playback event received: BECAME_ACTIVE
04-30 08:46:39.191    3430-3430/? D/MainActivity﹕ Login failed"

**Comment by kaaes** [comment]
@start-light, according to this stack trace logging to the player failed. Please check what error you got in the `onLoginFailed` callback.

**Comment by start-light** [comment]
Thanks. I have to get a premium account.
