### ISSUE TITLE
A tracklist with size 1 can not be played in 1.0.0-beta10 using PlayConfig.withTrackIndex(0)

### ISSUE THREAD

**Issue by rjayne** [spotify/android-sdk#119]
Code example:

List<String> trackIds = new ArrayList<String>();
trackIds.add("spotify:track:6MLycvbQNnctHqaL5qEVZs");

PlayConfig playConfig = PlayConfig.createFor(trackIds);
playConfig.withTrackIndex(index);
getPlayer().play(playConfig);

Looking at the code for PlayConfig.withTrackIndex(int index) method, it appears that if mUris.size() == 1 AND mUris.get(0) is a valid trackUri, the IllegalArgumentException is thrown with the message "Index is out of bounds for the context".

Please advise if I am meant to play a single track in a different way.

**Comment by kaaes** [comment]
@rjayne hm, yes.. specifying index 0 for 1 element track list should work. We'll fix it in the next release.
In the meantime you could just not specify an index when the list has 1 element (it plays from 0 by default):
```java
List trackIds = new ArrayList();
trackIds.add("spotify:track:6MLycvbQNnctHqaL5qEVZs");
PlayConfig playConfig = PlayConfig.createFor(trackIds);
getPlayer().play(playConfig);
```
or even play track uri directly:
```java
getPlayer().play("spotify:track:6MLycvbQNnctHqaL5qEVZs");
```

Thanks for reporting!

**Comment by kaaes** [comment]
This issue has been fixed in beta11
