### ISSUE TITLE
Cannot seem to get the user info using the /info/me web api after having requested the correct scopes from the Android Client

### ISSUE THREAD

**Issue by shroffrushabh** [spotify/android-sdk#120]
My android application has requested for the following scopes

```
builder.setScopes(new String[]{"user-read-private", "user-read-birthdate", "user-read-email", "streaming", "playlist-modify-private"});
```

The application pings the backend service and gets an access token and refresh token. But when I try to use that access_token to get the users display_name and profile pic I am getting a null in those fields. Do you think this is a possible bug or I am missing something especially when I am requesting for a new access_token from my back end service.

**Comment by kaaes** [comment]
@shroffrushabh what is the user name you're trying to check? In some cases those fields will be null because the user did not set their display name or profile picture (usually you would fall back to id in such case)

**Comment by shroffrushabh** [comment]
@kaaes its my own username and profile photo that I want, I can see those being populated in the spotify desktop app on the mac, so shouldn't it be available to me via the web spotify api?

**Comment by shroffrushabh** [comment]
@kaaes I just checked today morning and the access_token is allowing me to get the user info now, thanks for your help
