### ISSUE TITLE
playlist does not start on index=0 if last played song is in the new playlist

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/android-sdk#123]
if i start the top 100 with

mPlayer.play("spotify:user:spotify:playlist:4hOKQuZbraPDIfaGbM3lKI")
- Wiz Khalifa is played (first song)

if i select an other playlist, which also contains this song, the song ist played again instead of the first song in the playlist. 
spotify:user:spotify:playlist:4ldNPWkhPThHdq0FSxB0EZ

if i restart this playlist, its starts correct on index = 0

i tried mPlayer.clearQueue and tried to create an PlayerConfig with startindex=0. this also play the song twice. Only shutting down the mPlayer, Destroying the Spotify Instance and recreating everything new does work for me.

anyone has this issue?
best regards
Alex

**Comment by d-kunin** [comment]
Should not be a problem in beta 21.
