### ISSUE TITLE
Style / Hide Login Window

### ISSUE THREAD

**Issue by ckoessler** [spotify/android-sdk#126]
Is there a way to hide or style the login page with the progress bar?

Currently it is just a black popup that takes over the screen with a circling progress bar. It is confusing for the user as it doesn't show any Spotify logo, or message to explain what is going on.

Thanks!

**Comment by kaaes** [comment]
LoginActivity uses a small progress dialog with a transparent background. Did you add the correct theme to the manifest?
```
<activity
    android:name="com.spotify.sdk.android.authentication.LoginActivity"
    android:theme="@android:style/Theme.Translucent.NoTitleBar" />
```

**Comment by ckoessler** [comment]
Yes, I am using this theme. 
When the login takes couple seconds, the popup block any other interaction with the app and nothing indicates that it is Spotify that is trying to log in.

**Comment by kaaes** [comment]
The context for this indicator usually would come from a user action such as tapping on a "Login" button.
I guess you could use a custom theme for the LoginActivity but it's not possible to customise the progress dialog itself.

**Comment by roberttaylor426** [comment]
I tried using a custom theme in my `LoginActivity` declaration but I don't seem to be able to override the status bar color. Any attempts to set this to the color I use in the rest of my app are ignored.

Furthermore I agree with the OP, it would be nice to be able to style the progress bar, or hide it and display my own.

**Comment by d-kunin** [comment]
You can checkout the source code and propose your implementation in the dedicated repo: https://github.com/spotify/android-auth
