### ISSUE TITLE
Spotify Android SDK Tutorial - Cant play the track

### ISSUE THREAD

**Issue by supertreta** [spotify/android-sdk#127]
Hi,

I followed the tutorial "Spotify Andorid SDK Tutorial" (https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/) but after my login, the app doesn't play the track.

Despite having seen in multiple post , I didn´t forget the Internet permission in the manifest:
<uses-permission android:name="android.permission.INTERNET"/>

What can be the problem?

App log:
06-01 16:26:41.117    5495-5573/pt.spotifyandroidsdktutorial I/SpotifySDK﹕ Got notification: Became active playing device
06-01 16:26:41.135    5495-5573/pt.spotifyandroidsdktutorial I/SpotifySDK﹕ playbackCallbackOnSeek (to 0ms)
06-01 16:26:41.151    5495-5495/pt.spotifyandroidsdktutorial D/MainActivity﹕ Playback event received: BECAME_ACTIVE
06-01 16:26:46.320    5495-5573/pt.spotifyandroidsdktutorial I/SpotifySDK﹕ Temporary connection error occurred
06-01 16:26:46.332    5495-5495/pt.spotifyandroidsdktutorial D/MainActivity﹕ Temporary error occurred
06-01 16:26:47.146    5495-5495/pt.spotifyandroidsdktutorial D/MainActivity﹕ Login failed

**Comment by kaaes** [comment]
Please check what kind of error you're getting in the `onLoginFailed` callback.

**Comment by adarshakshetty** [comment]
Hi kaaes, 

i am also facing same problem, I created spotify account and application and generate key and I used Android Sdk sample code with my key. I am able to login, once login i recived Got notification: Became active playing device and playbackCallbackOnSeek (to 0ms) and Playback event received: BECAME_ACTIVE and Login failed .

Regards,
Adarsha

**Comment by kaaes** [comment]
@adarshakshetty please see my comment above. There's an error with more information in the `onLoginFailed`  callback.

**Comment by adarshakshetty** [comment]
Ok, Kaaes. Thanks for quick valuable response . onLoginFailed method  receiving "Operation required Premium account"   .  For testing sample app also required Premium account? .  Ok, I will try with Premium account and update you.

**Comment by adarshakshetty** [comment]
Hi kaaes,
How to test app from India? Any proxy settings in available ?

**Comment by adarshakshetty** [comment]
Hi kaaes,

Thank you, I am able to play audio stream from India with Premium Account.

Regards,
Adarsha

**Comment by lucabro** [comment]
There's a way to use a test account? I'm developing an android app and i need spotify authentication

**Comment by kaaes** [comment]
@lucabro no, I'm afraid you need to have a Spotify Premium account to be able to use this SDK

**Comment by lucabro** [comment]
Ok thankyou anyway

**Comment by adarshakshetty** [comment]
Hi kaaes,,

How to stop playing audio stream in Android web api. Any Audio controller in Android web api.

Regards,
Adarsha

**Comment by adarshakshetty** [comment]
Hi kaaes,,

How to stop playing audio stream in Android ..

Regards,
Adarsha

**Comment by adarshakshetty** [comment]
Hi kaaes,,

Player Stop method not able to call , please create method for Player stop able to call from our app.

Regards,
Adarsha

**Comment by adarshakshetty** [comment]
Hi,

Player Stop method not able to call , please create method for Player stop
able to call from any app.

when start playing immediately press device back button when stop and
destroyplayer the spotify also song is running even close the app. If song
is played after 30 seconds press device back button no issues
<https://github.com/spotify/android-sdk/issues/165>



Regards,
Adarsha

On Fri, Nov 6, 2015 at 7:10 PM, Kasia <notifications@github.com> wrote:

> Closed #127 <https://github.com/spotify/android-sdk/issues/127>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/android-sdk/issues/127#event-456920735>.
>



-- 
Thanks and Regards
Adarsha Shetty.k
