### ISSUE TITLE
Consider integration with ExoPlayer

### ISSUE THREAD

**Issue by fourlastor** [spotify/android-sdk#128]
Hello,

I noticed the Spotify player API is a bit awkward (`Spotify#destroyPlayer(reference)`) and doesn't play well if you have some other sources to play music with (since you have basically to switch players).

One option is to implement a Spotify [TrackRenderer](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/TrackRenderer.html) so Spotify songs will be playable via Google's [ExoPlayer](https://github.com/google/ExoPlayer).

This will also make mantaining the project easier since there's less thing you should actually work on.

**Comment by Ood-Tsen** [comment]
I think Spotify already did.

**Comment by fourlastor** [comment]
I honestly don't know, been a while since I last used this SDK. If they have added it/don't plan to add it to the roadmap they can simply answer and/or close it.

**Comment by ssawchenko** [comment]
I am also interested in this exact issue - could you please link to some documentation of this if it has been supported?

**Comment by d-kunin** [comment]
We didn't add it and don't have it planned, but it might be interesting to try it out. Let's keep as a feature request.

**Comment by ckoessler** [comment]
It would indeed be a great feature.

**Comment by d-kunin** [comment]
It seems like we will not be able to prioritize this issue any time soon.

**Comment by siegenthalerroger** [comment]
So...  "Let's keep this as a feature request" suddenly turned into "let's close this because it's not happening right now". That's not how issues and feature requests are supposed to work.
