### ISSUE TITLE
Login with a non-premium account doesn't fail

### ISSUE THREAD

**Issue by jeroenstevens** [spotify/android-sdk#129]
Hello,

When I'm requesting for authentication with the streaming scope and login with a non-premium account.
I still get an access_token and the response type is TOKEN. Shouldn't this result in getType returning ERROR instead? (Premium account is working fine btw.)

```java
    public void onSpotifyLoginRequired(SpotifyLoginRequired event) {
        AuthenticationRequest request = new AuthenticationRequest.Builder(
            getString(R.string.spotify_client_id),
            AuthenticationResponse.Type.TOKEN,
            REDIRECT_URI
        )
            .setScopes(new String[]{"streaming"})
            .build();

        AuthenticationClient.openLoginActivity(this, SPOTIFY_REQUEST_CODE, request);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        if (requestCode == SPOTIFY_REQUEST_CODE) {
            super.onActivityResult(requestCode, resultCode, intent);
            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, intent);
            switch (response.getType()) {
                case TOKEN:
                    Timber.d("Login successful");
                    break;
                case ERROR:
                    Timber.d("Login failed");
                    break;
            }
        }
    }
```

**Comment by kaaes** [comment]
@jeroenstevens you can obtain an access token for a free user and use it with the Web API. You won't however be able to login to the player using this token.

**Comment by jeroenstevens** [comment]
@kaaes My point is, how do I know if someone logged in with a free account or a premium account? Premium users I grant access to the player and free users not. Now I have to try and initialize the player and make it fail there, at that point I know but that's not nice. Why return a token if the requested scope is only "streaming"?

**Comment by kaaes** [comment]
You can check if user is free by [getting their profile](https://developer.spotify.com/web-api/get-current-users-profile/) from the Web API.
