### ISSUE TITLE
getArtistTopTrack needs required country param

### ISSUE THREAD

**Issue by jimbo1299** [spotify/android-sdk#130]
The following two methods won't work without **country** param:

    mService.getArtistTopTrack(artistId);
    mService.getArtistTopTrack(artistId, new Callback<Tracks>() {

You get a 404 
```
    {
        "error": {
            "status": 400,
            "message": "missing country parameter"
        }
    }
```

To get round this you can pass in options
```
Map<String, Object> options = new HashMap<>();
options.put("country", "GB");
```

But methods without options param should be fixed.

**Comment by kaaes** [comment]
This issue has been fixed in the Web API wrapper project. I'll close the issue
