### ISSUE TITLE
Facebook app not found, WebView is asking for credentials

### ISSUE THREAD

**Issue by McRonald** [spotify/android-sdk#132]
On Facebook-spotify login in a WebView using the authenticator in beta10, the app requests Facebook credentials and suggests to install the Facebook app for Android. But the Facebook app is installed on this phone. Is there a way to configure this or is this an upcoming fix maybe?

Tested on a HTC - One M8 with Android 5.0.1 - API 21.

![image](https://cloud.githubusercontent.com/assets/3762413/8460608/3aee2552-2026-11e5-88f1-d748290b58a7.png)

Best regards and keep on the good work!

**Comment by clevertrevor** [comment]
Hi McRonald,

I am received the same error and tested with version 9 of the beta and got it there as well. I believe that the LoginActivity is not checking to see that Facebook is installed.

Regards,
CleverTrevor

**Comment by jesseridgway** [comment]
Yep, having the same problem on beta10.

**Comment by McRonald** [comment]
How can we fix this? should we just wait until the next release or can we fork, push and hoping it get's included in the next release?

**Comment by d-kunin** [comment]
That is Spotify App issue that should be fixed at the moment.
