### ISSUE TITLE
The top tracks list JSON does not have a URL for full song playing through Android MediaPlayer

### ISSUE THREAD

**Issue by sherazahmed83** [spotify/android-sdk#133]
I am trying to pass a URL from the JSON response for an artist's top songs. But except the preview URL no URL is working. I need a URL to pass on to Android MediaPlayer to play full song. Anyone can help me on this.

For example this is the URL https://api.spotify.com/v1/artists/7krx6UBDKLwE0q3s3fesqF/top-tracks?country=US

But no URL from this JSON works with Android MediaPlayer class to give full Song streaming. Please help me.

"If Spotify only works with its own Player then also mention as well."

**Comment by ianhblakley** [comment]
You need to use the Player from the Spotify Player package. You can't use Android MediaPlayer at this time. Its outlined in the Android SDK tutorial
