### ISSUE TITLE
Will Beta 11 be RC? 

### ISSUE THREAD

**Issue by frel** [spotify/android-sdk#135]
Hi,

I know this is probably not the best place to ask, but I don't know where else to do it.
Will Beta 11 be a Release Candidate in terms of classes/methods? I am really looking forward to releasing my app, but I can't get myself to do it before I know the Spotify SDK will work in the same way.

Thank you
Regards Fred

**Comment by kaaes** [comment]
A bit late but well... it wasn't. There's at least one area where the API will change and it's around queuing. The rest shouldn't change much, at least in the player.
