### ISSUE TITLE
How to get user's playlists?

### ISSUE THREAD

**Issue by razikatz94** [spotify/android-sdk#136]
I followed the tutorial and am able to play the given track. Now i want to be able to get a list of users playlists and the tracks within, but there doesnt seem to be any information on this.

**Comment by lepsis3942** [comment]
Unfortunately it's not included in the current functionality of the library.  According to Spotify's developer site -

"The Android SDK does not currently have functions for metadata lookup or playlist management. For that, you need to use the Web API, with which you can communicate after receiving an OAuth token from the SDK. You can use a Spotify Web API Android wrapper." 

They suggest use of this library: https://github.com/kaaes/spotify-web-api-android

**Comment by razikatz94** [comment]
I managed to get my playlists and play songs from them. However, when I add a uri to player queue and call skiptonext, nothing plays. I verified that the uri passed to queue matches the uri for the song in spotify.
