### ISSUE TITLE
Should probably add some padding to the bottom of the confirmation page in the LoginActivity

### ISSUE THREAD

**Issue by jesseridgway** [spotify/android-sdk#137]
The included screenshot is scrolled to the very bottom of the page. Just a design nitpick.

![device-2015-07-16-114617](https://cloud.githubusercontent.com/assets/9370194/8732139/73df454a-2bb0-11e5-96eb-dbba7b3ea329.png)

**Comment by kaaes** [comment]
@jesseridgway this issue should now be fixed. Thanks for reporting
