### ISSUE TITLE
Spotify android SD example - cannot get player

### ISSUE THREAD

**Issue by dcoutts23** [spotify/android-sdk#139]
Hi all, followed the tutorial exactly. Seems to authenticate correctly, but get the 'Failed SpInit with error code 5 (An unexpected argument value was passed to a function)' when i attempt call getPlayer

Can anyone please provide any guidance or any more information required on this?

using 1.0.0-beta10 

    07-25 17:36:49.148    5820-5820/dave.spotifytest D/dalvikvm﹕ Trying to load lib /data/app-        lib/dave.spotifytest-1/libgnustl_shared.so 0x422382f0
    07-25 17:36:49.153    5820-5820/dave.spotifytest D/dalvikvm﹕ Added shared lib /data/app-lib/dave.spotifytest-1/libgnustl_shared.so 0x422382f0
    07-25 17:36:49.153    5820-5820/dave.spotifytest D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/dave.spotifytest-1/libgnustl_shared.so 0x422382f0, skipping init
    07-25 17:36:49.158    5820-5820/dave.spotifytest D/dalvikvm﹕ Trying to load lib /data/app-lib/dave.spotifytest-1/libspotify_embedded_shared.so 0x422382f0
    07-25 17:36:49.158    5820-5820/dave.spotifytest D/dalvikvm﹕ Added shared lib /data/app-lib/dave.spotifytest-1/libspotify_embedded_shared.so 0x422382f0
    07-25 17:36:49.158    5820-5820/dave.spotifytest D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/dave.spotifytest-1/libspotify_embedded_shared.so 0x422382f0, skipping init
    07-25 17:36:49.163    5820-5820/dave.spotifytest D/dalvikvm﹕ Trying to load lib /data/app-lib/dave.spotifytest-1/libspotify_sdk.so 0x422382f0
    07-25 17:36:49.163    5820-5820/dave.spotifytest D/dalvikvm﹕ Added shared lib /data/app-lib/dave.spotifytest-1/libspotify_sdk.so 0x422382f0
    07-25 17:36:49.183    5820-5871/dave.spotifytest E/SpotifySDK﹕ Throwing exception, failed SpInit with error code 5 (An unexpected argument value was passed to a function)
    07-25 17:36:49.198    5820-5871/dave.spotifytest W/System.err﹕ com.spotify.sdk.android.player.NativeSpotifyException: Failed SpInit with error code 5 (An unexpected argument value was passed to a function)
    07-25 17:36:49.208    5820-5871/dave.spotifytest W/System.err﹕ at com.spotify.sdk.android.player.NativeSdkPlayer.nativeInitialize(Native Method)
    07-25 17:36:49.218    5820-5871/dave.spotifytest W/System.err﹕ at com.spotify.sdk.android.player.NativeSdkPlayer.initialize(NativeSdkPlayer.java:79)
    07-25 17:36:49.228    5820-5871/dave.spotifytest W/System.err﹕ at com.spotify.sdk.android.player.Player.startRunLoop(Player.java:390)
    07-25 17:36:49.238    5820-5871/dave.spotifytest W/System.err﹕ at com.spotify.sdk.android.player.Player.access$100(Player.java:86)
    07-25 17:36:49.248    5820-5871/dave.spotifytest W/System.err﹕ at com.spotify.sdk.android.player.Player$1.run(Player.java:367)
    07-25 17:36:49.523    5820-5820/dave.spotifytest E/MainActivity﹕ Could not initialize player: com.spotify.sdk.android.player.NativeSpotifyException: Failed SpInit with error code 5 (An unexpected argument value was passed to a function)

**Comment by McRonald** [comment]
@dcoutts23 run debug against the getPlayer method, check your arguments and post them here. It's probably your settings in the Config class. (premium account is required for streaming)

**Comment by dcoutts23** [comment]
Thanks for the help. I have a premium account.
    
Here is my player config

    playerConfig = {com.spotify.sdk.android.player.Config@830039459272}
    brandName = {java.lang.String@830039467176}"HARDKERNEL_CO.,_LTD."
    uniqueId = {java.lang.String@830039466656}"d959db14f79bb267"
    cachePath = {java.lang.String@830039468912}"/storage/sdcard0/Android/data/dave.spotifytest/files"
    osVersion = {java.lang.String@830039477208}"4.4.4"
    clientId = {java.lang.String@830039476944}"##############################"
    oauthToken = {java.lang.String@830039455176}"#############################"
    displayName = {java.lang.String@830039466896}"spotifytest"
    modelName = {java.lang.String@830039467360}"odroid-u"
    mShouldUseCache = true
    deviceTypeIndex = 0
    cacheSizeLimitInMegabytes = 1024
    cacheAgeLimitInSeconds = 604800

Here is my call to getPlayer

    mPlayer = Spotify.getPlayer(playerConfig, this, new Player.InitializationObserver()

And looking at it in debug

    mPlayer = {com.spotify.sdk.android.player.Player@830039482640}
    mAudioController = {com.spotify.sdk.android.player.AudioTrackController@830039489048}
    mCacheExecutorService =                          {java.util.concurrent.Executors$DelegatedScheduledExecutorService@830039483160}
    mConnectionStateCallbacks = {java.util.Collections$SynchronizedSet@830039487256} size = 0
    mHandler = {android.os.Handler@830039663584}"Handler (android.os.Handler) {423823e0}"
    mInitializationState =   {com.spotify.sdk.android.player.Player$InitializationState@830039486360}"PENDING"
    mInitializedMutex = {java.lang.Object@830039485408}
    mPlayerNotificationMutex = {java.lang.Object@830039485440}
    mLoggedInMutex = {java.lang.Object@830039485424}
    mNativePlayer = {com.spotify.sdk.android.player.NativeSdkPlayer@830039671824}
    mPendingTasks = {java.util.LinkedList@830039487048} size = 0
    mPendingTasksMutex = {java.lang.Object@830039485456}
    mPlayerNotificationCallbacks = {java.util.Collections$SynchronizedSet@830039487352} size = 0
    mIsLoggedIn = false
    mShouldShutdown = false

**Comment by kaaes** [comment]
This issue should be fixed in beta11
