### ISSUE TITLE
Spotify Connect

### ISSUE THREAD

**Issue by sregg** [spotify/android-sdk#141]
That'd be awesome if we could have support for Spotify Connect.
That's the only feature missing on my Android TV app (https://play.google.com/store/apps/details?id=com.sregg.android.tv.spotify)

**Comment by vltmn** [comment]
+1

**Comment by emptyflash** [comment]
+1

**Comment by jvlomax** [comment]
+1

**Comment by RobertBorg** [comment]
+1

**Comment by chrishale** [comment]
+1

**Comment by tsengstudios** [comment]
+1

**Comment by d-kunin** [comment]
This SDK has no plans to support Connect at the moment.

**Comment by stevenkang90** [comment]
has this moved at all? i've seen spotify connect is available as a web api now. Im wondering if there are any plans to make the SpotifyPlayer show in in connect?
