### ISSUE TITLE
2 Step FB auth broken

### ISSUE THREAD

**Issue by chrishat-shazam** [spotify/android-sdk#145]
During the 2-step authentication process the user has to leave the Spotify authentication window (in order to get to the numeric code for the 2nd step). When you try to go back to it, it doesn't remember where you were, it just restarts the whole process. So you have the code but nowhere to enter it and have to start again and there's no way to pass 2-step auth.

**Comment by YeomansIII** [comment]
I am also experiencing this problem.  If the Facebook auth properly recognized the Facebook account on the device in the first place, this would not be an issue.

**Comment by kaaes** [comment]
2 step authentication is fixed in beta11 but #132 is a different issue.
