### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by dcamp200** [spotify/android-sdk#148]
I'm having an issue with my app crashing after a period of time.  I am playing a series of songs one after the other by passing in the song's id to the player.
It works fine for about 60-90 minutes and then crashes.
The logs have a series of messages like the following (for each song).

I/SpotifySDK﹕ Got notification: Track changed
I/SpotifySDK﹕ Got notification: Play
I/SpotifySDK﹕ Got notification: Track started
I/SpotifySDK﹕ Got notification: Audio flush

The app crashes after audio flush message with an Android message about "Too many files open".
I've looked at my code to see if it it anything I am doing but there is nothing apparent that really points to that.  Is it possible there is something like an FD or stream that is not getting closed in the SDK?  Is there something I am not doing properly e.g. should I be starting a creating a new player after each song?  I am following the sample code in the tutorial.
Thanks

**Comment by bsatorius** [comment]
@dcamp200 did you solve this? I'm having the exact same problem. Thought it was auth-token related, but I'm refreshing the token now and no luck yet.

**Comment by dcamp200** [comment]
Hi there,
Actually I'm not sure.  I spent hours and hours trying different things,
eliminating possibilities, probably the same as yourself.  The stack traces
are coming from the Android runtime - too many open files which I think it
is a bit misleading.
I tried eliminating Spotify from the equation and I was still getting the
error.  I also thought it was hardware acceleration related but that turned
out to not be it.
The latest thing I'm trying is to not keep my app screen on with
getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
and yesterday I was actually seeing some promising results by removing this
line.  I'm not sure if you are doing this or not.

Sorry I can't be of more help.  If I solve it I will let you know.  Please
let me know if you find anything as well.  I have spent a considerable
amount of tie on it.

David

**Comment by bsatorius** [comment]
Thanks for the details, David. It sounds like you're a little farther along on isolating this problem. My initial troubleshooting centered on auth token refreshing. The Spotify auth token expires after an hour, so my theory was the expired token was causing a lock up in the SDK. I moved to a code-based auth flow using an external webservice that pushed a new token to the client after thirty minutes. That change appears to have had little effect on solving this problem.
 
I'd be curious to know if anyone has been able to achieve continuous playback for two hours with the SDK. I'll keep trying to isolate this on my side and will keep you posted on any new updates.

Thanks,
Brian

**Comment by kaaes** [comment]
@dcamp200 @bsatorius one more thing you could try is to disable caching of the tracks:
```
Config playerConfig = new Config(getApplicationContext(), token, CLIENT_ID);
playerConfig.useCache(false);
```
It's highly unlikely it's related to access token. You only need it to login to the player. Once this happens it doesn't matter if the token expires - the session will remain valid until you log out or lose network connection.

**Comment by dcamp200** [comment]
Hi Brian, Thanks for the token.  I get at most 80 minutes of music, almost
to the minute and it's pretty much reproducible.
Hope it helps.

**Comment by bsatorius** [comment]
Good to know @kaaes - going to try removing track caching with the basic Spotify sample app and see how long it plays. Will follow up.

**Comment by dcamp200** [comment]
@kaase  Thanks Kasia. This appears to have fixed things!  I've been playing
for a couple of hours now and it seems to be working.  It also seems to
have fixed another issue I had opened about the caching growing.

David

**Comment by dcamp200** [comment]
Hi guys, I there might be an additional access token issue after all.  After about an hour of play, when I try to call any api that requires OAuth, I do get a 401 Unauthorized error.
Any luck with this Brian?
Otherwise i can continue to play music without issues now, over 24 hours in some cases.

-David

**Comment by bsatorius** [comment]
David, you'll have to change your auth method from "token" to "code" like so -

        AuthenticationRequest.Builder builder =
                new AuthenticationRequest.Builder(Constants.CLIENT_ID_SPOTIFY, AuthenticationResponse.Type.CODE, Constants.REDIRECT_URI_SPOTIFY);

When the callback returns, you'll have a "code" returned rather than an auth token. Spotify uses a standard OAuth-style model for granting access. You must take this code returned from the callback and request a refresh token and auth token from the Spotify web api endpoint 'https://accounts.spotify.com/api/token". You'll use the auth token to initialize your player, and the refresh token for obtaining additional auth tokens as they expire.

So, a lot more work than client-side token-based, but necessary if you want 1hr+ sessions against the Spotify web api.

**Comment by dcamp200** [comment]
Thanks Brian, much appreciated.  I'll try that.
I found these other tickets as well that pretty much describe what you are saying except I believe they recommend using a call back server..I think so you don't have to expose your CLIENT ID. Maybe I am mis-interpreting it though.
https://github.com/spotify/android-sdk/issues/47
and
https://developer.spotify.com/web-api/authorization-guide/


Cheers.

**Comment by shroffrushabh** [comment]
@kaaes I am also running into a similar situation. I am going to use the
```
Config playerConfig = new Config(getApplicationContext(), token, CLIENT_ID);
playerConfig.useCache(false);
```

Hope it works

**Comment by shroffrushabh** [comment]
@kaaes also about your comment on the access token "the session will remain valid until you log out or lose network connection" I have a service which get a new session token every 45 minutes, do you think I should scrap that and use the same session token for say 2 hours (beyond the 1 hr limit) and if the user loses connection or logs out then only refresh it?

**Comment by louiswilliams** [comment]
I want to confirm that setting `useCache(false)` does fix this problem. I was getting an EMFILE error for having "too many files open". I originally thought it was an issue with a file descriptor leak in my own code, then found this post. This happens only when the phone is sleeping, granted I haven't waited long enough plugged-in to observe it. The player runs inside a foreground service.

@kaaes Is this a bug in the cache implementation? It is kind of unfortunate that to stream for extended periods you have to sacrifice disk caching.

**Comment by dcamp200** [comment]
I can confirm it did fix the problem (resolved the crashes) for me however
my users have reported increased data usage now.
@kaaes Can we reopen this issue?
