### ISSUE TITLE
is:issue is:open Play downloaded/offline tracks on airplane mode (ie no internet connection)

### ISSUE THREAD

**Issue by camillo777** [spotify/android-sdk#149]
Hi,
I am writing an application using the Spotify SDK for Android.
I have Spotify Premium and I can download offline tracks.
But it seems with the Android SDK is possible to play tracks only after Spotify online authentication.
How can I use Android SDK to play tracks when I don't have internet connection on my device?
Thank you!
Camillo

**Comment by kolletzki** [comment]
Sadly, this is not possible at the moment, see #2

**Comment by camillo777** [comment]
Even if I set player connectivity to offline the player will not play available offline downloaded  tracks? 
Thanks 
Camillo

**Comment by siegenthalerroger** [comment]
Yes it will not work as long is #2 is not implemented. @kaaes you could close this as a duplicate.
