### ISSUE TITLE
Pitch modification

### ISSUE THREAD

**Issue by craziemac** [spotify/android-sdk#150]
Are there any plans on implementing a possibility to adjust the bpm of songs played?

**Comment by joekickass** [comment]
Yeah, would be nice.

**Comment by Wolftein** [comment]
I believe that is against Spotify T.O.S

"Editing, Modifying, and Altering. Except as set out in this paragraph or agreed upon by Spotify in writing, you shall not edit, modify, alter or create derivative works of Spotify Content in any way."

**Comment by kaaes** [comment]
I'm closing it as it's not an issue with the library and modification of the audio stream is not allowed by Spotify TOS
