### ISSUE TITLE
sportify SDK Is able to support in eclipse IDE???

### ISSUE THREAD

**Issue by dyraval** [spotify/android-sdk#151]
Am i used ecllipse juno. in  these ide converting spotify .aar file into .jar and put in libs but generate errror @runtime  like

1> java.lang.NoClassDefFoundError: com.spotify.sdk.android.R$layout

2> at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java:43)

i want to know is there any solution to run spotify in ecllipse??

**Comment by kaaes** [comment]
@dyraval this project doesn't have the official Eclipse support but you can the solution described here: #74

**Comment by marig345** [comment]
Figure it out
