### ISSUE TITLE
Wrong reference to player in tutorial

### ISSUE THREAD

**Issue by r0stig** [spotify/android-sdk#152]
This is a report of a mistake in the beginners tutorial (https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/).

The code for "onActivityResult" in the "InitializationObserver" is like this right now:
````
@Override
 public void onInitialized(Player player) {
    mPlayer.addConnectionStateCallback(MainActivity.this);
    mPlayer.addPlayerNotificationCallback(MainActivity.this);
    mPlayer.play("spotify:track:2TpxZ7JUBn3uw46aR7qd6V");
}
````

But shouldn't the method use the player object from the arguments, like this?
````
@Override
public void onInitialized(Player player) {
    player.addConnectionStateCallback(MainActivity.this);
    player.addPlayerNotificationCallback(MainActivity.this);
    player.play("spotify:track:2TpxZ7JUBn3uw46aR7qd6V");
}
````

With the code from the tutorial I got an error when I've tried to create a new player after screen reorientation which got solved when used the argument player:

````
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.spotify.sdk.android.player.Player.addConnectionStateCallback(com.spotify.sdk.android.player.ConnectionStateCallback)' on a null object reference
            at se.example.projec.tMainActivity$2.onInitialized(MainActivity.java:117)
````

And line 117 was this one:
````
player.addConnectionStateCallback(MainActivity.this);
````

**Comment by kaaes** [comment]
Thank you for reporting this. We updated the documentation to use a more robust code. Nice catch :)
