### ISSUE TITLE
Changing  audio quality doesn't appear to work

### ISSUE THREAD

**Issue by dcamp200** [spotify/android-sdk#154]
I tried using this api in during the play initialization - during the onInitialized call back.
 musicPlayer.setPlaybackBitrate(PlaybackBitrate.BITRATE_HIGH);

But it does not seem to have any noticeable effect.  Is there a proper way to call this?  How would you know if it is working? It there a discernible difference? 

Thanks.

p.s. Is this project still active? There does not seem to have been very much activity lately.

**Comment by jhmacdon** [comment]
+1, attempting to change bitrate based on connection and not having any luck.

**Comment by d-kunin** [comment]
This will take effect for the next chunk of audio data that is streamed
  from the backend. The format or sample rate of the audio data that is
  received by AudioController does not change.

How do you try to measure if it works? You can try to see network consumption.
