### ISSUE TITLE
openLoginActivity does nothing if screen is locked

### ISSUE THREAD

**Issue by zond** [spotify/android-sdk#157]
Hello Spotify!

I'm building an alarm clock app (or well, integrating the Spotify Android SDK with the AOSP alarm clock), and this makes it necessary to call openLoginActivity when the screen is locked.

This does nothing at all - no login activity shows up, and no `onActivityResult` is called.

Using a `wakeLock = pm.newWakeLock(PowerManager.ACQUIRE_CAUSES_WAKEUP | PowerManager.ON_AFTER_RELEASE | PowerManager.PARTIAL_WAKE_LOCK, "Clockify");
` works _sometimes_ (I get the callback, since your login activity already has a refresh token I assume), but not always.

Do you have any clues as to why the login activity doesn't work if the screen is locked?

**Comment by d-kunin** [comment]
@zond have your tried something like this http://stackoverflow.com/questions/20113161/start-activity-screen-even-if-screen-is-locked-in-android ?
Please reopen if the issue is still relevant.
