### ISSUE TITLE
Showing Login Failed everytime... even i have entered correct credentials...!!!

### ISSUE THREAD

**Issue by pinkalmistry** [spotify/android-sdk#158]
Hello, 
I have created android demo app to play track online... i m accessing this things from india and my log in account is from franc. in web i m able to login successfully and able to play tracks. but when i login into android app it displaying me that... Login Failed.. i am using soptify sdk version "SpotifySdkAndroid-1.0.0-beta11"... 

I m not a premium user,, so that it will not allow me to get log in  ? can you please let me know.

**Comment by mattiamaestrini** [comment]
Quoting from the [README.md](https://github.com/spotify/android-sdk/blob/master/README.md):

> Only Premium Spotify users will be able to log in and play music with this library.

**Comment by kaaes** [comment]
Yes, the premium account is required to play tracks using this SDK. I'll close the issue

**Comment by Canatsey** [comment]
Stop emailing me that is 11 today
