### ISSUE TITLE
This beta11 sdk can not dependencies on Android Studio 

### ISSUE THREAD

**Issue by shylauc** [spotify/android-sdk#161]
Error:(34, 13) Failed to resolve: com.spotify.sdk:spotify-auth:1.0.0-beta11

Please help

**Comment by kaaes** [comment]
@shylauc please make sure that the libraries are copied to the `libs` folder and that your `build.gradle` file contains a reference to the local repository as described in the [Tutorial](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/#installing-the-android-sdk)
