### ISSUE TITLE
Huge increase of size in version 1.0.0-beta11

### ISSUE THREAD

**Issue by mattiamaestrini** [spotify/android-sdk#162]
In the latest version of the SDK, the size of `spotify-player-1.0.0-beta11.aar` is 5.57 MB, compared to 1.60 MB of the previous version (beta10).

This size bump is caused by the JNI library `libgnustl_shared.so`.

Is this intentional? If so, is it necessary to the well functioning of the SDK?

**Comment by kaaes** [comment]
Thanks for reporting. This is something that will be fixed in the next release

**Comment by kaaes** [comment]
beta12 is back to its old ~1.5MB :)

**Comment by mattiamaestrini** [comment]
Thanks!
