### ISSUE TITLE
Get next/previous song in queue

### ISSUE THREAD

**Issue by Meisolsson** [spotify/android-sdk#163]
Would there be a possibility to get the next/previous song from the queue OR the entire queue. Would be nice when adding album art to have the ability to pre-fetch the images.

**Comment by kaaes** [comment]
@Meisolsson no, the SDK currently doesn't provide this functionality. You could create a list of tracks and play them in the player, then you would know the tracks beforehand

**Comment by Meisolsson** [comment]
Any idea if it will be added in the future?

**Comment by kaaes** [comment]
It's not on the roadmap for the project but this issue tracker is a good place to ask for new features. We take this input into consideration when planning the work.

**Comment by markrjr** [comment]
@Meisolsson I'd like to chime in and note that it's actually really nice that it's implemented this way, particularly because it gives you the freedom to design your own queue around the Spotify player object, whether or not that be a simple ArrayList or a complex object is up to you.

**Comment by stevenhewitt** [comment]
I'll just give my 2 cents on this.

I've been trying to make a separate, custom queue that tries to follow along whenever the spotify player goes to the next song.  But I'd say without a getQueue() or something in the spotify playerstate, it makes it extremely difficult and finicky to keep my custom queue in sync with what the spotify player is playing. Responding to various TRACK_CHANGED, or SKIP_NEXT, etc. works most of the time, but isn't reliable especially when the user starts skipping around.  The only way to make it stable is to check whenever the playerState.trackUri changes, although that then breaks when the same song appears twice.  So unless a getQueue() or similar function is implemented, I'll just load one song at a time into the spotify player and when it ends/is skipped, I manually play the next one in my queue.

**Comment by markrjr** [comment]
I agree. I just ugpraded and with the deprecation of TRACK_START and TRACK_END, it kind of makes responding to the flags impossible, and therefore building a custom queue a lot harder. Either the SDK needs to implement some sort of queue or expose enough of itself to allows users to create one around it (i.e. The Android MediaPlayer class).

**Comment by d-kunin** [comment]
`com.spotify.sdk.android.player.SpotifyPlayer#getMetadata` gives you prev,current, and next tracks since beta 21. The queue will not be exposed completely any time soon. Instead of track_start/end you should use `kSpPlaybackNotifyTrackChanged` and `kSpPlaybackNotifyTrackDelivered`.
Happy coding!
