### ISSUE TITLE
Failed SpTrackListLoad with error code 4

### ISSUE THREAD

**Issue by vishnuv1228** [spotify/android-sdk#166]
I retrieve an existing playlist from the user (using the spotify web api) and send its playlist id to a new activity. Once received, I place the uris from the playlists in a list of strings. I call mPlayer.play(URIList); 9/10 times however, I receive the following error:

Throwing exception, failed SpTrackListLoad with error code 4 (An unexpected NULL pointer was passed as an argument to a function)
11-26 03:51:36.065 14030-14104/? W/System.err: com.spotify.sdk.android.player.NativeSpotifyException: Failed SpTrackListLoad with error code 4 (An unexpected NULL pointer was passed as an argument to a function)
11-26 03:51:36.065 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.NativeSdkPlayer.nativePlayTrackList(Native Method)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.NativeSdkPlayer.playTrackList(NativeSdkPlayer.java:168)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.Player$14.call(Player.java:855)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.Player$14.call(Player.java:851)
11-26 03:51:36.066 14030-14104/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.Player.startRunLoop(Player.java:477)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.Player.access$100(Player.java:86)
11-26 03:51:36.066 14030-14104/? W/System.err:     at com.spotify.sdk.android.player.Player$1.run(Player.java:367)

**Comment by kaaes** [comment]
@vishnuv1228 could you post the code you're using to create and play the list of tracks?

**Comment by vishnuv1228** [comment]
In my MainActivity.java:  
// Check if this playlist already exists

                spotify.getPlaylists(USER_ID, new SpotifyCallback<Pager<PlaylistSimple>>() {
                    @Override
                    public void failure(SpotifyError spotifyError) {
                        Log.d(TAG, "Error in getting user's playlists: " + spotifyError);
                    }

                    @Override
                    public void success(Pager<PlaylistSimple> playlistSimplePager, Response response) {
                        Boolean exists = false;
                        Log.d(TAG, "Success in getting user's playlists");
                        List<PlaylistSimple> playlists = playlistSimplePager.items;
                        for (PlaylistSimple playlist : playlists) {
                            Log.d(TAG, "Retrieved Playlist: " + playlist.name);
                            if (playlist.name.equals(auto)) {
                                Log.d(TAG, "Default Playlist EXISTS");
                                PLAYLIST_ID = playlist.id;
                                moveToPlayScreen();
                                exists = true;

                            }
                        }
                        if (!exists) {
                            // search for songs
                            searchTracks(spotify, tempStreet);
                            Map<String, Object> body = new HashMap<>();
                            body.put("name", auto);
                            body.put("public", false);
                            spotify.createPlaylist(USER_ID, body, new SpotifyCallback<Playlist>() {
                                @Override
                                public void failure(SpotifyError spotifyError) {
                                    Log.d(TAG, "Error in creating new playlist: " + spotifyError);
                                }

                                @Override
                                public void success(Playlist playlist, retrofit.client.Response response) {
                                    PLAYLIST_ID = playlist.id;
                                    Log.d(TAG, "Successfully created new playlist");
                                    // Add tracks to auto-generated playlist
                                    for (int i = 0; i < trackObjs.size(); i++) {
                                        Map<String, Object> parameters = new HashMap<>();
                                        parameters.put("uris", trackObjs.get(i).uri);
                                        spotify.addTracksToPlaylist(USER_ID, PLAYLIST_ID, parameters, parameters, new SpotifyCallback<Pager<PlaylistTrack>>() {
                                            @Override
                                            public void failure(SpotifyError spotifyError) {
                                                Log.d(TAG, "Error in adding tracks to auto-generated playlist: " + spotifyError);
                                            }

                                            @Override
                                            public void success(Pager<PlaylistTrack> playlistTrackPager, retrofit.client.Response response) {
                                                Log.d(TAG, "Success in adding track to auto-generated playlist");
                                                //Toast.makeText(getApplicationContext(), "Saved to Auto-generated Playlist", Toast.LENGTH_LONG).show();

                                            }
                                        });
                                    }


                                }
                            });
                        }
                    }
                });

In PlayScreen.java:
// Get current playlist and add into list of tracks
        spotify.getPlaylist(SPOTIFY_USER_ID, SPOTIFY_PLAYLIST_ID, new SpotifyCallback<Playlist>() {

            @Override
            public void failure(SpotifyError spotifyError) {
                Log.d(TAG, "Error in getting playlist: " + spotifyError);
               // Toast.makeText(getApplicationContext(), "Could not query the spotify servers", Toast.LENGTH_LONG);
                finish();
            }

            @Override
            public void success(Playlist playlist, Response response) {
                Log.d(TAG, "Success -  got playlist");
                for (PlaylistTrack track : playlist.tracks.items) {
                    tracksInPlaylist.add(track.track.uri);
                    trackObjs.add(track.track);
                }
            }
        }); 
Config playerConfig = new Config(this, SPOTIFY_ACCESS_TOKEN, SPOTIFY_CLIENT_ID);


        mPlayer = Spotify.getPlayer(playerConfig, this, new Player.InitializationObserver() {
            @Override
            public void onInitialized(Player player) {
                mPlayer.addConnectionStateCallback(PlayScreen.this);
                mPlayer.addPlayerNotificationCallback(PlayScreen.this);
                mPlayer.play(tracksInPlaylist);
            }

            @Override
            public void onError(Throwable throwable) {
                Log.e(TAG, "Could not initialize player: " + throwable.getMessage());
            }
        });

**Comment by kaaes** [comment]
It looks like you're issuing the `play` command before `spotify.getPlaylist` finishes which would send the empty track list to the player. You could verify that by logging out the size of `tracksInPlaylist` just before sending `play`

**Comment by vishnuv1228** [comment]
Yes! That was the issue. Thank you!
