### ISSUE TITLE
Sign-up page rejects Android debug cert SHA1

### ISSUE THREAD

**Issue by ResonantCavity** [spotify/android-sdk#167]
I'm following the instructions here, and the registration form will not accept accept my SHA1 as valid. I'm getting the certificate by using

```keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore -list -v | grep SHA```
and I confirmed that this is the certificate that Android Studio is using by creating a new MapActivity in my package and checking the google_maps_api.xml file. I have tried appending ".debug" to the end of the SHA1 with no success. I have removed colons from the hash also.

I'm at a loss here. Help is appreciated.

**Comment by joekickass** [comment]
Got the same problem. Seems the web form only accepts 21(?!) bytes SHA1 instead of 20 bytes. You can try this by appending an extra ':FF' (this will of course not work).

**Comment by kaaes** [comment]
Thanks for letting us know! The fix is coming. I'll update this issue once it's out

**Comment by ResonantCavity** [comment]
Thanks! Write a test!

**Comment by kaaes** [comment]
The website is updated and will now accept the fingerprints. Please let us know if you have any more problems.
