### ISSUE TITLE
Why is the minSdk=15 for 1.0.0-beta12?

### ISSUE THREAD

**Issue by condesales** [spotify/android-sdk#170]
After upgrading from beta11 to beta12 I'm now having problems with the minSdk version.
Gradle build complains that minSdk version from project is smaller than lib minSdk version.
It tells me about `overrideLibrary` option in AndroidManifest.xml in order to fix the issue

```Error:Execution failed for task ':<ProjectName>:processServerDebugManifest'.
Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.spotify.sdk:spotify-auth:1.0.0-beta12] /Users/<UserName>/devel/android/<ProjectName>/build/intermediates/exploded-aar/com.spotify.sdk/spotify-auth/1.0.0-beta12/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.spotify.sdk.android.authentication" to force usage```

but this still not fixing the problem for me

Any ideias?

**Comment by kaaes** [comment]
@condesales if your app needs to work with SDK 14, `overrideLibrary` should allow you to do this.
I found this solution to work for the test app: https://stackoverflow.com/questions/27095077/how-do-i-use-toolsoverridelibrary-in-a-build-gradle-file

**Comment by condesales** [comment]
Yeah, I've tried that without lucky. 
I'll give it another look.

@kaaes If you say that this would solve the issue, it means that the library could get downgraded to support SDK 14, isn't it?
What forced the upgrade from SDK 14 to 15 in the library in first place?

**Comment by condesales** [comment]
Any new about this?

**Comment by d-kunin** [comment]
We moved from 14 to 15 the same way as Spotify Android App did and there is no way back. Sorry.

**Comment by condesales** [comment]
that's all good. it seems 14 shouldn't be supported any longer anyways.
👍
