### ISSUE TITLE
metaDataChanged broadcast sent incorrectly.

### ISSUE THREAD

**Issue by liamwli** [spotify/android-sdk#171]
If the app is closed (fully), and then reopened, when a song was playing, then when the Spotify app is re-opened, the metaDataChanged broadcast is sent twice.

The first time, the broadcast is sent with an empty trackId value, the second time is the valid broadcast.

**Comment by kaaes** [comment]
This sounds like a correct behaviour - the app starts and reports the changes in its state.
This functionality is not a part of this SDK so I'll close this issue.
