### ISSUE TITLE
Authentication Response Error

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/android-sdk#172]
When trying to login via the Spotify App, I am getting the response INVALID_APP_ID.
If a device doesn't have the Spotify App, the login will work.

I have checked the code is the same as the example.

**Comment by lepsis3942** [comment]
You need to follow these instructions to authenticate with the Spotify app.  [Here](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/#registering-application-fingerprints)

**Comment by Brad-Jackson** [comment]
Cheers, missed that bit.

**Comment by Brad-Jackson** [comment]
So I have successfully updated one app. However I am still getting INVALID_APP_ID on another app.
I have check the client code / secret to make sure that the keys are going in to the correct one.
I have unzipped the apk to confirm the key is correct and I have used aapt to get the package name from the apk. The only difference that I can find is on the developer website where I enter the package name I have to add com.nightlife.crowddj, where the actual package name is com.nightlife.crowdDJ .

Other than that I have no idea.
Help

**Comment by stefannilsson** [comment]
App package names are in general case-sensitive. So I'd recommend to either repackage your app with the registered case, or simply re-create the app at [My Apps](https://developer.spotify.com/my-applications) - with the matching case as the app.

**Comment by Brad-Jackson** [comment]
That's not possible the app is in the store and people are using it. The web site needs to allow upper case.

**Comment by kaaes** [comment]
@Brad-Jackson thanks for reporting this, we'll fix the website

**Comment by Brad-Jackson** [comment]
The website works now. Thanks
