### ISSUE TITLE
How to stop current playing track

### ISSUE THREAD

**Issue by adarshakshetty** [spotify/android-sdk#173]
how to stop spotify streaming  ?

**Comment by stefannilsson** [comment]
Is it the **pause()**-method you're looking for?
https://developer.spotify.com/android-sdk-docs/player/

**Comment by adarshakshetty** [comment]
No, I want to stop current track  like when song is playing if I move out from that screen song should close.
On Jan 4, 2016 1:51 AM, Stefan Nilsson <notifications@github.com> wrote:Is it the pause()-method you're looking for?
https://developer.spotify.com/android-sdk-docs/player/

**Comment by xplodwild** [comment]
Which is what the pause() method is doing - stopping the playback of the current track. There is no "stop()" method - pausing the track is enough.

**Comment by adarshakshetty** [comment]
I used pause no help. If song is playing if I use pause I am able to stop.
But in the case song is playing if I press device back button even I called
pause also song is continues playing

**Comment by kaaes** [comment]
@adarshakshetty as mentioned above `pause()` is the proper way of stopping the playback. If the music doesn't stop when you press back button it most likely means that this method is not called. Please verify that `pause()` is executed when you press back button.

**Comment by adarshakshetty** [comment]
@Kaisa its calling  if song start playing after  30 seconds pause is
working for me perfectly but my problem if try to stop before 30 seconds
pause will not help to stop the song.  Is it possible to release the mic
from pause ().  I tried with shutdown() but it's cause some other problems
and app will crash.
On Jan 7, 2016 7:42 PM, "Kasia" <notifications@github.com> wrote:
>
> @adarshakshetty as mentioned above pause() is the proper way of stopping
the playback. If the music doesn't stop when you press back button it most
likely means that this method is not called. Please verify that pause() is
executed when you press back button.

**Comment by d-kunin** [comment]
You can't completely stop current playback.
