### ISSUE TITLE
Spotify Test Account

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/android-sdk#176]
Hi, today i had a user who complained that my android app does not work for him. we find out that his account is not flagged as "PREMIUM". It is a 3-month-test-abo which is flagged as "OPEN". 

so the android sdk does not support these "test-abos" ??  is that right?

best regards
Alex

**Comment by hammar83** [comment]
As stated in the docs, the subscription level "open" can considered the same as "free".
[Web API Object Model](https://developer.spotify.com/web-api/object-model/#user-object-private)

**Comment by kaaes** [comment]
@digitaldesaster that is an interesting case. I can ask about it but I'd need to know what this "3-month-test-abo" is. Are we talking about one the "3 months for 9kr" offers or is it something else?

**Comment by digitaldesaster** [comment]
it is a offer in germany for people who didnt used spotify in the past. the first 3 months are free if you sign up. if i open this page there is a offer for one month for free. seems to be the same.   https://www.spotify.com/de/premium/?checkout=false
from the functionality it is a premium account  if you use the official apps. 

i understand that you have to separate between real premium users and people who are using a test account. but from the functionality point of view regarding the sdk it is a bad thing. 

@kaaes it would be great if you could check it. for my opinion the functionality should be the same for the sdk as in the official apps with these test accounts.

**Comment by kaaes** [comment]
@digitaldesaster users in the trial mode should get a full premium treatment (including the SDK access). Can you give us the username this issue occurs for?

**Comment by digitaldesaster** [comment]
username is
Michael.Heberer

**Comment by kaaes** [comment]
@digitaldesaster thank you
Just to clarify - when this user tries to log in, what is the error they're seeing? If it's the problem with premium vs free it would be "The operation requires a Spotify Premium account"

**Comment by digitaldesaster** [comment]
yes, onLoginFailed is thrown and the detailMessage is 
"The operation requires a Spotify Premium account"

his user id is "michael.anton.heberer-de". he told me that he upgraded to a Premium Account today, but his account has still the status "Open".

**Comment by kaaes** [comment]
@digitaldesaster I asked around and it's most likely the case where user has multiple accounts and not all of them are premium so they should double check which account they're trying to log in with.

**Comment by digitaldesaster** [comment]
thanks for your feedback. so in generally these trial accounts ("OPEN") should work like an premium account?

**Comment by kaaes** [comment]
@digitaldesaster if this is the "product" info from the Web API it is not 100% reliable. Probably the best place to check is user's account page (https://www.spotify.com/account) or reaching out to the Customer Support.
