### ISSUE TITLE
 Failed to resolve: com.spotify.sdk:spotify-auth:1.0.0-beta12 

### ISSUE THREAD

**Issue by Sultani00** [spotify/android-sdk#177]
Hi, 
I have problems getting build.gardle to work , I keep getting errors like "  Failed to resolve: com.spotify.sdk:spotify-auth:1.0.0-beta12  " . Please what I can I do to solve this issue.

Here is my code : 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1" // Note: this version should match the latest build-tools version
    // that you installed in the SDK manager

    defaultConfig {
        applicationId "com.android.application.spotifystreamer.app"
        minSdkVersion 10
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // This library handles authentication and authorization
    compile 'com.spotify.sdk:spotify-auth:1.0.0-beta12@aar'

    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player:1.0.0-beta12@aar'

    // All other dependencies for your app should also be here:
    compile 'com.android.support:appcompat-v7:23.1.1'
}

Any help would be highly appreciated .

Thank you.

**Comment by stefannilsson** [comment]
Have you copied the aar-files into /app/libs?
https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/

**Comment by Sultani00** [comment]
Yes I already did

**Comment by hammar83** [comment]
Minimum SDK has to be 15, but that shouldn't result in this error (?).

**Comment by Sultani00** [comment]
I tried changing that as well, still no luck

**Comment by kaaes** [comment]
@Sultani00 this build file looks correct. One thing that comes to mind - are the dependencies added to the correct `build.gradle` file? They need to be in the one inside app module (not the one in the root folder of the project)

**Comment by Sultani00** [comment]
Hi Kases,
Do they need to be in /app/libs or just in the app folder of the project?
Thank you

**Comment by kaaes** [comment]
@Sultani00 `app/libs`, the path in `flatDir.dirs` is relative to the build file it's defined in

**Comment by Sultani00** [comment]
Hi @kaaes 
i tried changing it but still no luck

**Comment by kaaes** [comment]
Here's a working setup:

![screen shot 2016-01-12 at 11 11 12](https://cloud.githubusercontent.com/assets/202548/12260823/e9df20b2-b91d-11e5-85b8-eb3b232d7777.png)

And the highlighted build file contents is:

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "kaaes.spotify.webapi.samplesearch"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile(name: 'spotify-auth-1.0.0-beta12', ext: 'aar')
    // other deps
}
```
If this doesn't work something might be wrong with your environment. In this case cleaning the build or creating a fresh project should help

**Comment by Sultani00** [comment]
Hi @kaaes ,

Thank you so very much. It worked like a charm. 

My mistake was that I was adding the whole folder sdk folder into the app folder instead of the .aar file alone.

Thank you so much.

**Comment by corriejgreen** [comment]
Just going to ask a follow up, there is no arr file in the repo for auth-1.0. Is this now using a different set up from the spotify set up tutorial? Ta

**Comment by andras-gyarmati** [comment]
I couldnt find any aar files at the location the tutorial points at eizher, but I found aar files here https://github.com/spotify/android-sdk/tree/master/samples/DemoProject/libs

**Comment by erikghonyan** [comment]
The auth library is now available on jcenter

```gradle
compile 'com.spotify.android:auth:1.0.0-alpha'
```

**Comment by JoseGeorges8** [comment]
can somebody help me set up spotify sdk? quick latest lines to compile

**Comment by hiranandanisonal** [comment]
please help with same issue, even after adding arr files, and using correct procedure from official documentation, i am not able to compile these dependencies.

**Comment by hiranandanisonal** [comment]
@erikghonyan 
I was able to compile auth dependency, as you said it was available on jcenter. Can you please provide such info about player dependency. Thanks

**Comment by hiranandanisonal** [comment]
@Sultani00 Can you link .aar files, I cannot find them. Also gradle is not able to locate those files in lib folder.

**Comment by bmachlin** [comment]
Found a solution to this here:
https://stackoverflow.com/questions/44226685/spotify-android-sdk-android-auth-1-0-how-to-build

basically throw the player aar file in app/libs and use these two lines in build.gradle:

compile 'com.spotify.android:auth:1.0.0-alpha'
compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'
