### ISSUE TITLE
Android "package name" / iOS "Bundle ID"

### ISSUE THREAD

**Issue by Anders27** [spotify/android-sdk#178]
I have two versions of my app, one for iOS and one for Android, both has the same name.

The iOS version of the app has the “bundle id”: 
com.mycompany.abc
The Android version has the package name:
com.mycompany.abc

meaning they are identical.

I’ve already added support for Spotify in the iOS version and have the app registered at “My Applications” in the Spotify develop portal.
Works fine.

I’ve registered the Android version with 
com.mycompany.abc
as the “Android Package Name” and added the correct “SHA1 Fingerprint”.

Whatever I do, login fails with:
[main@sso.AuthorizationActivity:372] INVALID_APP_ID
(the Client ID is correct)

I’ve tried to add the “Android Package Name” and “Fingerprint” in the Android section of my iOS app, same error.

But if I create a completely new Android test app with its package name and fingerprint, that works.
My regular Android app also works with the client ID for the test app!

Is there a problem having identical iOS “bundle id” and android package name?
I can’t change this since both apps are on sale since long.

Any advice?

**Comment by kaaes** [comment]
@Anders27 that should not be a problem. Can you verify that your package name and fingerprint are registered correctly (you need to click 'Save' button at the bottom after adding them)

**Comment by mpusinhol** [comment]
I have the exact same problem here. I get INVALID_APP_ID when I try to loggin. I have the debug fingerprint and package name saved in MyApplications. However, this problem happens only when using my cellphone (which has Spotify on it) to test my app; when using and android emulator (which does not have Spotify) it works fine. Any ideas about how to solve this? Thanks in advance
