### ISSUE TITLE
Issues with the login webview on some devices

### ISSUE THREAD

**Issue by vbessuges-wbd** [spotify/android-sdk#179]
Hello,

I'm having issues on some devices with the login webview dialog.
Instead of having the usual login dialog with the two green buttons ("I have a spotify account" / "I don't have a spotify account"), I got a dialog stating that "something went wrong".
![screenshot_2016-01-12-14-12-54](https://cloud.githubusercontent.com/assets/16666854/12264527/b8fa8ff8-b937-11e5-98d0-59097a669736.png)

I tried to debug to get the Uri and I opened it on Google Chrome, it worked.
![capture](https://cloud.githubusercontent.com/assets/16666854/12264543/cc6e1906-b937-11e5-97dd-2ae5b4078aef.JPG)

The specs of the device causing issues: Samsung Galaxy S3 running Android 4.3.
If I recall correctly I also had the same issue on an HTC One S running Android 4.0.1.
On other devices it works fine :)

Thank you for your help.

**Comment by kaaes** [comment]
It might have been a temporary problem with the Accounts Service. Is this something that happens regularly on these phones?

**Comment by vbessuges-wbd** [comment]
Hello, thank you for your answer. On those phones it happens 100% of the time.

**Comment by kaaes** [comment]
@vbessuges-wbd there was an issue with the Accounts service that could cause some requests to fail. This should be fixed now. Could you check if this still happens?

**Comment by vbessuges-wbd** [comment]
@kaaes thank you for you reply. Should we do something on our side? I tried the connection process on the Samsung last Friday and again today, I still have the same screen.

**Comment by d-kunin** [comment]
Should be fixed, please reopen if it is relevant.
