### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by mchiarello** [spotify/android-sdk#181]
Hey! 
First of all, I love your app!! But unfortunately one thing is missing to get the maximum experience of the premium account. 
So my userstory is: As a user I would like to be able to search my playlists via search field to be able to listen to a specific song instead of scrolling through all the titles of the playlist. This increases usability and customer satisfaction. 

Thanks! 
Greetings from a German Webdeveloper :)

**Comment by kaaes** [comment]
@mchiarello thanks for reaching out to us. This project however is dedicated to the Spotify SDK for Android and used to track feature requests and bugs for the library. If you'd like to share your idea about Spotify app, please use [Community Portal](https://community.spotify.com).
