### ISSUE TITLE
[Native crash] Track caching causes crashes after extended playback

### ISSUE THREAD

**Issue by louiswilliams** [spotify/android-sdk#183]
This is a follow-up to #148, which discusses a problem where after 60min+ playback, the application will crash, and disabling track caching solves the problem. This is a bug because caching tracks should not cause the application to crash.

First reported by @dcamp200 and confirmed by @bsatorius

**Comment by Anders27** [comment]
I changed to using beta 11 to get around the file cache problems.
As far as I can tell, for devices using Wi-Fi this solves the problem and it's possible set playerConfig.useCache(true).
BUT if the device is only using LTE, the app still crashes with the "Too many open files" error. It doesn't happen after one hour but after say 10-15 hours. So this bug exists in Beta 11 as well.

**Comment by d-kunin** [comment]
Please re-check with the latest release https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13 
Have a nice day!

**Comment by dcamp200** [comment]
Everything appears to working fine Dmitry.  I kept a session open for 24hrs
without any issues.
Thanks very much!

**Comment by d-kunin** [comment]
Good news! Really glad to hear this :)
