### ISSUE TITLE
INVALID_APP_ID

### ISSUE THREAD

**Issue by Brockify** [spotify/android-sdk#184]
I currently an error: INVALID_APP_ID. I only get this error if the user is currently logged into their spotify account through the spotify app, it will not be able to authenticate the user in my app.

**Comment by Anders27** [comment]
Same problem here. I have four devices to test with. I get INVALID_APP_ID error on the two devices that have the Spotify app installed, on the other two devices that does NOT have the Spotify app installed authentication works fine.

If I use another "CLIENT_ID" for another test app with another fingerprint and another package name, then authentication with my regular app (that has another fingerprint and another package name) works OK on all four devices!
Would this also work for regular users when I release the app?

Could anyone explain if the fingerprint and package name really matters?
Or is it only the "CLIENT_ID" that is important?

**Comment by Brockify** [comment]
@anders27 what do you mean another client ID

**Comment by Anders27** [comment]
With “another client ID”, I mean a client ID for a test app I created for initial testing.
This client ID works for my main app where I’m now adding support for Spotify.

My main app has another "Android Package Name" than my test app.
And using the client ID from my test app with my main app makes authentication work on all four devices, regardless if it has the Spotify player app installed or not. 

But when using the "real" client ID I created for my main app, authentication only works for the two devices that does NOT have the Spotify app installed.

Could anyone from the Spotify developer team explain what's going on?

**Comment by kaaes** [comment]
@Brockify did you register your package name and fingerprint in the [Dev Portal](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/#registering-application-fingerprints)?

**Comment by Anders27** [comment]
Thanks for replying!

Yes I have registered both the package name and fingerprint and double checked that they are correct.

I have four different Android devices to test with.

What's strange is that it works fine on two devices where the Spotify player app is NOT installed but when testing with two other devices which have the Spotify player app installed, login fails with "INVALID_APP_ID" error.

Even more strange is that if I add a second fingerprint for my app in the "Dev Portal", which comes from a test app where I made my first tests, then it works on all devices! This fingerprint has nothing to do with my regular app. This makes it work on all four devices but what will happen when I release the app? Will that work for regular users? Hm...

**Comment by Anders27** [comment]
Problem solved:

I didn't realise that my app during development is signed with the debug key and not the release key.
That's why adding the debug key fingerprint made it work.

so you can close probably close this issue as well as:
https://github.com/spotify/android-sdk/issues/178

Sorry for the noice.
