### ISSUE TITLE
Crash "IMemory﹕ cannot dup fd=18, size=4194304, err=0 (Too many open files)"

### ISSUE THREAD

**Issue by mrmaffen** [spotify/android-sdk#186]
The library crashed when I tried to play a track after returning to my device after a few hours of it being inactive.

Here's the log: [log.txt](https://github.com/spotify/android-sdk/files/110070/log.txt)

And here's the tombstone: [tombstone_02.txt](https://github.com/spotify/android-sdk/files/104439/tombstone_02.txt)

**Comment by Anders27** [comment]
I have the same problem when I try to play a track after returning to my device after a few hours of it being inactive.
I only have one file open using "player.play(uri)" but before the crash the log displays the same error:
art  ashmem_create_region failed for 'indirect ref table': Too many open files.

![spotifycrash](https://cloud.githubusercontent.com/assets/10338608/12617415/e0323876-c50f-11e5-84f0-862c49d6a2c9.png)

I've never seen this problem before I started to add support for Spotify but can of course not be 100% sure that it's related to the Spotify lib.

**Comment by Anders27** [comment]
This must be a bug in the Spotify SDK, I'm using the current beta 12.
Disabling the file cache by using
playerConfig.useCache(false);
makes everything work perfect.

**Comment by mrmaffen** [comment]
I have downgraded to beta 11. Everything's working fine again. Pretty sure this crash has been introduced with beta 12.

**Comment by stefannilsson** [comment]
We're also experiencing a crash due to "too many files" when keeping the app running for some time.

**Comment by kaaes** [comment]
I'll close this issue as it's a duplicate of #183 Let's track it there
