### ISSUE TITLE
player.seekToPosition() fails if called when playback position is close to EOF

### ISSUE THREAD

**Issue by Anders27** [spotify/android-sdk#187]
I use my own AudioController class and JNI playback logic and I have player.setRepeat(true); 

If calling player.seekToPosition() when playback position is closer than about 3-4 seconds of the song length (playerState.durationInMs), seeking fails and some internal Spotify exception is displayed in the log console:
"Throwing exception, failed SpPlaybackSeek with error code 1".

After that a lot of "TRACK_START" and "TRACK_END" events are sent out and playback eventually start over from time 0.
This makes looping of audio very difficult.

At every other playback position seeking works fine.

I've already implemented the same playback logic in the iOS version of my app and there it works perfect to seek anywhere at any playback position.
And since (from what I read elsewhere here) that the underlying JNI C/C++ library is the same for both Android and iOS, one would expect (hope for) the same behavior.

To me it seems as (just a speculation) before the audio is sent to onAudioDataDelivered(), it's buffered, and some internal flag is set when the file in the file cache reaches EOF and NOT when the last audio sample has been sent out and returned as "consumed / written".

In my opinion, until onAudioDataDelivered() has delivered every sample, the song has NOT reached EOF and seeking should of course work.

**Comment by d-kunin** [comment]
Should not be a problem for beta22.
