### ISSUE TITLE
Set size limit for disk cache

### ISSUE THREAD

**Issue by acommoner** [spotify/android-sdk#188]
Is it possible to do this at the moment? I looked through the APIs and didn't see anything right away. If not, could you possibly add an option to adjust it?

I see that I can turn off the disk cache altogether, but it would also be nice to be able to set the max cache size to be smaller than 1GB, since this is a lot of space on smaller devices.

**Comment by d-kunin** [comment]
You can use `Config.cacheSizeLimitInMegabytes`.
