### ISSUE TITLE
 When to call Player#shutdown() and shutdownNow() ?

### ISSUE THREAD

**Issue by mrmaffen** [spotify/android-sdk#190]
Hi there,

there's almost no information on those two methods in the documentation. The example code only uses Spotify.destroyPlayer(this) to clean up and release native resources. When would one want to call shutdown() or shutdownNow() instead? I noticed that I'm unable to revive a Player object once I have called shutdown(). So I'm not sure what those methods are doing.

And just a friendly poke: Open-source it! I'd love to work on fixing/analyzing a few crashes/bugs myself, but I can't :(

**Comment by d-kunin** [comment]
Hi @mrmaffen! You never need  to call any of them, the one was removed and another one is about to follow. `destroyPlayer` is the right way!
