### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by grenkaDmytrenko** [spotify/android-sdk#192]
Can I somehow get the refreshToken using your sdk ?
Or, at this point I can only get accessToken ?

**Comment by kaaes** [comment]
@grenkaDmytrenko you can get [access tokens](https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flow) or [authorization codes](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow) from the SDK library. If you'd like to get a refresh token you should get the auth code and swap it for a refresh token in a backend service
