### ISSUE TITLE
Request: Please don't remove TRACK_START and TRACK_END events.

### ISSUE THREAD

**Issue by Anders27** [spotify/android-sdk#193]
I know that TRACK_START and TRACK_END are deprecated since beta 10 and has been replaced with TRACK_CHANGED but there are situations when they are in fact needed.

My app only loads one song at the time using player.play(uri); and always uses player.setRepeat(true);
This is so that a user can repeat the complete song or a certain part of the song (for practicing purposes).

I have tried to avoid using TRACK_START and TRACK_END but because of this problem:
https://github.com/spotify/android-sdk/issues/187
the only way to have a reliable seeking close to EOF, is to monitor the TRACK_END event. 

So please keep TRACK_START/TRACK_END and TRACK_CHANGED since they are all useful for different purposes.

**Comment by chrishale** [comment]
+1

I'd also like this to be kept if possible. Same goes for the iOS SDK also

**Comment by kaaes** [comment]
Thanks for the feedback. We'll look into these issues and see what would be the best way of going forward with these events.

**Comment by mrmaffen** [comment]
+1 keep it please

**Comment by pschroen** [comment]
+1

**Comment by ZinoKader** [comment]
+1 For me, there are no reliable workarounds using TRACK_CHANGED. I need TRACK_END!

**Comment by d-kunin** [comment]
They were removed 😈 
But we have `kSpPlaybackNotifyTrackDelivered` and `kSpPlaybackNotifyTrackChanged` instead and they are not going anywhere :)

**Comment by ryandt** [comment]
Having a `PlayerEvent` for when playback completes on a given song without intervention would be great if this doesn't already exist. I'm specifically looking to differentiate this event from the events received when the player skips to the next song via a call to `player.skipToNext()`.
