### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by simonhopkin** [spotify/android-sdk#194]
I have implemented the beginners tutorial to the letter and I'm not able to authenticate.  When I attempt to authenticate I momentarily see a loader appear but that then vanishes and I see the following in logcat:

```
I/MAIN ACTIVITY: onPause
D/PhoneWindow: *FMB* installDecor mIsFloating : false
D/PhoneWindow: *FMB* installDecor flags : 8454400
D/SpotifyAuthHandler: start
I/Timeline: Timeline: Activity_launch_request id:com.spotify.music time:367303491
D/Activity: performCreate Call Injection manager
I/InjectionManager: dispatchOnViewCreated > Target : com.spotify.sdk.android.authentication.LoginActivity isFragment :false
D/SecWifiDisplayUtil: Metadata value : SecSettings2
D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
D/PhoneWindow: *FMB* isFloatingMenuEnabled return false
D/SRIB_DCS: log_dcs ThreadedRenderer::initialize entered! 
D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@23c48cfe time:367303629
V/ActivityThread: updateVisibility : ActivityRecord{a86d303 token=android.os.BinderProxy@cda3ea9 {com.ms.ts/com.ms.ts.activity.MainActivity}} show : true
V/ActivityThread: updateVisibility : ActivityRecord{208c5f75 token=android.os.BinderProxy@23c48cfe {com.ms.ts/com.spotify.sdk.android.authentication.LoginActivity}} show : true
D/com.spotify.sdk.android.authentication.LoginActivity: Error authenticating
D/SpotifyAuthHandler: stop
I/Ads: Scheduling ad refresh 60000 milliseconds from now.
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@cda3ea9 time:367303805
D/SpotifyAuthHandler: stop
```

I have added all the details in the spotify developer console for the app.  I see reference to Error authenticating in the logs but I have no idea why.

Any ideas whats going wrong here?

**Comment by simonhopkin** [comment]
Ok I have found what is going wrong.  I opened the Spotify app and noticed that I had set it to offline.  When I turned this off in the Spotify app, my app authentication started working.

Is it possible that the Spotify authentication api can catch this so that I can handle it in my app by putting up a dialog or something prompting the user to ensure they are not offline?

**Comment by kaaes** [comment]
@simonhopkin yes, starting from the next (4.6) version of Spotify (no need to update the auth library) when user is offline the error in the `AuthenticationResponse` will be more descriptive - OFFLINE_MODE_ACTIVE in this case
