### ISSUE TITLE
Observing the playback position?

### ISSUE THREAD

**Issue by chrishale** [spotify/android-sdk#195]
Is it possible to observe the playback position of the player in such a way that it fires an event or method with the new value upon change?

I'm wanting to update a progress bar in the UI, and I'm not sure how to get the value.

In the ios-sdk, this is achieved with KVO - so ideally I'm looking for something similar.

Thanks.

**Comment by sampurcell93** [comment]
Hey Chris, any progress on this since you posted the question?

**Comment by chrishale** [comment]
Unfortunately not, I've put a pause on my Android version for the time being. If anyone from Spotify could suggest even a workaround, I'd be very greatful

**Comment by sampurcell93** [comment]
Hey Chris, I have found a solution that I'm using for the android.MediaPlayer that I suspect will work for the Spotify player as well. It requires being extra mindful of the player's state, but using the technique found [here](http://android-er.blogspot.com/2012/06/display-playing-time-for-mediaplayer.html) you can set a function to dispatch your scrubbing update function. I cancel my ScheduledFuture on pause, and when the song is completed / the player is released, and I recreate it when the song is resumed / played. Hopefully this helps you!

**Comment by chrishale** [comment]
Thanks Sam, I'll take a look 👍

**Comment by ryandt** [comment]
Being able to get the song's duration and position from the Player _synchronously_ would be ideal.

**Comment by d-kunin** [comment]
We will not provide notifications, but you can pool for the position _synchronously_ since beta 23

**Comment by ryandt** [comment]
Thanks for adding this!
