### ISSUE TITLE
No playback status changes broadcast intent is sent when app is killed

### ISSUE THREAD

**Issue by kmitrovic** [spotify/android-sdk#198]
1. Start Spotify app, and start playback (related broadcast intents are sent out- so the playback state I know now is *playing*),
2. Kill Spotify app (swipe it out from Android's Recents screen)

I got no new Spotify intents at this point (even though the music is clearly stopped, and I still have *playing* as my internal state).

Expected: clean shutdown with sent out Broadcast intent for playback state change (to stopped/paused)

**Comment by d-kunin** [comment]
@kmitrovic thanks for the report, but it is not a part of the Android SDK, but Spotify App that sends the broadcasts. You can report this issue at a dedicated forum https://community.spotify.com/t5/Android/bd-p/spotifyandroid
