### ISSUE TITLE
Offline Playback

### ISSUE THREAD

**Issue by siegenthalerroger** [spotify/android-sdk#2]
Please make the ability for offline playback a top priority as everything else can be provided by the webAPI currently. Offline playback is curently the only reason to keep using the libspotify sdk which is deprecated.

**Comment by sockeqwe** [comment]
Any updates? will offline playback be part of final 1.0.0 release?

**Comment by kaaes** [comment]
We are looking into this feature and we are planning to add it but most likely it will not be a part of 1.0.0

**Comment by Wolftein** [comment]
The old libSpotify cached both played tracks and offline tracks as equal, would you concider to allow specified both cache and offline folder separately?

**Comment by nikreiman** [comment]
The offline feature relies on the cache directory, which was true for libspotify and also the new SDK. So it is probably not likely that we will have a feature which would purge "all but offline" from the cache, though it's something that we will consider when designing the offline API.

**Comment by siegenthalerroger** [comment]
When you add this could you also add a way to initialise the sdk in offline-mode (no attempt to connect to internet made from the get-go)? This would allow much faster start up times for time-critical applications.

**Comment by kolletzki** [comment]
:+1:

**Comment by sjimmie** [comment]
@nikreiman any update on getting this in the new SDK already? :)

**Comment by nikreiman** [comment]
@sjimmie I'm not on the team which does external SDK stuff, so I will instead ping @kaaes. Though last I heard, offline is still in the works but the devil is in the [implementation] details. ;)

**Comment by sjimmie** [comment]
@kaaes PING :)

**Comment by kaaes** [comment]
I agree that offline playback would be a cool addition to the SDK and it is something that we would like to add but it is not planned for the 1.0.0 release.

**Comment by truthz03** [comment]
I know that the SDK does not implement offline playback now. Is there already a date where this feature could be added?
Are I'm allowed to cache songs with my app to get offline access while the SDK doesn't support this feature?

**Comment by frunns** [comment]
What's missing for this issue to be closed? Is it planned? Are there any business obstacles to get it done?

Being able to cache for a mobile Spotify app is fairly critical, I probably can't release my project without it.

**Comment by truthz03** [comment]
I found out that there are some "spotify-track-....sp" files on my internal storage inside the files folder of my app. Because there is no possibility to play offline files yet I think these files are useless.
Can I disable the storage of these files? I don't have enough space to cache useless files on my phone

**Comment by truthz03** [comment]
If it's now possible to play offline files it will be very usefull if I can define the location of this files.

**Comment by siegenthalerroger** [comment]
So here we are, one and a half years(!) after this all started and no update on when this sdk will be finished, let alone any update on when we can expect offline capabilities and worst of all, no source code released (your lawyers really can't be this slow can they). What's up?

**Comment by FabioAntunes** [comment]
@siegenthalerroger They said this, a year ago:
> We are looking into this feature and we are planning to add it but most likely it will not be a part of 1.0.0

Version 1 it's still in beta so doing some calcs by the year of 2018 we might see that feature into version 2.0.

**Comment by anuragcm** [comment]
Hello,
I am android application developer. I am looking for offline playback from Spotify android SDK to integrate with my music application.
Do you know when this feature will be available?
Thanks in advance.

**Comment by pete-harris** [comment]
+1
I would also like this feature to be available.
The ability to play from the device's "downloaded" music is a primary requirement of an app idea I am developing.

**Comment by kabouzeid** [comment]
Without the offline feature this API is almost useless.

**Comment by siegenthalerroger** [comment]
Well at least the android community can be happy they haven't released this for iOS either; https://github.com/spotify/ios-sdk/issues/7

**Comment by Ruud-cb** [comment]
+1

**Comment by d-kunin** [comment]
The offline feature is more of a legal than technical problem and we don't see when it could be solved at the moment. We have to keep streaming :)

**Comment by ShyykoSerhiy** [comment]
I've imagined that the legal stuff took you guys so long to ~~implement~~ not implement this in sdk. That's a bummer as it seems you had no issues with this in libspotify.

**Comment by siegenthalerroger** [comment]
So even though you had this feature in your old library (libspotify) and anyone willing to break your ToS already can rip your entire library into an offline & unprotected format, coupled with the fact that your competition allows this; you're deciding to blame "legal issues". 

What a sad excuse, you know full well and right that this would be very useful for developers and using the exact same encrypted storage system that you already employ with your native application there should be no issues.

**Comment by kabouzeid** [comment]
Even worse, the official Android app is so poorly written, it doesn't make fun at all to use it.

**Comment by lorenzhs** [comment]
@d-kunin would you mind locking this issue? The comments are starting to derail.

**Comment by Ruud-cb** [comment]
Wierd, I don't see the legal issue here. Is the stream coming directly from the servers instead of the app? Maybe that is the problem if that is the case. The music should be streamed via the spotify app if it is installed, then the SDK gets the music from the spotify app and the spotify app will control if the user should be allowed to play the music or not, either online or offline usage.
FYI: I don't use the SDK yet, some apps I do are and I wish this would be possible. For example an Alarm app, depending on internet connection would be very uncertain to wake up for :).

I think this is just a major request/change and not a small 'issue'.
@siegenthalerroger could you elaborate?

**Comment by siegenthalerroger** [comment]
@Ruud-cb That is the exact reason we would like this offline feature. We have an app that requires 
a) fast startup times (much more realistic if we could start in offline mode)
b) guaranteed play regardless of connectivity (which almost always is unavailable when our app is called - I'll let you speculate as to what that could be ;) )

@d-kunin do you think you could maybe tell us if having users complain/petition for this feature would help? Or would it be possible for a small group to have a direct deal with Spotify for this feature?

**Comment by escamoteur** [comment]
Also for my App which deals with Audiobooks it would be really important as people like to listen to Audion books while travelling.
I really don't understand why Spotify does not care more about third party Apps that bring paid subscriptions for them.

**Comment by godofcpu** [comment]
Is this available yet for android?  I offline playback is now in the iOS sdk why no android love?
