### ISSUE TITLE
Directory for file cache

### ISSUE THREAD

**Issue by Anders27** [spotify/android-sdk#200]
It seems the file cache is stored in the app data folder and not in the app cache folder. 
If things works the same on Android as on iOS, the system will clear the cache folder when it needs more memory but not the data folder. And manually clearing the app data folder in the Android App settings view, will delete all data including preferences etc so that's not any good option.

**Comment by d-kunin** [comment]
It seems like we will not be able to prioritize this issue any time soon.

**Comment by siegenthalerroger** [comment]
https://github.com/spotify/android-sdk/issues/128#issuecomment-255370970

Just saying this here as well.
