### ISSUE TITLE
Caching Difference with Spotify App

### ISSUE THREAD

**Issue by krysanify** [spotify/android-sdk#201]
Hi, are there any differences between how this SDK handles caching with the official Spotify app?
I noticed that when I play a song on Spotify app, then abruptly disconnect my WiFi router from Internet, the song keeps on playing (fully cached).
However, when I do the same using Player SDK, the song would end after a few seconds (not fully cached).
This results in higher battery consumption due to constant data stream on SDK rather than the few seconds it took for official app to download the song first into cache.
I confirmed the caching are different by looking at the size of both apps stored data, official Spotify app used ~9MB after disconnection and my test app used ~2MB after disconnection.
The sample song is Hotel California by Eagles, duration 6:31.
Disconnecting WiFi router is done ~5 secs after touching song title to play, enough time to download the entire song on broadband.
Player connectivity is set to Wireless, playback bitrate is set to Normal.

**Comment by dcamp200** [comment]
Any updates on this issue?  I've tried various things but no luck.
The api says to use this
 musicPlayer.setConnectivityStatus(Connectivity.fromNetworkType(networkType)); 
when the network switches.  I tried it, but it did not help.

**Comment by krysanify** [comment]
Not that I'm aware of. Have you try to use ExoPlayer as mentioned  by @ssaxena0891 in #182 ?
I haven't try it myself 'cause I'm done evaluating Spotify and now pursuing other services.

**Comment by d-kunin** [comment]
The cache implementation is different in the SDK and in the app. The does something called prefetching, while the SDK just caches what needs. Both approaches have proc and cons, but for now it is the way it is. We might introduce prefetching in the SDK later, but no promises or date at this point.
