### ISSUE TITLE
Calling LoginActivity from another Intent

### ISSUE THREAD

**Issue by deeuler** [spotify/android-sdk#202]
I need a little help working with the SDK. I am trying to follow the [SDK tutorial](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/) but not use this activity as a main activity. As such, I am trying to perform the whole login activity from the onCreate() of another class, called as a new Intent object from my main activity. I, basically, want to select a button then be directed to the Spotify loginActivity. Unfortunately, I believe this is not working correctly (i.e. the app crashes) because during onCreate(), class "com.spotify.sdk.android.authentication.LoginActivity" is trying to be found in my local package (like "com.example.appName"). Debug log points to AuthenticationClient.openLoginActivity(), to be specific. The error stated reads

 "android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.appName/com.spotify.sdk.android.authentication.LoginActivity}; have you declared this activity in your AndroidManifest.xml?". 

How can I go about remedying this? I'm pretty green on app development and authentication, so please bear with me :)
I will attach some relevant text samples
My MainActivity class:
```
public class MainActivity extends AppCompatActivity{
    onCreate(Bundle SavedInstanceState){
    //yada yada...
    }

    //where the intent change occurs
    public void onSpotifyClick(View view){
        Intent intent = new Intent(PlayerActivity.this,SpotifyLogin.class);
        startActivity(intent);
        this.finish();
    }
}
```

My SpotifyLogin class:
```
public class SpotifyLogin extends Activity implements PlayerNotificationCallback,
    ConnectionStateCallback{

    //some required variables...

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_spotify_login);

        AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID,
                AuthenticationResponse.Type.TOKEN,
                REDIRECT_URI);
        builder.setScopes(new String[]{"user-read-private", "streaming"});
        AuthenticationRequest request = builder.build();

       //where onCreate() breaks down
        AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);
    }
}
```

From my AndroidMainfest file:
```
...
<activity android:name=".SpotifyLogin">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <category android:name="com.spotify.sdk.android.authentication.LoginActivity" />
                <data android:scheme="SpotifyLogin" android:host="callback"/>
            </intent-filter>
            <activity
                android:name="com.spotify.sdk.android.authentication.LoginActivity"
                android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
        </activity>
...
```

I really hope the error I am making is obvious for you. Thanks in advance!

**Comment by Fanta1090** [comment]
It seems that you have declared the spotify LoginActivity inside another activity tag (SpotifyLogin).

Your manifest should be something like this :

```
<activity android:name=".SpotifyLogin">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <category android:name="com.spotify.sdk.android.authentication.LoginActivity" />
                <data android:scheme="SpotifyLogin" android:host="callback"/>
            </intent-filter>
</activity>

<activity android:name="com.spotify.sdk.android.authentication.LoginActivity"
              android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
```

**Comment by deeuler** [comment]
Sure enough!

**Comment by Nagavikas96** [comment]
Hai Deeuler, do you completed spotify api android studio project, can you share me the code. I am also working on same, I got stuck in redirect url, can you help me on this.
