### ISSUE TITLE
Not able to get particular user playlist track  in android

### ISSUE THREAD

**Issue by dyraval** [spotify/android-sdk#203]
I have some user and playlist with their id & want to getting tracklist from that  like **"api.spotify.com/v1/users{user_id}/playlists/{playlist_id}/tracks"** but getting error 401: authentication error. So how to solve these ?? @spotifyteam please suggest me!!

I am using **Spotify Android SDK 1.0.0-beta12 **

**Comment by jhmacdon** [comment]
First off, this is the web api not the android sdk.

Also, assuming this is just a typo but it should be "https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks" (you're missing the "/" above.

**Comment by erdtman** [comment]
I´m closing this since it is as mentioned by @jhmacdon a web-api issue. If it is still an issue please report it in the web-api issue tracker (https://github.com/spotify/web-api).
