### ISSUE TITLE
Re-connecting after network change

### ISSUE THREAD

**Issue by dcamp200** [spotify/android-sdk#204]
When I am playing a song over wifi and then switch to a mobile (3G) network, I do not see any errors or messages.  From the documentation, 
https://developer.spotify.com/android-sdk-docs/player/
I was expecting to see a callback onTemporaryError.  The music will continue to play for approximately 2 minutes and then stop.
To recreate: Start playing a song (over wifi) and then turn wifi off to allow switching to the mobile network.
The Spotify app seems to handle the switchover without issue.

What is the best way to handle reconnecting? i.e. should I shutdown the player and re initialize it?

Thanks.

**Comment by krysanify** [comment]
On the Spotify app, how long did you wait before turning off the WiFi? I think the difference is due to that the song was cached faster on Spotify app compared with Spotify SDK, and not because they handle switchover. See also #201.

**Comment by dcamp200** [comment]
Thanks Krysanify.  Sounds like you are having the same issue.  With the SDK I can play about 1:50 before it abruptly stops.  With the Spotify app, I let it play into the second song but saw no issues.
I have caching turned off due to issue #148 

It appears to be a bug.  I don't seem any callbacks being invoked.  I would think the SDK could recover from a network change.  The callback at least gives you a chance to warn the user that you are switching to the mobile network.

Exiting my app and restarting fixes the problem but is inconvenient for the user.  I also tried creating a new player when the event happens (catching it using CommunicationsManager) but this did not work.

**Comment by dcamp200** [comment]
Solved this issue.  There is some sample code in the demo activity that shows how to handle network change over. The key is calling
 mPlayer.setConnectivityStatus(connectivity);
on the player.
