### ISSUE TITLE
How to play full-length songs on Android using Spotify SDK?

### ISSUE THREAD

**Issue by burakulu** [spotify/android-sdk#206]
I read everywhere that it is possible to offer the users of our applications full-length songs via using Spotify SDK for Android. But only way I could find is that users should have premium account on Spotify to get full-length tracks. Otherwise, it is not possible to get full-length even if you were non-premium user of Spotify.

Am I wrong or right? Is there a way to get full-length tracks without being a premium user on Spotify?

**Comment by shirleymiao** [comment]
No, I'm pretty sure you can only get full length tracks as a premium user. 

https://developer.spotify.com/technologies/spotify-android-sdk/ 
"Please also note that streaming of full-length tracks is only available to your users who have a Spotify Premium subscription."

**Comment by erdtman** [comment]
You are right you can only play full length songs if the user has a premium account.
