### ISSUE TITLE
Getting wrong PCM data after spotify song resume function call

### ISSUE THREAD

**Issue by dawanoop** [spotify/android-sdk#207]
Hello,
I am using own custom  AudioController to play spotify song using pcm data successfully. For this i have used spotify player. When i paused the song song pause successfully. If i resume the pause song     there is no playback. i have print the pcm data in onAudioController function. I am getting wrong pcm data when i call resume function of spotify player. I have used code given as developer website.

How i can get correct PCM data after resume function call.

please help me to solve this issue.

**Comment by d-kunin** [comment]
@dawanoop is still an issue in beta 21? Please reopen if it is and provide more context.
