### ISSUE TITLE
Enhancement request - Volume on Player

### ISSUE THREAD

**Issue by happyruss** [spotify/android-sdk#208]
Can you please expose a method in the Player class so we can adjust the volume of the AudioTrack that is playing inside of the AudioTrackController so that we can modify the volume of the AudioTrack or even mute it, irrespective of the master system volume? This should be pretty easy for you to implement, but I can't override since the Player is marked as Final. Thanks. Alternatively, exposing the AudioTrack would allow me to not only manipulate the volume, but also use a Visualizer class to do fun stuff like create visualizations based on what's being played.

**Comment by krysanify** [comment]
you can use custom audiocontroller, look at "custom audio handling" part: https://developer.spotify.com/android-sdk-docs/player/com/spotify/sdk/android/player/Player.html

**Comment by erdtman** [comment]
@happyruss have you tried the suggestion from @krysanify?

Thanks @krysanify for suggesting a solution

**Comment by NathanWalker** [comment]
Any progress here? Curious on the custom audiocontroller, but not sure how to do this properly, is there an example which would adjust the volume of just the streaming music player?

**Comment by d-kunin** [comment]
It seems like we will not be able to prioritize this issue any time soon.

**Comment by siegenthalerroger** [comment]
https://github.com/spotify/android-sdk/issues/128#issuecomment-255370970

And here too

**Comment by PankajSavaliyaGit** [comment]
any update for this enhancement?
