### ISSUE TITLE
Bug with right scroll in playlist  on mobile

### ISSUE THREAD

**Issue by marty89** [spotify/android-sdk#209]
Hi,
I'm a user of spotify premium and also professional developper in Brussels . i just want note you thathave encountered one small issue with the right scroll bar when navigate in playlists

My mobile is a sony Z5 
Android version 5.1.1
app version : 4.8.0.1004

i record my screen, see link below
https://drive.google.com/file/d/0B1IiBrpspQBQRW9zUEJaSkZxdTA/view?usp=sharing

i hope it's useful for you, IT solidarity ;-)

**Comment by d-kunin** [comment]
Thank you @marty89, unfortunately this is not the forum to report Spotify App issues. It makes more sense to use community forums instead: https://community.spotify.com/t5/Android/bd-p/spotifyandroid
