### ISSUE TITLE
REQUEST : Please Add Feature in Settings to Set active OTG external DAC 

### ISSUE THREAD

**Issue by elfaandhika** [spotify/android-sdk#211]
i hope Sportify Player for Android can have a Feature to Choose Media Ouput to USB OTG for use Dac external like app Onkyo Player Music .
Thanks

**Comment by Meisolsson** [comment]
You should be able to do this with the AudioController? https://developer.spotify.com/android-sdk-docs/player/com/spotify/sdk/android/player/AudioController.html

**Comment by erdtman** [comment]
@elfaandhika did the suggestion from @Meisolsson work?

Thanks @Meisolsson for suggesting a solution

**Comment by d-kunin** [comment]
Since no reaction followed, I am closing the issue.
