### ISSUE TITLE
Code expiry time

### ISSUE THREAD

**Issue by mradzinski** [spotify/android-sdk#212]
If I request a code instead of a token, does this code has an expiration time or can it be re-used to request future tokens without the user having to go through all the auth flow again? The parameter expiresIn returns always 0 when I request a code, thus my question.

**Comment by Meisolsson** [comment]
If you look at the doc for it [here](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow). Code is only used for Authorization Code Flow which lets you refresh the token once.

**Comment by mradzinski** [comment]
@Meisolsson, I do understand that, but my question is about the expiry time of the code itself. Lets suppose an user approves the access to my application, receives the code but all of a sudden his phone battery dies and my app fails to refresh the token using that code, however, the code manages to be persisted by my app somewhere. The user manages to charge his phone back, turns it on two hours later and opens up my app to continue with the registration process. Is the code still valid after two hours or the user has to go through the auth flow again? Can I use that code that was saved two hours before to ask for a refresh token?

**Comment by Meisolsson** [comment]
No clue about the expiry time but since the docs don't say a time I'd guess it's "infinite". The best way to know is to test it I guess, at least before Spotify gives a response.

**Comment by erdtman** [comment]
The code-grant code is currently valid for 10 minutes, after that a new one has to be requested.
