### ISSUE TITLE
Can't play following uri on Android player: spotify:artist:4gzpq5DPGxSnKTe4SA8HAU

### ISSUE THREAD

**Issue by mabounassif** [spotify/android-sdk#213]
**Spotify android player:** 1.0.0-beta12.

It seems that I'm getting issues with artists URIs. Does the player support URI's such as `spotify:artist:4gzpq5DPGxSnKTe4SA8HAU` ? I'm not getting any playback events.

I'm not having any problems with Track URIs such as: `spotify:tracks:<track_id>`

**Comment by mabounassif** [comment]
No love? :(

**Comment by Meisolsson** [comment]
It only plays tracks and playlists. https://developer.spotify.com/android-sdk-docs/player/com/spotify/sdk/android/player/Player.html#play-java.lang.String-
