### ISSUE TITLE
Spotify Player : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdb40c386 in tid 26688 (SpotifySdkPlaye)

### ISSUE THREAD

**Issue by middebugger** [spotify/android-sdk#214]
The crash is happen random.I have implemented the spotify sdk as per the instruction given by the tutorial.It will happen when i skip the songs through several songs.Then the app crash and restarts the current activity.The same methods i used in Media Player.It is working fine without any error.Could you please help me to solve the issue.

`04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###

04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: Chrome build fingerprint:

04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: 2.4.1

04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: 102

04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: 3033544c-2413-4357-8daf-30f417786034

04-07 10:43:42.336 25033-26688/com.x3.sample W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###

04-07 10:43:42.336 25033-26688/com.x3.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdb40c386 in tid 26688 (SpotifySdkPlaye)

04-07 10:43:47.681 25033-26769/com.x3.sample W/AudioTrack: releaseBuffer() track 0x859bca80 disabled due to previous underrun, restarting
`

**Comment by middebugger** [comment]
@kaaes : Could you please help me to solve the issue ?

**Comment by ssuukk** [comment]
Two more raports, happens on HTC

04-06 12:03:23.498 F/DEBUG   (312): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 12:03:23.498 F/DEBUG   (312): Build fingerprint: 'htc/m8_google/htc_m8:6.0/MRA58K.H6/648564:user/release-keys'
04-06 12:03:23.498 F/DEBUG   (312): Revision: '0'
04-06 12:03:23.498 F/DEBUG   (312): ABI: 'arm'
04-06 12:03:23.498 F/DEBUG   (312): pid: 15167, tid: 15167, name: pl.qus.xenoamp  >>> pl.qus.xenoamp <<<
04-06 12:03:23.498 F/DEBUG   (312): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc2732362
04-06 12:03:23.514 F/DEBUG   (312):     r0 00000004  r1 be900a40  r2 00000004  r3 24000016
04-06 12:03:23.515 F/DEBUG   (312):     r4 85f8a10f  r5 9e73234c  r6 85f8a10c  r7 85f8a0fd
04-06 12:03:23.515 F/DEBUG   (312):     r8 12c9a7c0  r9 b4c76500  sl 12c9e3c0  fp be90113c
04-06 12:03:23.515 F/DEBUG   (312):     ip 9e7375cc  sp be9009e8  lr 9e7091fc  pc 9e70ce88  cpsr 80000010
04-06 12:03:23.516 F/DEBUG   (312): 
04-06 12:03:23.516 F/DEBUG   (312): backtrace:
04-06 12:03:23.516 F/DEBUG   (312):     #00 pc 0000de88  /data/app/pl.qus.xenoamp-2/lib/arm/libspotify_embedded_shared.so
04-06 12:03:23.516 F/DEBUG   (312):     #01 pc 0000a1f8  /data/app/pl.qus.xenoamp-2/lib/arm/libspotify_embedded_shared.so
04-06 12:03:24.478 F/DEBUG   (312): 
04-06 12:03:24.478 F/DEBUG   (312): Tombstone written to: /data/tombstones/tombstone_03
04-06 12:03:24.478 E/DEBUG   (312): AM write failed: Broken pipe
04-06 12:03:24.483 W/ActivityManager(748):   Force finishing activity pl.qus.xenoamp/.NewMainActivity
04-06 12:03:24.505 I/BootReceiver(748): Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
04-06 12:03:24.538 W/MediaFocusControl(748):   AudioFocus   audio focus client died
04-06 12:03:24.538 I/MediaFocusControl(748): AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@cd8df5e
04-06 12:03:24.538 E/WifiService(748): Multicaster binderDied
04-06 12:03:24.539 D/WifiService(748): releaseWifiLockLocked: WifiLock{AndroidRouter type=3 binder=android.os.BinderProxy@4150a3b}
04-06 12:03:24.539 D/GraphicsStats(748): Buffer count: 7
04-06 12:03:24.539 I/WindowState(748): WIN DEATH: Window{72c421b u0 pl.qus.xenoamp/pl.qus.xenoamp.NewMainActivity}
04-06 12:03:24.575 W/MediaSessionRecord(748): Removing dead callback in pushEvent.
04-06 12:03:24.575 W/MediaSessionRecord(748): android.os.DeadObjectException
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at android.os.BinderProxy.transactNative(Native Method)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at android.os.BinderProxy.transact(Binder.java:503)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at android.media.session.ISessionControllerCallback$Stub$Proxy.onSessionDestroyed(ISessionControllerCallback.java:219)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.server.media.MediaSessionRecord.pushSessionDestroyed(MediaSessionRecord.java:709)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.server.media.MediaSessionRecord.-wrap12(MediaSessionRecord.java)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.server.media.MediaSessionRecord$MessageHandler.handleMessage(MediaSessionRecord.java:1429)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at android.os.Looper.loop(Looper.java:148)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.server.SystemServer.run(SystemServer.java:300)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.server.SystemServer.main(SystemServer.java:172)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at java.lang.reflect.Method.invoke(Native Method)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-06 12:03:24.575 W/MediaSessionRecord(748): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-06 12:03:24.593 I/ActivityManager(748): Process pl.qus.xenoamp (pid 15167) has died
04-06 12:03:24.594 W/ActivityManager(748): Scheduling restart of crashed service pl.qus.xenoamp/.xenoservice.XenoUpnpService in 1000ms
04-06 12:03:24.594 W/ActivityManager(748): Scheduling restart of crashed service pl.qus.xenoamp/.xenoservice.XenoAmpService in 11000ms
04-06 12:03:24.594 W/ActivityManager(748): Scheduling restart of crashed service pl.qus.xenoamp/.xenoservice.XenoStreaming in 21000ms

second one:

04-04 12:29:28.079 I/SELinux (312): SELinux: Loaded file_contexts contexts from /file_contexts.
04-04 12:29:28.080 F/DEBUG   (312): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-04 12:29:28.080 F/DEBUG   (312): Build fingerprint: 'htc/m8_google/htc_m8:6.0/MRA58K.H6/648564:user/release-keys'
04-04 12:29:28.080 F/DEBUG   (312): Revision: '0'
04-04 12:29:28.080 F/DEBUG   (312): ABI: 'arm'
04-04 12:29:28.080 F/DEBUG   (312): pid: 9205, tid: 9205, name: pl.qus.xenoamp  >>> pl.qus.xenoamp <<<
04-04 12:29:28.080 F/DEBUG   (312): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcc49935a
04-04 12:29:28.095 F/DEBUG   (312):     r0 00000004  r1 be900a40  r2 00000004  r3 3400000e
04-04 12:29:28.095 F/DEBUG   (312):     r4 8bf0a11d  r5 9849934c  r6 8bf0a10c  r7 8bf0a0fd
04-04 12:29:28.095 F/DEBUG   (312):     r8 32e0fc40  r9 b4c76500  sl 12cae620  fp be90113c
04-04 12:29:28.095 F/DEBUG   (312):     ip 9849e5cc  sp be9009e8  lr 984701fc  pc 98473e88  cpsr 80000010
04-04 12:29:28.096 F/DEBUG   (312): 
04-04 12:29:28.096 F/DEBUG   (312): backtrace:
04-04 12:29:28.096 F/DEBUG   (312):     #00 pc 0000de88  /data/app/pl.qus.xenoamp-2/lib/arm/libspotify_embedded_shared.so
04-04 12:29:28.096 F/DEBUG   (312):     #01 pc 0000a1f8  /data/app/pl.qus.xenoamp-2/lib/arm/libspotify_embedded_shared.so
04-04 12:29:28.935 F/DEBUG   (312): 
04-04 12:29:28.935 F/DEBUG   (312): Tombstone written to: /data/tombstones/tombstone_01
04-04 12:29:28.935 E/DEBUG   (312): AM write failed: Broken pipe

**Comment by alliejc** [comment]
I am having the same issue.  It occurs most predictably when skipping through songs, yet it has also happened on clicking the first song after login.

Moto X Pure Edition
Android Version 6.0

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa3b93196 in tid 24884
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x36f6a34c in tid 25885

**Comment by alliejc** [comment]
#182

**Comment by ssuukk** [comment]
I think this android client is abandoned.

I am having the same issue. It occurs most predictably when skipping
through songs, yet it has also happened on clicking the first song after
login.

Moto X Pure Edition
Android Version 6.0

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa3b93196 in tid
24884
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x36f6a34c in tid
25885

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/spotify/android-sdk/issues/214#issuecomment-232229133>,
or mute the thread
<https://github.com/notifications/unsubscribe/ACu3eZ4aiF7DO67BMZ0u3bUAT78WnKz9ks5qVD3RgaJpZM4IByFi>
.

**Comment by d-kunin** [comment]
Guys please re-check with the latest build available https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13
