### ISSUE TITLE
Buffer Issues: Playback constantly stuttering / cache causes stutter

### ISSUE THREAD

**Issue by jhmacdon** [spotify/android-sdk#218]
So I continually get stuttered playback, followed by this message:

`releaseBuffer() track 0xac7cb860 disabled due to previous underrun, restarting`

I am on 220mb/s internet so I doubt this is due to slow internet. I have tried running from mainactivity, I have tried moving the player to a foreground service, but nothing seems to help. 

Any ideas?
_________________________________________________

Update: Turning off cache `playerConfig.useCache(false)` seems to remove the issue. Not sure why, but would be interested in anyones ideas? Would like to find a way to fix this and use cache if possible, obviously.

**Comment by d-kunin** [comment]
Can you check with the latest release please ? https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13

**Comment by jhmacdon** [comment]
I'll have to give this a look.
