### ISSUE TITLE
Spotify app does not play when launched while Android phone screen OFF.

### ISSUE THREAD

**Issue by jwang14** [spotify/android-sdk#221]
This may not be an SDK issue but not sure if posted here would be better than general support forum.

Spotify app does NOT start playing when:
Using an external Bluetooth device to launch Google Now (or other Android service) which in turn to launch Spotify app to play a song while phone screen is off. We have to light up the screen either manually or programmatically to make it play. Not the best scenario for our development purpose.

**Comment by d-kunin** [comment]
Hey @jwang14 since it is not the SDK issue we cannot help here. Try https://community.spotify.com/t5/Android/bd-p/spotifyandroid so that a dedicated team gets it.
