### ISSUE TITLE
Queuing and shuffle unexpected behaviour

### ISSUE THREAD

**Issue by JoshFalken** [spotify/android-sdk#228]
First I queue a number of songs:

```
mPlayer.clearQueue();
for (TrackSimple trackSimple : savedAlbum.album.tracks.items) {
     mPlayer.queue(trackSimple.uri);
}
```

Than I start playing and use the following to skip to the next song:

```
mPlayer.skipToNext();
```

This all works great but when I turn of shuffling and I call skiptonext(), it skips ahead a number of tracks in the queue and ends when it reaches the final track. The behaviour I expect is that the queue is shuffled or that a function shuffleQueue/unshuffleQueue is added.

BTW: I enjoyed working with this API a lot.

**Comment by d-kunin** [comment]
Could you check that for beta 21 and reopen if relevant? Thank you!
