### ISSUE TITLE
Play Track with a Free Spotify Account

### ISSUE THREAD

**Issue by Rapoporras** [spotify/android-sdk#229]
our application was detecting either case where you try to play a specific song with an account free, but suddenly began to play songs also with that account, after checking several days if it was a fault of our app we think might be a bug in its API we have detected this error because both the app 1.0.0 - beta 10 and 1.0.0 - beta 12 could you tell me some solution on this?

**Comment by erdtman** [comment]
You should not be able to use a free-account with the mobile SDKs (Android-SDK and iOS SDK). There might have been glitch. Can you verify that you cannot use a free account with your app?
