### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by AlokBansal8** [spotify/android-sdk#230]
What is this custom protocol redirect uri? Can anyone please elaborate on it?

**Comment by jchoi18** [comment]
You can just make up a random callback address like (appname)://callback and it should work. I think Spotify uses the address to get back to your app after certain activities.

**Comment by erdtman** [comment]
This is a OAuth 2 thing, for more details see https://tools.ietf.org/html/rfc6749

**Comment by abechoi** [comment]
If your URI is set to "spotifytutorial://callback", what should you add for the Redirect URI in your dashboard?

**Comment by arirawr** [comment]
You should set it to `simpleapp://callback`

**Comment by Twobeard** [comment]
The dashboard requires a http or https infront of your URI. Does your redirect URI need to be hosted so it's visible to everyone?

filling in `simpleapp://callback` says "Not a valid URI"

**Comment by arirawr** [comment]
@Twobeard The dashboard does not require http(s) - can you make sure there are no extra spaces around the URL?
