### ISSUE TITLE
Android AuthorizationActivity: INVALID_APP_ID

### ISSUE THREAD

**Issue by daniksh** [spotify/android-sdk#233]
**What I am doing:**
```
        AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID,
                AuthenticationResponse.Type.TOKEN,
                REDIRECT_URI);
        builder.setScopes(new String[]{"streaming", "playlist-read-private", "playlist-read-collaborative", "user-library-read"});
        AuthenticationRequest request = builder.build();

        AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == REQUEST_CODE) {
            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, data);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
                SpotifyTokenManager.writeToken(this, response.getAccessToken());
            }else{
                System.out.println("ERROR! " + response.getError());
            }
        }
    }
```
**What I get is:** 
`E/Spotify: [main@sso.AuthorizationActivity:371] INVALID_APP_ID`.

I have re-checked package name, certificate fingerprint and CLIENT_ID several times and I am completely sure they are the same as in the "My applications" section on Spotify website.

**What does that error mean?** This error is not documented :(

By the way, what is the purpose of redirect uri in Android apps. Do i have to listen on it to get the response or is it enough to get it onActivityResult?

**Comment by cloudface** [comment]
I get the same error. I updated to the latest Spotify Android SDK (Spotify auth 1.0.0 beta 12, Spotify player 1.0.0 beta 12) today and since then I've been getting this error when I try to authenticate.

**Comment by takvinge** [comment]
I got the same error and follow the tips from cloudface. When I went back to 1.0.0.beta 11  the authentication worked as it should

**Comment by imsantosh100** [comment]
I am implementing SSO in my app where i tried using Spotify auth 1.0.0 beta 12 to authenticate i got response as INVALID_APP_ID,as mentioned in the above solution i tried using Spotify auth 1.0.0 beta 11.Its worked fine but if i use this i can't access the Spotify Android app to obtain access tokens (which is the new feature in Spotify auth 1.0.0 beta 12) which will redirect to webview So how to go further

**Comment by joekickass** [comment]
Also getting this error with beta12, works with beta11

**Comment by pewusoft** [comment]
I can also confirm the issue using beta13, beta11 works fine.

**Comment by Rahul-kAgrawal** [comment]
i used your code from https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/, getting following error when i am trying to login.

08-18 14:52:26.201 16713-16713/com.player.myspotifymusic I/chromium: [INFO:CONSOLE(6)] "SyntaxError: Unexpected token I in JSON at position 0
                                                                         at Object.parse (native)
                                                                         at J (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:5:6501)
                                                                         at At (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:6:14454)
                                                                         at https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:6:14923
                                                                         at i (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:5:1297)
                                                                         at Tt (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:6:14905)
                                                                         at o (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:6:15632)
                                                                         at s (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:7:2578)
                                                                         at https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:7:2750
                                                                         at f.$eval (https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js:7:10267)", source: https://d2d1dxiu3v1f2i.cloudfront.net/baa0509/js/index.js (6)

Thanks

**Comment by d-kunin** [comment]
That should work fine given that you use the same client_id and *signature* as you registered at the developer site.

If you have both debug and release signatures, make sure you've added both.
