### ISSUE TITLE
Android sdk, Player issue

### ISSUE THREAD

**Issue by AlexeiaW** [spotify/android-sdk#235]
Hi,

I am getting this problem:
Playback event received: BECAME_ACTIVE
                                                                           
                                                                           [ 06-02 14:07:05.253   210:  318 D/         ]
                                                                           RIL_onMultiClientUnsolicitedResponse: 11010

and

Playback event received: PLAY
Playback event received: TRACK_START
Playback event received: AUDIO_FLUSH

I did set useCache to false.
The player was working fine, and then suddenly gave me these issues.

Any help would be appreciated.

Regards

**Comment by osharifali** [comment]
I am having the same issue. Does your media player minimize and not come back as well? @AlexeiaW

**Comment by d-kunin** [comment]
@AlexeiaW we need more detailed explanation to be able to help.
What is expected behaviour and what is actual? How do you reproduce the issue. Unfortunately, I cannot understand it from the fasts you've provided.
Please reopen with a detailed description if the issue is relevant.
