### ISSUE TITLE
Could not find class 'PersistableBundle' in .openLoginActivity(...) on Android 4.4(.2)

### ISSUE THREAD

**Issue by sharaquss** [spotify/android-sdk#236]
Hi, I pasted code from your 'beginners tutorial' and I try to get it working, but it's giving me hard time. 
Last line of onCreate() method in Main Activity is 
```
`AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);`

and this is where i get:
`06-09 01:21:03.810 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.811 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.812 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.812 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.815 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.817 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.818 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.pszemek.betterfy.MainActivity.access$super
06-09 01:21:03.821 9698-9698/com.pszemek.betterfy E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.pszemek.betterfy.MainActivity.access$super`
```
So, I guess this is because I extend AppCompatActivity, instead of Activity (different parameters to onCreate), but how can I get this code to work on APIs lower than 21? Tried to google it out but without luck.
Thanks!

**Comment by GuoJinyu** [comment]
Same Question

**Comment by d-kunin** [comment]
What version of auth library do you guys use?

**Comment by sharaquss** [comment]
Don't remember importing any auth library at all to be honest. 
Btw: Now I work on Nexus 5 w/ Android 6.0.1 and have no problems whatsoever. 
Curiously enough, I noticed that on my older phone, this problem was occurring only when I was logged in on official Spotify Android app. 
When I logged out or uninstalled official app, I could use AuthenticationClient's methods inside my project with ease.
Don't know if this was because my older phone is some serious cheap crap or is it a bug in SDK, but if you're running out of ideas, you can try that one! :)

**Comment by d-kunin** [comment]
What version of the SDK do you use? What kind of phone is crashing with `could not find class`? Didn't manage to repro it so far.

**Comment by d-kunin** [comment]
Closing as not-active.
