### ISSUE TITLE
Tutorial syntax

### ISSUE THREAD

**Issue by illblew** [spotify/android-sdk#237]
Your tutorial is missing two semicolons. 

One is " private static final int REQUEST_CODE = 1337"

The other is "builder.setScopes(new String[]{"user-read-private", "streaming"})"

These are both found at https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/ under the MainActivity example.

**Comment by erdtman** [comment]
Thanks for the feedback, missing semicolons has now been added.
