### ISSUE TITLE
Android - Check login status without calling AuthenticationClient.openLoginActivity

### ISSUE THREAD

**Issue by andrearinaldispotsoftware** [spotify/android-sdk#238]
Hi guys,

is there a way to check the login status through the Android SDK without opening the LoginActivity if there's no user logged in?

I mean.. I'd like to call something like `AuthenticationClient.getLoginStatus()` instead of being forced to call `AuthenticationClient.openLoginActivity()` that would bring me outside of my application's flow.

Hoping you can help me, thanks in advance for the attention.

Regards

**Comment by d-kunin** [comment]
Hey, @andrearinaldispotsoftware!
If you mean `check if the user is logged in in the Spotify App` then there is no way.
If you mean `checking if my access token is still valid` than you can ether keep track of `authenticationResponse.getExpiresIn()` or make a simple web-api call like `https://api.spotify.com/v1/me`
