### ISSUE TITLE
Support crossfade between two tracks

### ISSUE THREAD

**Issue by ssawchenko** [spotify/android-sdk#239]
Hello hello,

I have implemented a basic music player, based heavily on the simple demo Android project found in the documentation - and I am now looking to add a cross fade transition between tracks. The SDK docs indicate that we should only have one instance of the Player object, so I am unsure on how to implement this. To do this with Android's stock MediaPlayer class, I simply created two objects, one for each track, and then applied a fade in / fade out respectively by adjusting the MediaPlayer's volume.

I noticed there was an iOS version of this issue (https://github.com/spotify/ios-sdk/issues/73), but I am not sure if the answer is applicable since the audio control we have in Android is vastly different.

So now my questions: 

1. How would I go about playing two tracks simultaneously using the SDK, since the docs state we should have only one instance of the Player object?

2. How do I modify the volume of a track? https://github.com/spotify/android-sdk/issues/103 mentions implementing our own custom AudioController to apply a fade on a single track. Is this applicable at all to my problem since I essentially need to modify multiple tracks at once? And if so, any initial guidance /  reference on how to set this up would be much appreciated.

Cheers

**Comment by d-kunin** [comment]
It seems like we will not be able to prioritize this issue any time soon.
