### ISSUE TITLE
addConnectionStateCallback not always triggered.

### ISSUE THREAD

**Issue by oleaasbo** [spotify/android-sdk#240]
Hi, i have made an app that has been working for a long time now, it is still under development and I found a bug that appears when the app begins to load more thing then just the spotify library. 
From the tutorial:  
Spotify.getPlayer(playerConfig, BackgroundService.this, new Player.InitializationObserver() {
   @Override
   public void onInitialized(Player player) {
      mPlayer = player;
      mPlayer.addConnectionStateCallback(BackgroundService.this);
      mPlayer.addPlayerNotificationCallback(BackgroundService.this);
   }
   @Override
   public void onError(Throwable throwable) {
      Log.e(LOG_TAG, "Could not initialize player: " + throwable.getMessage());
      stopSelf();
   }
});

This sometimes fail to call onLoggedIn() because the Player may set the mIsLoggedIn variable and call its listeners before the listener accualy is registered.

When i first made the barebone app with almost only the spotify library and some minor other things, it works nicely! But now after some development and longer load times the listeners are added after the spotify library call its listeners. The result of that is i am unable to continiue my app beacuse i depend on the callback isLoggedOn().

My quick fix to those how also notice their app not allways get the onLoggedOn() callback is:
After the listeners are registered, call the onLoggedOn() manually:
mPlayer = player;
mPlayer.addConnectionStateCallback(BackgroundService.this);
mPlayer.addPlayerNotificationCallback(BackgroundService.this);
if(mPlayer.isLoggedIn()){
   onLoggedIn();
}

And modify the callback like this:
@Override
public void onLoggedIn() {
   synchronized (LogginLock) {
      if(!logginEventCalled) {
         logginEventCalled = true;
         //TODO Do something
      }
   }
}

The LogginLock is -> Object LogginLock = new Object();
The logginEventCalled is inizialized -> boolean logginEventCalled = false;

There is still a problem though. I need to recieve the error messages also...

**Comment by d-kunin** [comment]
I dont know if we can do more than you do with `isLoggedIn()`. We could make the callback to receive the last state in a sticky way, but that could break login for others.
