### ISSUE TITLE
Not receiving metadata while using Android SDK

### ISSUE THREAD

**Issue by ganeshskudva** [spotify/android-sdk#241]
Hello Folks,
                  I am trying to build an android app, which plays music from Spotify. I am trying to get metadata from Spotify to display Track/Album/Artist being played currently. 
I have enabled "**Device Broadcast Status**" in Spotify Android app setting. 
As per the suggestions from these two SO threads, [Link-1](http://stackoverflow.com/questions/17236358/how-is-it-possible-to-know-whats-spotify-is-playing-from-an-external-android-ap) & [Link-2](http://stackoverflow.com/questions/24687063/having-problems-getting-the-metadata-for-spotify-songs) I tried these two intent filters: 

> com.android.music.metachanged 

> com.spotify.music.metachanged

None of them seem to work. I can play song from the SDK, but unable to get any metadata.
I am using Spotify Android SDK: **1.0.0-beta12**

Can you kindly let me know, what am I missing?

**Comment by d-kunin** [comment]
You combine two different approaches, cause the links you've sent are for getting metadata from Spotify App (not from the sdk).

For the sdk you can call `spotifyPlayer.getMetadata()`.
