### ISSUE TITLE
Android M - Frequent crashes when playing tracks with Android SDK

### ISSUE THREAD

**Issue by tisalmin** [spotify/android-sdk#242]
Our app is playing tracks from user's and featured playlists. We're suddenly facing several crashes from native lib when trying to play a track. For us the best way to reproduce this was to switch between play/ pause for a while, but this has happened also randomly when just starting once the playback.

We use the latest SDK and this happens on Nexus 5X with Android 6.0.1. As it is the c-lib crashing, there is not much in the stack trace except "FATAL SIGNAL" (our package name hidden below):

06-23 11:21:39.279 19005-20221/com.ficonic.*** I/SpotifySDK: Got notification: Became active playing device
06-23 11:21:39.279 19005-20221/com.ficonic.*** I/SpotifySDK: playbackCallbackOnSeek (to 0ms)
06-23 11:21:39.665 19005-20221/com.ficonic.*** I/SpotifySDK: Login complete
06-23 11:21:39.799 19005-20221/com.ficonic.*** I/SpotifySDK: Got notification: Track changed
**06-23 11:21:39.800 19005-20221/com.ficonic.*** A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x62a0495d in tid 20221 (SpotifySdkPlaye)**

**Comment by alliejc** [comment]
I am having the same issue. It occurs most predictably when skipping through songs, yet it has also happened on clicking the first song after login.

Moto X Pure Edition
Android Version 6.0

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa3b93196 in tid 24884
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x36f6a34c in tid 25885

**Comment by alliejc** [comment]
#182

**Comment by d-kunin** [comment]
Please recheck with the latest build https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13

**Comment by nitinkumar8462** [comment]
I am getting same issue on 1.0.0-beta13  also
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x183f83c8 in tid 25371
