### ISSUE TITLE
Cast music with Chromecast

### ISSUE THREAD

**Issue by alexandre-lefranc-ezeeworld** [spotify/android-sdk#243]
Hi,

I use the Spotify SDK in my Android application and I need to cast music with Chromecast.
How I can do that ?

Regards,

**Comment by erdtman** [comment]
If I have understood Chromecast correct it gets the audiostream/videostream directly from the server so there is no obvious way to integrate the Android-SDK with cast.

**Comment by JMSerruya** [comment]
That's correct. This is not currently supported by our SDK.
