### ISSUE TITLE
Track preview

### ISSUE THREAD

**Issue by LeoKaliazine-Digiflare** [spotify/android-sdk#246]
As of now it seems only the web-api provides ability to play track previews. Basically, it seems if you want to support that feature for non-logged in users there's basically no point in using the android-sdk (compile 'com.spotify.sdk:spotify-player:1.0.0-beta12@aar') since you'll be duplicating code by supporting players from both the web-api-wrapper and android-sdk depending on the user? Please either add support for 30s track previews and other calls that don't require authentication in the web-api, or explain what is the 'best practice' for supporting both non-logged in, free, and premium users within android-sdk?

**Comment by d-kunin** [comment]
We dont have plans for adding preview support to sdk.

At the moment the Android SDK is not supposed to be used by non-premium users, so I can't give decent advice on how to combine these experiences in the same app. I guess you can write your own facade that will fallback to standard system player for non-premiums. Woul be nice to hear how you solve the problem.

**Comment by LeoKaliazine-Digiflare** [comment]
Basically had to solve this by creating my own interface (AudioPlayer) and making wrapper classes for the Spotify premium player and my own free player implementation. Naturally the wrapper for the free player had a lot more logic than the one for the premium one (especially logic related to management of song list, to support shuffle, etc...), which could hand off most things to the spotify premium player...

**Comment by phoenixdesignza** [comment]
@LeoKaliazine-Digiflare Any pointers you could give me on where to start with a free player implementation like you've described? I assume you're making calls to the web-api instead of the android one, but I have no clue on how to even begin to do that.
