### ISSUE TITLE
java.lang.NoSuchMethodError Config.shouldUseCache()

### ISSUE THREAD

**Issue by cjwilliams24680** [spotify/android-sdk#247]
I'm running beta 12 on a Samsung Galaxy S5 Marshmallow and I'm getting this crash. Any ideas?

I'm also getting the crash on a LG Leon LTE, a Galaxy S3, a nexus 5, and a nexus 6 emulator with x86 arch

'A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: no non-static method "Lcom/spotify/sdk/android/player/Config;.shouldUseCache()Z"
A/art: art/runtime/java_vm_ext.cc:410]   at getPlayer (Spotify.java:110)
A/art: art/runtime/java_vm_ext.cc:410]   at getPlayer (Spotify.java:76)
A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 0001556c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni14JavaClassUtils9findClassEP7_JNIEnvPKcb+492)
A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 00015a90  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni18JavaExceptionUtils20throwExceptionOfTypeEP7_JNIEnvPKcS5_St9__va_list+32)
A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 0001607c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni18JavaExceptionUtils20throwExceptionOfTypeEP7_JNIEnvPKcS5_z+32)
A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 000120ec  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni9JavaClass11cacheMethodEP7_JNIEnvPKcS5_z+540)
A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 0000896c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3sdk6Config10initializeEP7_JNIEnv+440)
A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 00009488  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3sdk6ConfigC2EP7_JNIEnv+128)
A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 00009f5c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (JNI_OnLoad+48)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.NativeSdkPlayer.nativeInit(NativeSdkPlayer.java:46)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.NativeSdkPlayer.<clinit>(NativeSdkPlayer.java:34)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Player.<init>(Player.java:310)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Player.create(Player.java:356)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Player.access$000(Player.java:86)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Player$Builder.build(Player.java:282)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:110)
A/art: art/runtime/java_vm_ext.cc:410]   at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:76)
A/art: art/runtime/runtime.cc:366]   native: #10 pc 0001556c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni14JavaClassUtils9findClassEP7_JNIEnvPKcb+492)
A/art: art/runtime/runtime.cc:366]   native: #11 pc 00015a90  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni18JavaExceptionUtils20throwExceptionOfTypeEP7_JNIEnvPKcS5_St9__va_list+32)
A/art: art/runtime/runtime.cc:366]   native: #12 pc 0001607c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni18JavaExceptionUtils20throwExceptionOfTypeEP7_JNIEnvPKcS5_z+32)
A/art: art/runtime/runtime.cc:366]   native: #13 pc 000120ec  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3jni9JavaClass11cacheMethodEP7_JNIEnvPKcS5_z+540)
A/art: art/runtime/runtime.cc:366]   native: #14 pc 0000896c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3sdk6Config10initializeEP7_JNIEnv+440)
A/art: art/runtime/runtime.cc:366]   native: #15 pc 00009488  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (_ZN7spotify3sdk6ConfigC2EP7_JNIEnv+128)
A/art: art/runtime/runtime.cc:366]   native: #16 pc 00009f5c  /data/app/com.gametime.gametime.debug-1/lib/arm/libspotify_sdk.so (JNI_OnLoad+48)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.NativeSdkPlayer.nativeInit(NativeSdkPlayer.java:46)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.NativeSdkPlayer.<clinit>(NativeSdkPlayer.java:34)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Player.<init>(Player.java:310)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Player.create(Player.java:356)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Player.access$000(Player.java:86)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Player$Builder.build(Player.java:282)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:110)
A/art: art/runtime/runtime.cc:366]   at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:76)'

**Comment by d-kunin** [comment]
Please reopen for beta 21 if relevant.
Also please check that you dont obfuscate library classes with proguard.
