### ISSUE TITLE
Crash on playback start when changing tracks (beta13, caching disabled)

### ISSUE THREAD

**Issue by tisalmin** [spotify/android-sdk#249]
Device: Samsung Galaxy Tab S2
Android: 5.0.2
Network: Cell network, 3G (low signal)

Trace:
07-18 08:22:39.977 11443-11443/com.ficonic.project D/SpotifyPlayer: PlaybackEvent --  TRACK CHANGED 
07-18 08:22:39.977 11443-13610/com.ficonic.project I/SpotifySDK: Got notification: Track started
07-18 08:22:39.977 11443-11443/com.ficonic.project D/SpotifyPlayer: PlaybackEvent -- PLAY
07-18 08:22:40.287 11443-13610/com.ficonic.project I/SpotifySDK: Got notification: Audio flush
07-18 08:22:40.432 9741-9741/? I/DEBUG:     #00 pc 0000e1f8  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
07-18 08:22:40.432 9741-9741/? I/DEBUG:     #01 pc 0000a1f8  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
07-18 08:22:41.367 3356-3356/? D/CrashAnrDetector: Build: samsung/gts28ltexx/gts28lte:5.0.2/LRX22G/T715XXU2APB2:user/release-keys
                                                   Hardware: universal5433
                                                   Revision: 8
                                                   Bootloader: T715XXU2APB2
                                                   Radio: unknown
                                                   Kernel: Linux version 3.10.9-6572077 (dpi@SWDD6715) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Thu Feb 11 21:40:59 KST 2016
                                                   
                                                   *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
                                                   Build fingerprint: 'samsung/gts28ltexx/gts28lte:5.0.2/LRX22G/T715XXU2APB2:user/release-keys'
                                                   Revision: '8'
                                                   ABI: 'arm'
                                                   pid: 11443, tid: 11443, name: conic.project  >>> com.ficonic.project <<<
                                                   signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb92a6d65
                                                       r0 00000004  r1 bee10860  r2 00000004  r3 1bcd5a19
                                                       r4 9580a116  r5 9580a0fd  r6 9d5d134c  r7 9580a10b
                                                       r8 00000000  r9 b4428000  sl 00000000  fp bee10f5c
                                                       ip 9d5d65cc  sp bee10800  lr 9d5a81fc  pc 9d5ac1f8  cpsr 80000010
                                                       d0  000048aa006fad00  d1  72646e612f6b6400
                                                       d2  79616c702f646900  d3  766974614e2f7200
                                                       d4  00000000000f5a46  d5  0000000000000000
                                                       d6  0000000000000000  d7  0000000800000008
                                                       d8  0000000000000000  d9  0000000000000000
                                                       d10 0000000000000000  d11 0000000000000000
                                                       d12 0000000000000000  d13 0000000000000000
                                                       d14 0000000000000000  d15 0000000000000000
                                                       d16 0000280600002806  d17 0000280600000000
                                                       d18 0064004100650043  d19 006c007600490061
                                                       d20 0101010101010101  d21 0101010101010101
                                                       d22 8080808080808080  d23 8080808080808080
                                                       d24 58746b746c764961  d25 376d647033367635
                                                       d26 1010101010101010  d27 1010101010101010
                                                       d28 0000000000000000  d29 0000000000000000
                                                       d30 0000000000000000  d31 0000000000000000
                                                       scr 20000014
                                                   
                                                   backtrace:
                                                       #00 pc 0000e1f8  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
                                                       #01 pc 0000a1f8  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
                                                   
                                                   stack:
                                                            bee10780  00000000  
                                                            bee10784  00000000  
                                                            bee10788  00000003  
                                                            bee1078c  00000000  
                                                            bee10790  00000000  
                                                            bee10794  00000000  
                                                            bee10798  b4f9161e  /system/lib/libart.so
                                                            bee1079c  b4d6db13  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckEbPKcz.constprop.128+218)
                                                            bee107a0  00550000  
                                                            bee107a4  0000001a  
                                                            bee107a8  00000001  
                                                            bee107ac  00000004  
                                                            bee107b0  bee10850  [stack]
                                                            bee107b4  9d5d64cc  
                                                            bee107b8  9d5d65c0  
                                                            bee107bc  bee10838  [stack]
                                                            bee107c0  00000003  
                                                            bee107c4  9d5a8f00  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
                                                            bee107c8  bee10838  [stack]
                                                            bee107cc  00000000  
                                                            bee107d0  b6f43fc8  
                                                            bee107d4  00000003  
                                                            bee107d8  b4404e00  
                                                            bee107dc  9580a116  
                                                            bee107e0  9580a0fd  
                                                            bee107e4  9d5d134c  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
                                                            bee107e8  9580a10b  
                                                            bee107ec  00000000  
                                                            bee107f0  b4428000  
                                                            bee107f4  00000000  
                                                            bee107f8  bee10f5c  [stack]
                                                            bee107fc  9d5ac1f0  /data/app/com.ficonic.project-1/lib/arm/libspotify_embedded_shared.so
                                                       #00  bee10800  b44712b0  
                                                            ........  ........
                                                       #01  bee10800  b44712b0  
                                                            bee10804  109716f1  
                                                            bee10808  00000004  
                                                            bee1080c  5bbbcdeb  
                                                            bee10810  006fad2a  
                                                            bee10814  000048aa  
                                                            bee10818  00000000  
                                                            bee1081c  00000000  
                                                            bee10820  00000001  
                                                            bee10824  0000003e  
                                                            bee10828  9f4e8940  
                                                            bee1082c  139e2190  /dev/ashmem/dalvik-main space (deleted)
                                                            bee10830  9f6e37b4  
                                                            bee10834  00000000  
                                                            bee10838  00000004  
                                                            bee1083c  7294a529  /system/framework/arm/boot.oat
                                                            bee10840  094a0c2e  
                                                            bee10844  0000012c  
                                                            bee10848  00000000  
                                                            bee1084c  04000000  
                                                            bee10850  00000004  
                                                            bee10854  1bcd5a19  /dev/ashmem/dalvik-main space (deleted)
                                                            bee10858  006f3568  
                                                            bee1085c  00000000  
                                                            bee10860  00000000  
                                                            bee10864  bee1086c  [stac

**Comment by d-kunin** [comment]
Please reopen if it is relevant on beta 21.
