### ISSUE TITLE
Spotify.getPlayer leads to crash on devices with 64bit CPUs

### ISSUE THREAD

**Issue by LeoKaliazine-Digiflare** [spotify/android-sdk#250]
Calls to Spotify.getPlayer cause the application to crash.
I'm experiencing this kind of crash a Samsung S6 and Nexus 9 devices (the same code works on my HTC M8). All I get in the logs is: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file... with a list of all the dex files etc...
This happens with beta13 build. I tried a solution of exporting all the player aar's jni folder contents suggested in #34 to no avail. It's likely the reason my app is being build for 64bit is due to my use of renderscriptTargetApi 21, which adds so arm64-v8a `jni` `so` files to my apk. Although reducing the renderscript api target even to 19 still generates those arm64-v8a resources, so not sure.

**Comment by LeoKaliazine-Digiflare** [comment]
I can temporarily address this problem by excluding all 64 bit libs so's, but 64bith support should really be added to the sdk.
```ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }```

**Comment by vladislav-k** [comment]
Hi guys,

any update due to this issue?

Thank

**Comment by d-kunin** [comment]
64 archs are included to beta22.
