### ISSUE TITLE
Repeated calls to skipToNext or skipToPrevious cause crash [BETA 13].

### ISSUE THREAD

**Issue by jacoblubecki** [spotify/android-sdk#252]
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc7972cf8 in tid 14273 (SpotifySdkPlaye)
```

This is all that shows up in my logcat output. I get this error pretty consistently when trying to rapidly skip through tracks. Running on android 6.0.1 using a Samsung Galaxy S6 Edge for testing.

**Comment by tisalmin** [comment]
I believe this is the same as #249. Similar issues existed too for beta12.

**Comment by tisalmin** [comment]
Any updates for this one? Would be great to have a work around for this to prevent our whole app from crashing due to this problem. Thanks!

**Comment by d-kunin** [comment]
We dont support beta 12 anymory, please check if it is still an issue in beta 21.
