### ISSUE TITLE
INVALID_APP_ID on physical device

### ISSUE THREAD

**Issue by jvcdk** [spotify/android-sdk#253]
Hi,

I am trying to get started with developing an android app using the Spotify SDK. I am using version beta 13.

I followed the tutorial put up and trying it out on a software emulator (on my computer) the login-procedure works fine. Trying it out on my physical phone (debugging from Android Studio) I get an INVALID_APP_ID response from the authorization procedure.

What can be wrong? I would like to give more details - but don't quite know what to look for.

~Jørn

**Comment by erdtman** [comment]
Make sure the "Android Packages" details is correct on the My app details on the Spotify developer page.

**Comment by d-kunin** [comment]
You need to use the same signature and package name that you have registered on your developer page. 
Most likely you will need to add your debug key signature as well. Read more http://stackoverflow.com/questions/4594952/android-key-hash

**Comment by jvcdk** [comment]
Thanks for your reply - it helped me in the right direction.

For other visitors (that find the documentation a bit wanty like me), here is how to find your sha1 finger print:

`keytool -exportcert -alias <key alias> -keystore ~/.android/<key store> -list -v`

Combine that with the package name stated in your android manifest and enter that on the Spotify My Applications page.

~Jørn
