### ISSUE TITLE
How to use generated token Again for playing music?

### ISSUE THREAD

**Issue by ronit12** [spotify/android-sdk#254]
I am generating token and then storing it into sharedpreference, but while I am using that stored token for player at that time it showing LogIn failure.
So How can I reuse  once generated token  for player?
and What is expire time of token?

**code snippet**    
String token = AppPreferenceManager.getPreference(this, "key", null);
        if (token != null){
            playMusic(token);
            onLoggedIn();
        }else {
            AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID, AuthenticationResponse.Type.TOKEN, REDIRECT_URI);
            builder.setScopes(new String[]{"user-read-private", "playlist-read", "playlist-read-private", "streaming"});
            AuthenticationRequest request = builder.build();
            AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);
        }

 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);

        // Check if result comes from the correct activity
        if (requestCode == REQUEST_CODE) {
            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, intent);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
                AppPreferenceManager.setPreferenceObj(MainActivity.this, "key", response.getAccessToken());
                String t = response.getAccessToken();
                Log.i(TAG, "Token "+ response.getAccessToken());
                playMusic(t);
            }
        }
    }

    public void playMusic(String token){

        Config playerConfig = new Config(this, token, CLIENT_ID);
        Spotify.getPlayer(playerConfig, this, new Player.InitializationObserver() {
            @Override
            public void onInitialized(Player player) {
                mPlayer = player;
                mPlayer.addConnectionStateCallback(MainActivity.this);
                mPlayer.addPlayerNotificationCallback(MainActivity.this);
                mPlayer.play("spotify:user:webvice:playlist:1fpecubMxS2RzkfooZzlrN");
                Log.d("MainActivity", "player started");
            }

            @Override
            public void onError(Throwable throwable) {
                Log.e("MainActivity", "Could not initialize player: " + throwable.getMessage());
            }
        });
    }

**Comment by lepsis3942** [comment]
AuthenticationResponse.Type.TOKEN is a single use token that lasts for as long as you have an active player.  If you want to be able to be able to renew a token request a AuthenticationResponse.Type.CODE which will return an Auth code and a refresh token. You then can use both of those to request a new token when your original token expires. The refreshed token response will give you an "expires_in" field that will let you know how long it's valid. 

https://developer.spotify.com/web-api/authorization-guide/#authorization_code_flow

**Comment by erdtman** [comment]
Correct when using AuthenticationResponse.Type.TOKEN you get a token directly that is valid for one hour, but if you use AuthenticationResponse.Type.CODE you will get a code that can be exchanged for a token (valid for 1 hour) and a refresh-token. the refresh-token  can then be used to get a new tokens to get a long live session.

See #5 and #259 which is on the same subject.
