### ISSUE TITLE
Spotify fails to create/update android media session

### ISSUE THREAD

**Issue by maharamachandran** [spotify/android-sdk#255]
Spotify fails to create/update android media session most of time. OnActiveSessionsChangedListener session list consist of Deezer and Pandora sessions instead Spotify, when Spotify is an active music player.

Also media can be played both in Spotify and another music player at the same time when MediaSessionService couldn't keep track of Spotify music player.

**Comment by immran** [comment]
Hi @maharamachandran , I'm also facing the same issue. You got any solution to solve this?
Thanks

**Comment by d-kunin** [comment]
@maharamachandran is that report for Spotify App or Spotify Android SDK? 

Can you provide repro/test steps?

**Comment by maharamachandran** [comment]
@d-kunin, actually it is for both but I believe the root cause for two issues are same.

First point is specific to Spotify Android SDK or Spotify Remote SDK,
_Spotify fails to create/update android media session most of time. OnActiveSessionsChangedListener session list consist of Deezer and Pandora sessions instead Spotify, when Spotify is an active music player._

**Step to Reproduce:**
Play music in different app via SDK, Android media session list (OnActiveSessionsChangedListner) updates other app session properly, but when Spotify is active it is not getting updated to the MediaSession. 

Media session list will have list of media players which are opened and order by the active session. Spotify doesn't update its current state to Android Media session, so when we try to retrieve active media session it returns some other media player info as active when actually Spotify is an active media player.

Second point is specific to Spotify App
_Media can be played both in Spotify and another music player at the same time._

**Steps to Reproduce:**
Manually play music in multiple apps [Napster, Spotify, Pandora, Soundcloud, Deezer etc., ]. Media can be played in Spotify and Pandora (or any other app) simultaneously.
