### ISSUE TITLE
Spotify app is not playing music 

### ISSUE THREAD

**Issue by ronit12** [spotify/android-sdk#256]
Using spotify sdk spotify player just starts music of spotify, It is not playing music using  Spotify App.

So If i want to play music using spotify app what I need to do?

**Code snippet**

Config playerConfig = new Config(context, token, CLIENT_ID);
        Spotify.getPlayer(playerConfig, context, new Player.InitializationObserver() {
            @Override
            public void onInitialized(Player player) {
                mPlayer = player;
                mPlayer.play(playlist);
                Log.i(TAG, "player started");
            }

            @Override
            public void onError(Throwable throwable) {
                Log.e(TAG, "Could not initialize player: " + throwable.getMessage());
            }
}); 

this code is just playing music.

**Comment by sampurcell93** [comment]
I'm pretty sure playback using the spotify app itself is not supported in this SDK.

**Comment by osharifali** [comment]
This SDK plays music through Android's native media player not through the Spotify app.

**Comment by erdtman** [comment]
Correct the current Android-SDK does not play music from the Spotify App.
