### ISSUE TITLE
Controlling spotify on different device

### ISSUE THREAD

**Issue by Xanore** [spotify/android-sdk#258]
I would like to build an Android app which allows me to control Spotify on a different device. (play, pause, next, prev, volume, etc). This in combination with a device like [gramofon](https://gramofon.com/) 

When looking to the page [Web API: Using Scopes](https://developer.spotify.com/web-api/using-scopes/) it describes "Play music and control playback on your other devices" which is exactly what I want to do. This can only be done by the Android or iOS SDK although I cannot find any documentation about how to do this.

Is this possible?

**Comment by NOlivNeto** [comment]
I think the way it was written leads to misinformation. The scope "streaming" is for allowing your application to play music in Android or iOS, not to "remote control" the playback on other device.

I don't think this is possible for now. Devices like gramofon use [Spotify Connect](https://developer.spotify.com/spotify-connect-hardware-partners/), which is proprietary and have no open APIs.

**Comment by erdtman** [comment]
Correct the scope text is slightly misleading, there is currently no way remote control the Spotify in that way.

**Comment by ericwjr** [comment]
Yeah that's pretty misleading.  Is this still the case?
