### ISSUE TITLE
How to refresh token,,,

### ISSUE THREAD

**Issue by nicejob** [spotify/android-sdk#260]
We can got access_token after user login, but access_token only available in one hour, is there any way to do "refresh token" just like in iOS SDK ?

this confuse me many days ,,,

Thanks a lot !

**Comment by JingweiWang** [comment]
I also have this problem, but do not know how to solve

**Comment by erdtman** [comment]
see #259

**Comment by JingweiWang** [comment]
@erdtman Thank you very much. But we also hope that the token swop functionalety in Android-sdk can be implemented at an early time.

**Comment by d-kunin** [comment]
There is no plans to implement it as a part of the Android SDK.
