### ISSUE TITLE
When Spotify App isn't connect to an account, if I try to connect it via facebook, the app returns error at onActivityResult

### ISSUE THREAD

**Issue by NOlivNeto** [spotify/android-sdk#261]
When I try to login with Facebook in Spotify App through my application expecting it to return my token, the Spotify App returns me an error before it's authenticated. This error occourred on Samsung Galaxy S6 and S7, with Android 6.0.1 installed, but I have reproduced it on several devices.

How to reproduce the error:

1. Spotify app must be logged out
2. My application calls for  `AuthenticationClient.openLoginActivity((Activity) this.context, REQUEST_CODE, request);`
3. Click in "Log in"
4. Click in "Log in with Facebook"
5. Enter the credentials

ExpectedResult: The Spotify app should send to my app the token in onActivityResult
Actual Result: The Spotify App ends processing before it's authenticated and on my Activity's `onActivityResult`i get `ERROR` code with NOT_LOGGED_IN with result message

**Comment by hughrawlinson** [comment]
Thanks for the report! I'll make sure the right team gets this. 🐛

**Comment by d-kunin** [comment]
@NOlivNeto I am right saying that this is an issue while logging in through Spotify Client app that is not logged in itself? Does happen on every device? Does it happen on Facebook login only? 

Thanks for report, btw.

**Comment by NOlivNeto** [comment]
@d-kunin Yes. It happens on every device I tested. It happens only with login through facebook.

**Comment by d-kunin** [comment]
Spotify 6.4 will have fix for that included.

Thanks for reporting this issue, it was an important one.
