### ISSUE TITLE
Error when using Player.play(List<String> uris)

### ISSUE THREAD

**Issue by NOlivNeto** [spotify/android-sdk#262]
This problem is a bit difficult to explain, so I'll try to describe it's scenario:

1. Generate a list of track uris (`uris01`). Let's call the first element of the list `track01Uri` for convenience. 
2. Play this list of tracks via `Player.play(List<String> uris01)`
3. Generate another list of track uris (`uris02`), with different elements, but with `track01Uri` inside this list (but not on the first position). Let's call the first element of the list `track02Uri`.
4. Call `Player.play(List<String> uris02)`

Expected result: The player should play the first element of uris02 (`track02Uri`)
Actual result: The player restarts the playback of `track01Uri`, no matter where on the list it is.

If we remove track01Uri from this list, everything goes fine.
I have debugged and found out that `TRACK_CHANGED` is called with the uri of `track01Uri`, not `track02Uri`.

**Comment by d-kunin** [comment]
` Player.play` is not present in beta20.
