### ISSUE TITLE
Beta 21 - kSpPlaybackNotifyTrackChanged sent when it shouldn't be

### ISSUE THREAD

**Issue by Anders27** [spotify/android-sdk#264]
Using the new Beta 21.

With caching enabled -> playerConfig.useCache(true);
I start a new track, play for a while.
Then stop playback, do nothing for say 5-10 minutes.
Then seek to a new position, say into the middle of the song - seeing playbackCallbackOnSeek as expected
BUT
also receiving a kSpPlaybackNotifyTrackChanged!  (“D/SpotifyPlayerModel” is my log info)
That should not happen since it's the same track.
In the console log I see a "Disk close" log event at the same time which seems to be related to file caching.
Receiving a kSpPlaybackNotifyTrackChanged when track is not changed breaks the promises from the documentation and 
requires "hacks" from my side to get a reliable behaviour.

With playerConfig.useCache(false); it works a expected meaning kSpPlaybackNotifyTrackChanged is received only at track start.

Hm...

("vacuum() requested" must be some leftover from some testing?)

Below is the relevant log info

08-26 07:07:20.933: D/SpotifySDK(9289): vacuum() requested
08-26 07:07:25.934: D/SpotifySDK(9289): vacuum() requested

HERE I SEEK TO A NEW POSITION

08-26 07:08:12.904: I/SpotifySDK(9289): Disk close 3c89494d1eb99f0a0092c6a90e3af8cd58804f7f 103

08-26 07:08:12.907: D/SpotifyPlayerModel(9289): onPlaybackEvent: event kSpPlaybackNotifyMetadataChanged
08-26 07:08:12.907: D/SpotifyPlayerModel(9289): onPlaybackEvent: event kSpPlaybackNotifyMetadataChanged

08-26 07:08:12.961: I/SpotifySDK(9289): playbackCallbackOnSeek (to 179046ms)

08-26 07:08:12.964: D/SpotifyPlayerModel(9289): onPlaybackEvent: event kSpPlaybackNotifyTrackChanged
08-26 07:08:12.966: I/SpotifySDK(9289): Disk close 333413b1c256351886c28ab7921803502aa78a51 103
08-26 07:08:13.008: I/SpotifySDK(9289): playbackCallbackOnSeek (to 1ms)

08-26 07:08:15.933: D/SpotifySDK(9289): vacuum() requested
08-26 07:08:20.934: D/SpotifySDK(9289): vacuum() requested
08-26 07:08:25.934: D/SpotifySDK(9289): vacuum() requested
08-26 07:08:30.934: D/SpotifySDK(9289): vacuum() requested

**Comment by d-kunin** [comment]
@Anders27 thanks, we will take a look.

**Comment by d-kunin** [comment]
Does not happen to me with beta22 or beta21. Could you check again?
