### ISSUE TITLE
how to check whether current user is a premium user

### ISSUE THREAD

**Issue by mmm2006** [spotify/android-sdk#265]
HI,  I want to use spotify sdk in my app.  When i login in with my premium account in my demo app, play is ok.  if i login in with a free account, play will fails. I want to check type of account before playing a music, Can you tell me how to do it?  Is this supported by now?  I am using android sdk:SpotifySdkAndroid-1.0.0-beta12. Please help me about this question. Thanks.

**Comment by sampurcell93** [comment]
Hi, here's a code sample. This is how I do it in my app, after I have obtained a user's access token.

```
import request from 'superagent';

export default function isSpotifyUserPremium({accessToken}) {
  return new Promise((resolve, reject) => {
    request.get(`https://api.spotify.com/v1/me/`)
      .set('Authorization', 'Bearer ' + accessToken)
      .set('Content-Type', 'application/x-www-form-urlencoded')
      .end((err, response) => {
        if (err || !response) {
          resolve({isPremium: false});
        } else {
          resolve({
            isPremium: response.body.product === 'premium'
          });
        }
      })
  });
}
```

**Comment by mmm2006** [comment]
HI, sampurcell93,
Thank you help very much. You mean I should trigger a http access to get account type with token, right?
thanks again.

**Comment by sampurcell93** [comment]
Yep! That's how I do it.

**Comment by andydev2134** [comment]
Hi, mmm2006
Can you please tell me how you handle the login consistency. Mean when i runs the app again after authentication it don't start the song unless i get a message from spotify sdk which is "Login Complete".

**Comment by d-kunin** [comment]
There is no way to detect premium users before login in the mobile SDK. But as @sampurcell93 mentioned, you can use web api. But you will need to login anyway.

In the mobile SDK you will be get an error `com.spotify.sdk.android.player.Error.kSpErrorNeedsPremium` while logging in for free users.

**Comment by mmm2006** [comment]
HI, d-kunin

Are you sure we can get com.spotify.sdk.android.player.Error.kSpErrorNeedsPremium error? In my test, we only get error:The operation requires a Spotify Premium account. This  happen when i try to play a song.

**Comment by mmm2006** [comment]
hi, sampurcell93, i use https://developer.spotify.com/web-api/console/get-users-profile/#complete to check account, I provide user id and a token. But I don't get information about premium. info from web:
{
  "display_name" : null,
  "external_urls" : {
    "spotify" : "https://open.spotify.com/user/firehoo_99"
  },
  "followers" : {
    "href" : null,
    "total" : 0
  },
  "href" : "https://api.spotify.com/v1/users/firehoo_99",
  "id" : "firehoo_99",
  "images" : [ ],
  "type" : "user",
  "uri" : "spotify:user:firehoo_99"
}
Can you tell me what information is missing in my request? Thanks.

**Comment by erdtman** [comment]
use https://developer.spotify.com/web-api/console/get-current-user/#complete

**Comment by mmm2006** [comment]
HI, erdtman, 
thanks very much. You are great.  that's is cool.

**Comment by mmm2006** [comment]
Hi, all
I have a another question. Can I login with a web-api?  I mean just like input a user name and password and get a token from response. So my user can only see my page and not a spotify page. Is there a api?thanks.

**Comment by erdtman** [comment]
No there is no API to exchange a username and password for a token, you have to use the supported oauth flows as detailed here https://developer.spotify.com/web-api/authorization-guide/.
However by using the code grant flow you can lessen the login and authorization to one time for the user.

**Comment by mmm2006** [comment]
Hi, erdtman, 
Thank your help very much firstly. I read this docs from your message.
Can i use Client Credentials Flow to get a token? In this method, we don't need user to authorize access right and that is what i want. Thanks

**Comment by erdtman** [comment]
when using client credentials flow you will not get a token bound to an account so when you send requests to  endpoints under me (https://api.spotify.com/v1/me) the API cannot decide which user to return data for. so no it is not possible to use the Client Credentials Flow for your use case.
