### ISSUE TITLE
Invalid redirect URI

### ISSUE THREAD

**Issue by ahuang13** [spotify/android-sdk#266]
When I try running the [tutorial](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/), the web view dialog that pops up to log in shows an error message `INVALID_CLIENT: Invalid redirect URI`. 

![screenshot_20160830-171055](https://cloud.githubusercontent.com/assets/2015033/18111489/e8bbf08a-6ed4-11e6-8dec-c26d5661703b.png)

I was able to see the login web view initially. However, every run of the app after that showed the error.

I am using the following callback URI `"spotifytutorial://callback"`, which is registered in the My Applications portal and referenced in my app code.

I'm using **Version 1.0.0-beta13** of the SDK.

**Comment by ahuang13** [comment]
The callback URI was not properly saved in the My Applications portal.

**Comment by abechoi** [comment]
If your URI is set to "spotifytutorial://callback", what should you add for the Redirect URI in your dashboard?

**Comment by arirawr** [comment]
You should set it to `spotifytutorial://callback`
