### ISSUE TITLE
Logged In state is not being maintained.

### ISSUE THREAD

**Issue by andydev2134** [spotify/android-sdk#268]
When i first logged in its working fine its taking me to desired next activity. And if I navigate back to the login screen it opens the scopes confirmation screen and if i click on the OK button it tells me that I am already logged in as I am checking the "mPlayer.isLoggedIn()".
But if I close the app and run app again it opens the login screen, but do skip the login credentials window and move forward to the scopes confirmation screen. And when I press okay  on scopes confirmation screen it again log in and SDK returns me the below confirmation message.

SpotifySDK: Login complete

Which means SDK is logging me again, while it should give me the message that i am already logged in.  And it also took a delay before giving me the login complete confirmation. 

I am using this sdk beta21-noconnect-2.18c.

And below is how I am handling the authentication.

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        openLoginWindow();
    }
 public void openLoginWindow(){
        AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID,    AuthenticationResponse.Type.TOKEN,REDIRECT_URI);
        builder.setScopes(new String[]{"user-read-private","streaming"});
        AuthenticationRequest request = builder.build();
        AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);
    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode==REQUEST_CODE){
       final AuthenticationResponse response = AuthenticationClient.getResponse(resultCode,data);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
            Config playerConfig =new Config(this,response.getAccessToken(),CLIENT_ID);
                Spotify.getPlayer(playerConfig, this, new SpotifyPlayer.InitializationObserver() {
                          @Override
                            public void onInitialized(SpotifyPlayer spotifyPlayer) {
                                mPlayer = spotifyPlayer;
                                if(mPlayer.isLoggedIn()) {
                            Toast.makeText(MainActivity.this,"Loggedin",Toast.LENGTH_LONG).show();
                                }
                                System.out.println(response.getAccessToken());
                                mPlayer.addConnectionStateCallback(MainActivity.this);
                                mPlayer.addNotificationCallback(MainActivity.this);
                            }
                            @Override
                            public void onError(Throwable throwable) {
                            }
                        }
            );
            }else{
               Toast.makeText(MainActivity.this,"Authorization Failed",Toast.LENGTH_LONG).show();
            }
        }
    }
    @Override
    public void onLoggedIn() {
    System.out.println("login");
          }
    @Override
    public void onLoggedOut() {
    }
    @Override
    public void onLoginFailed(int i) {
    }

**Comment by d-kunin** [comment]
@andydev2134 could you please report this issue in form of 'step, expected result, actual result'? I cant really understand what problem do you have :(

**Comment by andydev2134** [comment]
okay i will explain it in steps.
step 1: I login first time it works perfectly and songs are being played.
step 2 : I close the app.
step 3: when I run the app again it should maintain the logged in state i think it do maintain the logged in state as it do not show me login screen but skip to the application information dialog where scopes information is shown too.
step 4: If i wont press okay on this screen it wont let me play the songs. Did player stopped working if i close the app and it needs to be logged in again?

**Comment by andydev2134** [comment]
If i am still not able to explain clearly please tell me. Sorry for inconvenience.

**Comment by andydev2134** [comment]
And A question did we need to log in the user again once he have login using Spotify android SDK. Or only once is enough.

**Comment by andydev2134** [comment]
I usually received this 'SpotifySDK: Unknown connection error of type '5' received' code while internet is working fine.

**Comment by d-kunin** [comment]
Since it is an auth flow issue please fill the ticket to the new repo if it is still an issue https://github.com/spotify/android-auth

**Comment by alliejc** [comment]
@andydev2134 I ran into a similar issue.  I resolved it by:
-saving the token and userId to SharedPreferences on login
-clearing them on logout
-checking them in onCreate to see if the user needs to login again

I do have the 'SpotifySDK: Unknown connection error of type '5' received' error showing, but it doesn't seem to be effecting anything as far as I can tell

Hope that helps!
