### ISSUE TITLE
Please include the layout file in the examples folder

### ISSUE THREAD

**Issue by krsnaa** [spotify/android-sdk#269]
Please include the layout file for DemoActivity in the examples folder

**Comment by happyruss** [comment]
Hi, We're eagerly awaiting this ability to grab a fully-operational sdk with a basic ui, and are already excited about its eventual delivery and limitless possibilities upon its arrival, as it will make it easy for any android developer to advance the music.

**Comment by d-kunin** [comment]
Done https://github.com/spotify/android-sdk/tree/master/samples/DemoProject
