### ISSUE TITLE
Will this only work on Android? Do you have a generic playback API?

### ISSUE THREAD

**Issue by shawaj** [spotify/android-sdk#270]
Is there a way to get this SDK working on a different platform - just in a standard Linux app?

Or do you have a generic playback API that will play full songs?

Thanks

**Comment by erdtman** [comment]
This is android only for now.

For playback we have the Android-SDK (this one) and the iOS-SDK. I cannot say if other SDKs will be released in the future to do playback.

**Comment by shawaj** [comment]
Why has libspotify been discontinued if there is no other alternative for
playback on non Android or iOS devices?

This is a very strange move by Spotify?!?
