### ISSUE TITLE
Documentation for beta21-noconnect?

### ISSUE THREAD

**Issue by sampurcell93** [spotify/android-sdk#271]
Hi, I've looked at the DemoActivity, but I'm looking for javadocs for the new beta, similar to what exists for beta12/13. Do these exist anywhere?

**Comment by d-kunin** [comment]
http://spotify.github.io/android-sdk/authentication/
http://spotify.github.io/android-sdk/player/

Or an umbreall page:
https://developer.spotify.com/technologies/spotify-android-sdk/android-sdk-api-reference/

**Comment by YeomansIII** [comment]
@d-kunin Please add these links to the README!
