### ISSUE TITLE
playUri not working proberly

### ISSUE THREAD

**Issue by denzerd** [spotify/android-sdk#272]
Hi,

I'm trying to implement the SDK in my app and I observe a strange behaviour.
The following is my code
`if (requestCode == REQUEST_CODE) {
            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, intent);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
                Config playerConfig = new Config(this, response.getAccessToken(), CLIENT_ID);

                Spotify.getPlayer(playerConfig, this, new SpotifyPlayer.InitializationObserver() {

                    @Override
                    public void onInitialized(SpotifyPlayer spotifyPlayer) {
                        Log.d("TEST","Init baby");
                        mPlayer = spotifyPlayer;
                        mPlayer.addConnectionStateCallback(SpotifyActivity.this);
                        mPlayer.addNotificationCallback(SpotifyActivity.this);
                        mPlayer.playUri(songUri,0,0);
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        Log.e("MainActivity", "Could not initialize player: " + throwable.getMessage());
                    }
                });
            }
        }`
I want to play a song after initialization using the new playUri method. 
Strange is, that it is not working, no song is played except if I put a break point inside of onInitialized. If the code stops once there and I continue, the song is playing fine.

**Edit:**
I forgot I can see this error message in logcat

> 09-14 09:16:39.447 28435-29564/com.testapp.test E/SpotifySDK: Throwing exception, failed SpPlayUri with error code 1 (The operation failed due to an unspecified issue)

Ever heard of that? What to do about it?
I'm using a Xiaomi MI4 with Android KitKat 4.4.4 for testing.

Greetings

**Comment by denzerd** [comment]
Solved it by putting the mPlayer.playUri call into the OnLoggedIn Event of the ConnectionStateCallback.

You should really update your documentation as it's not even close to what has to be done.

**Comment by matuki** [comment]
Same problem here, denzerd's solution worked.

I guess the problem is the beginner's tutorial example does not work anymore (link below) due to this.

https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/
