### ISSUE TITLE
How to know seek completions while music is paused

### ISSUE THREAD

**Issue by tcrondo** [spotify/android-sdk#273]
As of beta21-noconnect, you say seek completions will be notified by `kSpPlaybackEventAudioFlush` but this event seems to be triggered only while music is playing and I can not receive it while music is paused.

In beta13, I could know the playback position after seeking using `Player#getPlaybackState()` asynchronously immediately after `Player#seekTo()` but now the method returns the result synchronously and it does not reflect the playback position after seeking.

Is there any good way to know the seek completions on paused state (or maybe something like `kSpPlaybackEventSeekCompleted`)?

Thanks

**Comment by d-kunin** [comment]
You can use `void seekToPosition(OperationCallback callback, int positionInMs)` setting your own `callback` object. `void onSuccess()` is called when operation is complete.
