### ISSUE TITLE
Player.clearQueue() missing in beta21?

### ISSUE THREAD

**Issue by YeomansIII** [spotify/android-sdk#274]
It seems like, while queueing is still possible, there is now no way to clear the queue of songs on a player.

This becomes extra difficult because beta21 still lacks any documentation even though it has some of the biggest changes in the SDK and was released almost a month ago.

Is there now another way to clear the queue?

**Comment by erdtman** [comment]
The "missing" clearQueue is a result of us updating the underlying layer of the SDK and the clear queue function is removed from there.
To clear the queue you can skip through it of use playURI which will reset the context.
