### ISSUE TITLE
Retrieve spotify:image resources

### ISSUE THREAD

**Issue by mymymario** [spotify/android-sdk#277]
The beta21-noconnect-2.18c release provides Metadata.Track information including albumCoverArtUri - There is no way of retrieving the image (e.g. "spotify:image:XXXXXX")?

Issuing a Web API request with the trackURI kind of mutes the point of having the Track metadata at all because the request would produce a lot of redundant information.

Also AFAIK the Spotify iOS SDK delivers the URLs and not the URIs for cover art.

Cheers,
Mario

**Comment by Meisolsson** [comment]
The URL  for all the images are <code>https://i.scdn.co/image/COVER_ART_ID</code>. The COVER_ART_ID is the URI without "spotify:image:". At least that's how I do it :)

**Comment by mymymario** [comment]
Thanks for the hint. That works. I was just wondering what will happen if Spotify changes the base URL.
I guess I will just have that bit delivered by the backend to make quick changes without rolling out a full App update.

**Comment by d-kunin** [comment]
In beta22 you can use `albumCoverWebUrl` fields directly without adding anything to it.
