### ISSUE TITLE
SpotifyPlayer.Builder  is  missing

### ISSUE THREAD

**Issue by swa00** [spotify/android-sdk#278]
Hi  together,

in Version 1.0.0 (Beta13) i  used  the  builder to  set  the AudioController
`
     

>    Player.Builder b = new  Player.Builder(playerConfig);
        AudioController ac = new AudioController()
        {
          ///  ......
        };
        b.setAudioController(ac);`

What  similar solution is available  in beta21 ?

Thx  a  lot

Steve

**Comment by d-kunin** [comment]
It seems like you still can do
```
        Config playerConfig = new Config(getApplicationContext(), "access-token", CLIENT_ID);
        final SpotifyPlayer.Builder builder = new SpotifyPlayer.Builder(playerConfig);
        builder.build();
```
in beta22.
