### ISSUE TITLE
Miui 8 + Spotify

### ISSUE THREAD

**Issue by Alexey71** [spotify/android-sdk#279]
Hello. When fix?

![screenshot_2016-09-25-12-05-03-604_com miui home](https://cloud.githubusercontent.com/assets/10572914/18814102/a5ea0726-8318-11e6-8552-ee2661d068c7.png)
![screenshot_2016-09-25-12-05-09-350_com miui home](https://cloud.githubusercontent.com/assets/10572914/18814101/a5e8bd76-8318-11e6-9b20-b5b40e60c697.png)

**Comment by erdtman** [comment]
We cannot help you without a better description.

**Comment by Alexey71** [comment]
What?. All miui 8 devices BUG Spotify notification

**Comment by erdtman** [comment]
I is this using the Spotify App or the Android-SDK.
If it is the Spotify App, please visit https://support.spotify.com/ and report the issue.
If this is an issue with the SDK we still need a more detailed explanation of what the expected and actual behavior in combination with logs and best cases code examples.

**Comment by Alexey71** [comment]
Oh sorry)
