### ISSUE TITLE
Spotify app Home screen opened after Authenticating

### ISSUE THREAD

**Issue by LeoKaliazine-Digiflare** [spotify/android-sdk#280]
On some devices (HTC M8) when authenticating while the Spotify app is installed, instead of automatically going back to my app after authenticating/login the Spotify Home screen is opened.
Doesn't seem to occur every time. More often after a token request when a good amount of time (first login of the day?) has passed between these requests.
(Currently using v12 of the sdk, Spotify app on devices is up to date)

Is this a known issue?

**Comment by d-kunin** [comment]
Sorry, but we dont support v12 anymore. Recheck with v22 and reopen with the steps to reproduce so that we can help you.
