### ISSUE TITLE
Is it possible to set a player instance corresponding to the playback state of the native Spotify android app?

### ISSUE THREAD

**Issue by farberjam** [spotify/android-sdk#285]
Hi folks - just wondering if it's possible to call getMetadata() and receive the track and context URI for the song currently playing on my android device.  A quick scan of the docs has me thinking that it's not the case presently, but I was thinking the qualifier "noconnect" in the present release suggests to me that it might be an option down the road.  

If this is the case, would such a player instance be able to change the playback state in the official app or would such calls affect a separate android process?

Best wishes and many thanks!

**Comment by d-kunin** [comment]
No, it is not possible. 

But you can listen to broadcasts http://stackoverflow.com/questions/17236358/how-is-it-possible-to-know-whats-spotify-is-playing-from-an-external-android-ap

The downside is that the broadcasts must be turned on in the Spotify App
