### ISSUE TITLE
Login question Beta22

### ISSUE THREAD

**Issue by swa00** [spotify/android-sdk#287]
Hi  Guys

at first :  Thank you very much for the great update , it seems to be more stable :-)

Coming  from Beta13 there must be a bug in Beta22&23 while login.

If the account was allready registered (first Account login) i allways get a "confirmation box"

**"Connect xxxapp with your spotify-Account. xxxApp can get these spotify account data"**
(Translated from german)

during **each** login..... 

This  box  has only to quit with ok.. 

EDIT  -  This  is  also in Beta23 and  with the  DemoActivity of the  SDK.
i tried  it  with  three ( ! )  different  packages and USER_ID's
i  revoked  also the  access  on the  "MyApplication"-Page and paired  them again .

Pls  fix  it to ship out the  "better" Spotify :-) 

Thx  a lot
Steve

**Comment by swa00** [comment]
# PSEUDO Solution . Mix player-Beta23 with the Auth from Beta13 until Beta XX is avaliable

**Comment by d-kunin** [comment]
We will take a look, thanks for the report.

**Comment by michaelrhughes** [comment]
Any updates on this ticket?

**Comment by d-kunin** [comment]
Sorry for the late reply on this, the issue were fixed in standalone auth library https://github.com/spotify/android-auth. Please get the update from there.
