### ISSUE TITLE
Non-premium user accounts - error handling

### ISSUE THREAD

**Issue by k-misztal** [spotify/android-sdk#292]
## Description
When I login to Spotify using non-premium account according to documentation login should fail. 
First of all it doesn't fail, I obtain access token, but I am not able to start playback. I got an error `kSpErrorFailed`. The problem is that I got the same error for other types of errors (like no internet), so I cannot distinguish between case when there is an playback error, and when user does not have premium account. 

Version: `beta23-noconnect-2.20b`

### Expected behaviour
Login should fail with some additional information like `user_with_basic_account`, or if login passes I should get an error while trying to start playback. But it **shouldn't** be `kSpErrorFailed`! I'd expect something like `kSpBasicAccount`.

**Comment by erdtman** [comment]
So the documentation is referring to the requirement of premium fro streaming in the mobile SDKs to get the access token does not require that. the reason for this is that you can get access tokens for a whole set of other features (web-api) that does not require premium.
It is unfortunate that you get the same error, our recommendation is that you make a request to the web-api me endpoint to get the account type to display appropriate error and actions to resolve the issue e.g. register for a premium account.
see https://developer.spotify.com/web-api/console/get-users-profile/

**Comment by k-misztal** [comment]
You've got a point, that I should be able to log in using `auth` library, to get a token for different purposes. But `player` and `auth` are separate libraries, and even if `auth` gives me a token, calling `Spotify.getPlayer()`, should fail if a logged user does not have premium account. 

Moreover, you even have got it in your `README.md` file, I quote:

> This library can play music from Spotify after the user logs in with the access token. **Only Premium Spotify users will be able to log in and play music with this library..**

Which clearly says that you should not be able to initialize player with token correspondent to non-premium account. I think you should implement it. 


About your idea to connect to the WEB-API - right now this is the only option, but this should be somehow implemented in SDK. If SDK does not support playback for non-premium accounts it definitely should inform me *somehow* that logged user does not have premium account. Correct me if I'm wrong.
