### ISSUE TITLE
Login not returning access code

### ISSUE THREAD

**Issue by chnt-gomez** [spotify/android-sdk#293]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
Scenario: Android device has installed Spotify app and the user has loged in at least once.
My own application request a login using the Spotify SDK and asks for an request code instead of an access token
The spotify sdk login is not returning the request code

### Versions
Android Marsmellow
Spotify Version 6.2.0.1028

### Severity
Cathastrophic

## Steps to Reproduce
1. Have Spotify App installed
2. Login using the Spotify app
3. Try to request a request code using the following code on a different app.

```
AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(AppConstant.CLIENT_ID,
                AuthenticationResponse.Type.CODE,
                AppConstant.REDIRECT_URI);
        builder.setScopes(new String[]{"user-read-private", "streaming","user-top-read",
                "playlist-modify-public", "playlist-modify-private", "user-library-read", "playlist-read-private"});
        AuthenticationRequest request = builder.build();
        Intent intent = AuthenticationClient.createLoginActivityIntent(getActivity(), request);
        startActivityForResult(intent, AppConstant.REQUEST_CODE);
```

### Actual behaviour
The response is not retirning an request Code

### Expected behaviour
I requested an access code and I need to receive one. The flow works well when Spotify App is not installed on the device

## Logs
Please include any relevant log output that might assist in tracking down the problem.

**Comment by chnt-gomez** [comment]
> access

**Comment by d-kunin** [comment]
@chnt-gomez what's up?
