### ISSUE TITLE
PLAYLIST SORT BY DATE ADDED - REAL TIME CONNECT TO FRIENDS

### ISSUE THREAD

**Issue by joshbhill123** [spotify/android-sdk#296]
I am writing to propose new features for Spotify on a mobile device either IOS or Android.

Firstly, you should have the ability to sort songs within playlists by date added as it is frustrating constantly scrolling down to listen to my latest songs on a playlist on a mobile device. I acknowledge this feature is available on desktop version of Spotify.

Secondly, there should be a feature that enables your profile to connect to friends and visa versa so others can "piggyback" each other live streaming music.

Good musiking!!!

**Comment by swa00** [comment]
Wrong question at this place.

This is the place for  **DEVELOPER SDK** , not for the  Spotify App
 ...

**Comment by joshbhill123** [comment]
please send link

**Comment by erdtman** [comment]
As mentioned above this is the issue tracker for the Spotify Android-SDK and not the Spotify app. For questions and requests on the Spotify app please contact Spotify support https://support.spotify.com
