### ISSUE TITLE
bate13-Call the mPlayer.skipToPrevious() problem when playing first song 

### ISSUE THREAD

**Issue by JingweiWang** [spotify/android-sdk#297]
When I get a track list, playing the first song, I want to use `mPlayer.skipToPrevious()` to play last song in my list. 
I already set `mPlayer.setRepeat(true);`

In order to achieve a list of loops, how to achieve？ Thanks

tips: I use `mPlayer.play(List<String> trackUris)`.

**Comment by swa00** [comment]
Have you tried Beta23 ??
