### ISSUE TITLE
beta23-How can mPlayer.play(List<String> trackUris)?

### ISSUE THREAD

**Issue by JingweiWang** [spotify/android-sdk#298]
Thanks.

I found the function `SpotifyPlayer.nativePlayTrackList(java.lang.String[], int, int)` is pravite. 
I want to ues Reflect, but may be not yet implemented the native c.

```
10-10 15:34:22.610 E/art: No implementation found for int com.spotify.sdk.android.player.SpotifyPlayer.nativePlayTrackList(java.lang.String[], int, int) (tried Java_com_spotify_sdk_android_player_SpotifyPlayer_nativePlayTrackList and Java_com_spotify_sdk_android_player_SpotifyPlayer_nativePlayTrackList___3Ljava_lang_String_2II)
```

So can you quickly achieve this function?
Especially I will thank you for your company.

**Comment by erdtman** [comment]
The functions that plays a set of URIs has been removed, please use playURI with appropreate context.
If you have an arbitrary list of tracks use the queue to mimic the old behavior.
