### ISSUE TITLE
Some tracks throws kSpErrorFailed at the end of playback

### ISSUE THREAD

**Issue by jamestut** [spotify/android-sdk#299]
## Description
Some tracks like "6baDhElHBV8vvGzzxvffWq" can play correctly, but at the end of each track, just after  onPlaybackEvent fired with value kSpPlaybackNotifyTrackDelivered, the library fires onPlaybackError with value kSpErrorFailed. The logcat also prints "E/SpotifySDKNative: Unknown connection error of type '3' received"

### Versions
Android SDK version beta22-noconnect-2.20b
Spotify app not installed
Android OS version 6.0.1 on x86 AVD (Android SDK)

### Severity
Major

## Steps to Reproduce
1. initialize SpotifyPlayer
2. use custom AudioController
3. addNotificationCallback, with onPlaybackError implemented.
4. play the affected track ( e.g. spotify:track:6baDhElHBV8vvGzzxvffWq )
5. cut the internet (e.g. airplane mode), before the track completes buffering.
6. replay the track.
7. after the song ends, just after onPlaybackEvent fired with value kSpPlaybackNotifyTrackDelivered, the error happened.

### Actual behaviour
onPlaybackError with value kSpErrorFailed fired after the affected track played successfully.

### Expected behaviour
onPlaybackError should not be fired at all.

**Comment by d-kunin** [comment]
It seems to correct behavior, since you are offline.
