### ISSUE TITLE
Use Error instead of int in ConnectionStateCallback#onLoginFailed(int i)

### ISSUE THREAD

**Issue by ckoessler** [spotify/android-sdk#300]
## Description

The `onLoginFailed(int i)` callback returns an `int` instead of returning an `Error`
### Versions

spotify-player-beta23-noconnect-2.20b
### Severity

Minor

**Comment by tejasna** [comment]
Got this by looking into the spotify sdk. May-help!
  UNKNOWN(-1),
  kSpErrorOk(0),
  kSpErrorFailed(1),
  kSpErrorInitFailed(2),
  kSpErrorWrongAPIVersion(3),
  kSpErrorNullArgument(4),
  kSpErrorInvalidArgument(5),
  kSpErrorUninitialized(6),
  kSpErrorAlreadyInitialized(7),
  kSpErrorLoginBadCredentials(8),
  kSpErrorNeedsPremium(9),
  kSpErrorTravelRestriction(10),
  kSpErrorApplicationBanned(11),
  kSpErrorGeneralLoginError(12),
  kSpErrorUnsupported(13),
  kSpErrorNotActiveDevice(14),
  kSpErrorAPIRateLimited(15),
  kSpErrorPlaybackErrorStart(1000),
