### ISSUE TITLE
Player pause and resume methods question

### ISSUE THREAD

**Issue by dhuang89** [spotify/android-sdk#301]
Hi, I'm currently trying to use this Spotify API as part of my Android app. I'm using the beta23 version. 

I was able to successfully implement the player following the tutorial, and I can hear the song play when I login to my app. However, I can't seem to figure out how to pause/resume the song. The API has these methods that take in a parameter called Player.OperationCallback callback. I don't know what this is or how to get it, and I can't find any examples online. Most of the code online is from previous versions when the pause/resume functions didn't take in a parameter. Can someone explain to me how to implement these methods? I realize the answer is probably very simple. Thanks in advance!

**Comment by erdtman** [comment]
Please have a look in the demo project here
https://github.com/spotify/android-sdk/blob/master/samples/DemoProject/src/main/java/com/spotify/sdk/demo/DemoActivity.java#L421

and here for the implementation of the callback interface
https://github.com/spotify/android-sdk/blob/master/samples/DemoProject/src/main/java/com/spotify/sdk/demo/DemoActivity.java#L168

**Comment by dhuang89** [comment]
Hey erdtman, 

Thanks for the links, those seem very helpful. I added the mOperationCallback, but when I attempt to pause the song, I just get the notification that says "Unfortunately, your-app has stopped." Any ideas on where I could be going wrong? Thanks!

**Comment by dhuang89** [comment]
I fixed it by adding additional things, such as mCurrentPlaybackState. It now works well, thanks again!
