### ISSUE TITLE
openResource() open() No such file or directory

### ISSUE THREAD

**Issue by ryandt** [spotify/android-sdk#303]
## Description
When initiating playback on a song using the `SpotifyPlayer`, the following error is logged to the console twice:
```
E/SpotifySDKNative: openResource() open() No such file or directory
E/SpotifySDKNative: openResource() open() No such file or directory
```

### Versions
Android SDK version: 25
Spotify app version: 23
Android OS version: 7.1

### Severity
Minor

## Steps to Reproduce
1. Authenticate with Spotify to receive a valid access token.
2. Play a song via `spotifyPlayer.playUri(uri)`. The error appears to trigger exclusively on the first play of a song. Subsequent plays for the same song do not trigger the error. It sounds like it might be related to a failed cache fetch.

### Actual behaviour
The song plays normally, but a "No such file or directory" error is logged to the console.

### Expected behaviour
The song plays without error.

**Comment by jenzz** [comment]
I'm seeing the same error using the latest SDK: **beta23-noconnect-2.20b**.

**Comment by maxwen** [comment]
Nevertheless it does not seem to cause any harm - so its more cosmetic

**Comment by swa00** [comment]
> Nevertheless it does not seem to cause any harm - so its more cosmetic

right -  more important  is the "hopefully  very soon" working version
