### ISSUE TITLE
Stale playback position after seeking player and resuming playback

### ISSUE THREAD

**Issue by ryandt** [spotify/android-sdk#306]
## Description
When seeking the player while playback is paused and subsequently retrieving the playback position immediately after resuming playback, the retrieved playback position does not match the "seek to" position from the seek request.

### Versions
Android SDK version: 25
Spotify SDK version: 23
Android OS version: 7.1

### Severity
Medium

## Steps to Reproduce
1. Play a song by calling `spotifyPlayer.playUri(...)`.
2. Pause the song at any time by calling `spotifyPlayer.pause(..)`.
3. Seek to a new position by calling `spotifyPlayer.seekToPosition(..., newPosition)` while the player is still in a paused state.
4. Resume playback by calling `spotifyPlayer.resume(...)`.
5. Get the current playback position by calling `spotifyPlayer.getPlaybackState().positionMs`.

### Actual behaviour
The `PlaybackState`'s `positionMs` retrieved in step 5 is the playback position from when the song was paused in step 2.

### Expected behaviour
The `positionMs` value is the position that was seeked to, `newPosition`, in step 3.

## Description Update
It looks that this issue can be simplified a bit. I can reproduce the issue anytime I retrieve the playback position right after a seek regardless of whether I paused or resumed playback. For example: 
```
spotifyPlayer.seekToPosition(new Player.OperationCallback() {
    @Override
    public void onSuccess() {
        long position = 0;
        PlaybackState state = spotifyPlayer.getPlaybackState();
        if (state != null) {
            position = state.positionMs;
        }
    }

    @Override
    public void onError(Error error) {

    }
}, (int) newPosition);
```
The value of `position` is the playback position of the song right before the seek request. `position != newPosition`.

**Comment by d-kunin** [comment]
Could you check with version 24?

**Comment by ryandt** [comment]
@d-kunin It looks like the `PlaybackState` update frequency change introduced in version 24 fixed this issue. Cheers!

**Comment by d-kunin** [comment]
@ryandt great! Closing it then.
