### ISSUE TITLE
Spotify Login Issue on API <=19 

### ISSUE THREAD

**Issue by gpowell13** [spotify/android-sdk#313]
### Versions
Android SDK version: 25.0.1
Spotify app version: 1.0.0 (com.spotify.sdk:spotify-android-auth-1.0.0@aar)
Android OS version: 19

The Spotify auth api should be updated for API support API 19 and below. The issue is in the sdk tutorial you say to add
```
<activity
            android:name="com.spotify.sdk.android.authentication.LoginActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
```
to the AndroidManifest.xml and then use 
`AuthenticationClient.openLoginActivity(this, RequestCode.SPOTIFY_AUTH_REQUEST.getCode(), request);`
to login. 

In pre-Lollipop versions of Android the startActivityUncheckedLocked method behaves in a way where you can't call startActivityForResult() with an activity that has the launch mode "singleTask" or "singleInstance" which the LoginActivity has. So this results in a RESULT_CANCELLED to be returned to the calling activity. Shown here:
http://stackoverflow.com/questions/8960072/onactivityresult-with-launchmode-singletask

So to bypass this I have to override the Spotify LoginActivity's launchMode to either "singleTop" or "standard" like so:

```
<activity
            android:name="com.spotify.sdk.android.authentication.LoginActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:launchMode="singleTop"
            tools:replace="android:launchMode"
            />
```

**Comment by wolkenschieber** [comment]
I reported a similar issue to `spotify/android-auth`: [Can't authenticate on device running API 19 #11](https://github.com/spotify/android-auth/issues/11)
