### ISSUE TITLE
The Spotify login dialog is blank

### ISSUE THREAD

**Issue by edwardharks** [spotify/android-sdk#315]
When logging into Spotify using the webview dialog, the dialog is blank on some devices. 

![spotifylogin](https://cloud.githubusercontent.com/assets/1922349/20840907/c3a9e1c0-b8a9-11e6-8454-8dc93cbc14af.png)

Observed on Android 5.0 and 7.0
LG G3, Nexus 6, Nexus 5X
Spotify sdk version: beta23

This bug can be reproduced using the demo app

**Comment by erdtman** [comment]
Auth part of the library has moved to https://github.com/spotify/android-auth could you please verify if the problem is present there too?

**Comment by sid9102** [comment]
+1. Building the demo app as instructed results in a blank screen on my Nexus 6P, but it works fine on the emulated 5X.
