### ISSUE TITLE
After Login Same Authentication Web view pop-ups coming  twice.

### ISSUE THREAD

**Issue by Lokesh-speakmusic** [spotify/android-sdk#317]
Hi Team,

I am facing problems with Spotify Authentication, 

Problem details 

**Description**

Problem Is getting Login Authentication Pop up twice.
.

**Versions**

Android SDK version: 25.0.0
Spotify app version : beta23 sdk
Android OS version. All version Above 4.2.2

**Severity**

Major

**Steps to Reproduce**

1. Put The Credentials, click on Login.
2. Get The Web view pop up, click on OK button .
3. Again i get same pop up. Then Click on OK button 
4. This is the problem of Same pop up getting twice: One for get Auth token and other for Refresh Token.
So is it Correct getting Pop up  twice??

**Describe what happens when you perform the steps above.**

Getting Web View Pop of Authentication  twice.

**Expected behaviour**

Should the pop-up come once or twice?

Thanks ,

Lokesh

**Comment by Meisolsson** [comment]
This belongs in https://github.com/spotify/android-auth
