### ISSUE TITLE
Shuffle first song in a playlist

### ISSUE THREAD

**Issue by Meisolsson** [spotify/android-sdk#32]
For the moment the playlists can be played but the first song is always the same, even if I tell it to shuffle.

**Comment by d-kunin** [comment]
Please feel free to reopen if it is still an issue in beta 21.

**Comment by Meisolsson** [comment]
The bug is still in beta 21. I tried to start the shuffle before <code>SpotifyPlayer.play</code> and get some error about not being the active device.

When I put it after the  <code>SpotifyPlayer.play</code> it always plays the first song from the playlist.

**Comment by mymymario** [comment]
It is still an issue with player 24-nconnect-2.20b - and the aforementioned workaround also fails because the "current device is not the active device". Any news on this?
