### ISSUE TITLE
is it possible to refresh token only without showing the login activity ?

### ISSUE THREAD

**Issue by elirangoshen** [spotify/android-sdk#323]
## Description
Im using the sdk, login working.
but via sdk i see that i can login by show the login window.
but what happens when token is expiring// is there a method to call that only refresh the token without showing the window ?

### Versions
all

### Severity
Minor

### Expected behaviour
Id like to use some method that refresh the token by using the refreshToken that i should get from the web api authentication

**Comment by erdtman** [comment]
To start with the auth functionality has been moved to https://github.com/spotify/android-auth

Secondly, yes if you use the code grant flow as described [here](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow) you can get a new token without any user-interaction.

**Comment by elirangoshen** [comment]
In the sample there is 2 different calls to get code or token, and in real app its should pop up the login activity once.  and i noticed that i should get refresh code with the token, in the web api, and then i can use this code when i want to refresh. 
but in library i didn't see any code that comes with the token, so i don't know how to refresh it.
The flow i try to do is to a get token and show the login activity, and if there is need to refresh, so make a call without opening the login again. but for this call i need to send a code and it doesn't seems that the library getting one with the token, as it shows in the grant flow.
