### ISSUE TITLE
No log out methods

### ISSUE THREAD

**Issue by Contract16** [spotify/android-sdk#33]
There are currently no methods to log out of spotify at the moment. This causes issues attempting to logon after cancelling the first attempt.

This issue does not seem to happen if the user already has the Spotify app installed.

Is there any ETA on full login/out functionality?

**Comment by kaaes** [comment]
This issue should now be fixed. The new version (1.0.0-beta8) contains both the methods to log out from the player and to log out from the Spotify account.
