### ISSUE TITLE
Gradle Build Failing - Could Not Expand ZIP

### ISSUE THREAD

**Issue by GarryMcKee** [spotify/android-sdk#337]
## Description
When attempting to build the project after importing the .aar files and setting up gradle dependancies. Build fails either error: Could Not Expand ZIP '<directory of .aar file(s)>'

### Versions
Android SDK version: 25
Build Tools: 25.0.2
Android Studio version: 2.2.3
Gradle version: 2.2.3
Spotify app version (if native SSO flow is involved): n/a
Android OS version : n/a

### Severity
Catastrophic

## Steps to Reproduce
1. Create a new project in Android Studio.
2. Follow instructions as per Spotify Android SDK beginners guide with latest versions of .aar files

### Actual behaviour
Build fails with error: Could Not Expand ZIP '<directory of .aar file(s)>'

### Expected behaviour
Build should complete successfully

### Notes
Have already looked the problem at a wider gradle error level and come across read/write access issues and new version of gradle breaking. However I have already tried using an earlier gradle version and manually giving rw access to Android Studio to know avail. Would be very grateful to see if anyone has had this specific issue!

## Logs
Error:Execution failed for task ':app:prepareComSpotifySdkSpotifyAndroidAuth100Library'.
> Could not expand ZIP '/Users/garrymckee/Documents/Development/Spop/app/libs/spotify-android-auth-1.0.0.aar'.

Thanks in advance for any thoughts folks!

**Comment by 3flex** [comment]
That error is related to the Spotify Android Auth project
> Could not expand ZIP '/Users/garrymckee/Documents/Development/Spop/app/libs/spotify-**android-auth**-1.0.0.aar'.

Might be better to open the issue at https://github.com/spotify/android-auth instead?

**Comment by abstream** [comment]
I have the same issue. IMHO it is not related to spotify but it is a general issue....people are reporting it for different jar or aar files...for some reason the new gradle file cannot expand the archives into the corresponding folders.Here is my error:

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not expand ZIP 'C:\Users\abstream\.android\build-cache\45cead86d1e85b76fd55cbc8d24748549af2fdeb\output\jars\classes.jar'.

**Comment by abstream** [comment]
I ment new graddle versions , for example it will work fine with 2.10 , so maybe it is a graddle issue?

**Comment by cw1427** [comment]
I met the same error when using gradle 2.14.1 and with a dependencies compile  a aar lib
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not expand ZIP '/ path to this jar /jars/classes.jar'.
Could anyone know how to deal with it?

**Comment by Freedomhxb** [comment]
@abstream @cw1427 
you can look this 
http://blog.csdn.net/dota_coco/article/details/78958456

**Comment by tai** [comment]
Looks like an issue related to these?
- [Incremental Java compilation fails in some cases](https://github.com/gradle/gradle/issues/3935)
- [Java 8 type-use annotation on local variable in a method overriding a parameterized one breaks ClassReader](https://gitlab.ow2.org/asm/asm/issues/317789)

**Comment by hughrawlinson** [comment]
Hi! This looks like an issue related to Gradle, rather than to the SDK Distribution, so I'll close this issue.

**Comment by maracuja-juice** [comment]
I never used these aar files. You only need to set in the build.gradle file that you use the library
