### ISSUE TITLE
No more slot available for my app

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/android-sdk#339]
## Description
On my developer account I am not able to save my changes. 
I'm trying to register one more Android Package Name and SHA1 Fingerprint. It's well added in list and displayed but nothing happened when I click on the save button.

### Severity
Minor

## Steps to Reproduce
1. Create an app in your developer portal 
2. Add 64 Android Package Names and SHA1
3. Try to add one more

### Actual behaviour
You will not be able to save your changes.

Thank you for your help!

**Comment by hughrawlinson** [comment]
Hey @greencoppercompany - at the moment, the limit is 30 apps per user and 64 android package names per app. I'll talk to the team about seeing whether or not this is open for change, but in the mean time I'd suggest that you remove any android package names you're not using. We should certainly improve the error message on the developer console for when people hit this limit.

**Comment by greencoppercompany** [comment]
Hi @hughrawlinson 

Thanks for your reply and suggestions. As said, we already reached the limit and we'll need to add many more in the coming weeks/months. We're doing many music festivals apps and each one integrate the Spotify SDK. We will have hundreds of apps for 2017.

We started to recycle a bit old package names but the limit is approaching very fast. Thanks a lot for taking time to discuss this subject with your team. We looking forward for news!

Best.
Greencopper team.

**Comment by hughrawlinson** [comment]
@greencoppercompany do all of your apps need to be on the same client? We limit to 30 clients, with 64 redirect uris each, which amounts to 1920 redirect uris. We feel this is more than adequate, if an organisation needs more than this (or even more than the 64 for one client id) that we should be in direct contact. Have you considered applying for a commercial partnership as mentioned in the developer terms of use?

I'm going to close this issue as we consider the current limits to be good defaults, and anyone falling outside of the limits should contact us for us to consider making an exception.
