### ISSUE TITLE
Developed Android-app simulating Spotify Connect for AirPlay-devices -> seeking contact at Spotify

### ISSUE THREAD

**Issue by funtax** [spotify/android-sdk#345]
Hi there,
 
I'm seeking for a real human at Spotify (dev, legal) to talk about this:
 
I have developed an Android-app (finished, used by several users) that simulates a "Spotify Connect"-enabled device for each available AirPlay-receiver (Airport Express, Apple TV etc.).
This has been done by "transcoding" a "Spotify Connect reverse-engineering project" to the Android-platform.
No code/sdk of Spotify is involved, no app-key used, no user-data requested.. it just works like "Spotify Connect for AirPlay" and of course requires a Premium subscription.
 
I will comply with Spotify's Developer Terms of Use, but as the app doesn't use any official API/code from Spotify, this might be a bit more complex.

Submitting the form for _Hardware Partners_ resulted in a generic message
 
Additionally, maybe Spotify supports this project to allow Android-users streaming Spotify to AirPlay.
This would strengthen Spotify's position on Android-devices for users with AirPlay-receivers.
 
Can you please share any real human's contact address?
 
Thanks in advance,
Martin L.

**Comment by hughrawlinson** [comment]
Hey @funtax - if you want to become a partner of Spotify, you'll have to follow our Hardware Partners process. This is the process that internal teams use to organise and prioritise requests for commercial integrations. Due to the large number of applications, the process can be slow at times, but the team in charge will get back to you ASAP.

**Comment by funtax** [comment]
Hey @hughrawlinson , thanks for your feedback. The application has always been answered via a standard "we receive a lot of applications.."-template. I'm not sure the the team even read the content of the application. But it seems I got contact to Spotify via support@spotify.com now. 

If you could help me in any way, please contact me and I'll send you the link to the Android-app on the market.
