### ISSUE TITLE
Error:Failed to resolve: com.spotify.sdk:spotify-player-24-noconnect-2.20b

### ISSUE THREAD

**Issue by niteshverma09** [spotify/android-sdk#357]
I am using spotify player library like 
`compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'` 
with gradle version 2.3.0 and compileSdkVersion 24. 

I have also added folders of player and auth libraries in my app/libs directory. can anybody check with same configuration?

**Comment by ZinoKader** [comment]
You closed this issue, so I'm assuming you solved it. I'm having the same problem so I'd be delighted if you could let me know how you solved it.
