### ISSUE TITLE
Control Spotify Connect

### ISSUE THREAD

**Issue by jfjallid** [spotify/android-sdk#358]
Are there any way to control the Spotify Connect feature through the sdk? I've been searching for it but have not found anything yet. If it's not available right now it would be nice if it was added for use-cases such as transfering playback to a Spotify Connect enabled speaker when entering a specific room etc.

**Comment by arirawr** [comment]
Hello! What you're looking for are the Connect endpoints: https://developer.spotify.com/news-stories/2017/04/10/new-endpoints-beta-web-api-connect/. You can authenticate using the Android Authentication library, then call the Web API endpoints.
