### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by kabouzeid** [spotify/android-sdk#361]

**Comment by aslhdyt** [comment]
whats this?

**Comment by seahorsepip** [comment]
This issue exists already: https://github.com/spotify/android-sdk/issues/2

But was closed for the following reason:

> The offline feature is more of a legal than technical problem and we don't see when it could be solved at the moment. We have to keep streaming :)

Personally I implemented offline support by converting the raw pcm stream into audio files but as far I know this is against the Spotify developer agreement so should never be implemented in apps that aren't for personal use.

**Comment by arirawr** [comment]
Hi @kabouzeid  - this is not available in the Android SDK. However, you can take a look at the new Android App Remote SDK, which allows remote control of playback in the Spotify app, which does offer this functionality: https://beta.developer.spotify.com/documentation/android-app-remote/
