### ISSUE TITLE
Status of the SDK

### ISSUE THREAD

**Issue by noties** [spotify/android-sdk#365]
Hello

I wanted to ask what is the status of this SDK? When the release is planned? We have a world known DJ with 12 millions listeners as a client and wanted to make sure that it is safe to proceed with adding this SDK to our application.

**Comment by hughrawlinson** [comment]
Hi @noties,

This SDK is in beta, and releases will likely continue. It sounds to me though like you're hoping to use the SDK for commercial purposes, which is precluded by our [developer terms of use](https://developer.spotify.com/developer-terms-of-use/). I'd strongly recommend that you thoroughly understand this document, ideally with the guidance of your own legal counsel, before continuing.
