### ISSUE TITLE
Maybe not the best place to ask this question

### ISSUE THREAD

**Issue by diamant254** [spotify/android-sdk#373]
Hi!
I have just started to program in android studio and want to make a app for my training class that i have. I have made a protype program in VB.NET there i control spotify functions, like play and pause. And now i want to make an app for it instead, but don't really know if this SDK works for what i want. So therefore i kindly asking this question, How do i control spotify's play and pause function?

**Comment by SoulEater45** [comment]
https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/
Here is a nice example of how to make the code work. The player can play and pause with the Player.resume or Player.playuri and Player.pause, but I haven't fiddled much with those, bcs I am still stuck on getting the audio session id from the player. But playing songs works without problems for me with the example code!

Hope it helps and I also don't know where such questions should be asked...

**Comment by arirawr** [comment]
Hey @diamant254 - you can play and pause (and similar functions) in the Spotify.Player class: https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/SpotifyPlayer.html

If you need specific programming help, I recommend asking on StackOverflow and tagging your question with `spotify`. Good luck!
