### ISSUE TITLE
Album Art?

### ISSUE THREAD

**Issue by limeblack** [spotify/android-sdk#381]
Is there a possibility to add the functionality to send/receive album art for the current song?
I may have missed something, but couldn't find it.  [Reading this page](https://developer.spotify.com/technologies/spotify-android-sdk/android-media-notifications/)

So I believe setLargeIcon and setSmallIcon under the Notification class let you potentially set/access the image but it is restricted to a certain size so it is coming out to be really blurry.

**Comment by arirawr** [comment]
Hi @limeblack - you can find the album art URL in the `Metadata.Track` object as `albumCoverWebUrl`. Documentation here: https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/Metadata.Track.html
