### ISSUE TITLE
Other/cross-platform SDKs?

### ISSUE THREAD

**Issue by Reyth3** [spotify/android-sdk#383]
Is there anything more... versitile than the iOS and Android SDKs? Something cross-platform, that is available on a wider scale than just the mobile platforms?

Is any such SDK available? If not, are there any plans for that?

**Comment by 3ammari** [comment]
Not anymore ,libspotify was what you were looking for but it is discontinued

**Comment by arirawr** [comment]
Hi @Reyth3 - the heart and soul of the Spotify Platform offering is the [Spotify Web API](https://developer.spotify.com/web-api/). The mobile SDKs wrap much of the functionality.

Through the Web API, you can get metadata, manage playlists and user library, get detailed audio features and analysis, control Spotify Connect, and much much more (and we're always releasing new functionality!). Don't be fooled by the name - you can use the API on any platform that can make HTTP requests. There are also [many community-built libraries](https://developer.spotify.com/web-api/code-examples/#libraries) which make working with the API in different languages and platforms even easier.

If you need help integrating the API, reach out to us on the [issue tracker](https://github.com/spotify/web-api) or on [Twitter](https://twitter.com/SpotifyPlatform).

**Comment by Reyth3** [comment]
Hi,

I see what you mean @arirawr. Still, that's just the *web* API. It doesn't give an option to stream music directly to the device.

**Comment by arirawr** [comment]
That's correct - the Spotify Connect API does allow you to control playback which works for a variety of playback use cases, but unfortunately we only offer currently offer playback in the mobile SDKs.
