### ISSUE TITLE
Connect the device from another

### ISSUE THREAD

**Issue by baptiste-mnh** [spotify/android-sdk#385]
Hi,
I want to create a Home Station which will be able to play music from spotify (in the same way as Alexa).

The problem is that my Home Station does not include a screen, so it is necessary that the user uses a smartphone to connect the Home  #Station to Spotify.
But the connection is via a WebView, and I have found no way to connect in a different way.

Is there a way to make the connection?
Thanks.

**Comment by seahorsepip** [comment]
You can retrieve the token using the Spotify Web API instead of the Android SDK on another device and then send it from that device to the Home Station.

I did something similar with my Android Wear app since Android Wear doesn't support Web Views.

**Comment by baptiste-mnh** [comment]
I made a partership with Spotify so I have now access to the eSDK.
