### ISSUE TITLE
Audio stream type.

### ISSUE THREAD

**Issue by dljones79** [spotify/android-sdk#386]
## Description
It would be great to have the ability to set the audio stream type for the Spotify player.

### Severity
Major

## Steps to Reproduce
Not a bug, just a feature request.  

### Actual behavior
Cannot set the audio stream type for the player.

### Expected behavior
Need to be able to set the audio stream type for the player.

**Comment by arirawr** [comment]
Hi @dljones79 - thanks for the request. We agree that this would be nice to have, but we unfortunately do not plan to implement it in the Android SDK.
