### ISSUE TITLE
I am not able to figure out that, how can I get aar files from zip files? please guide

### ISSUE THREAD

**Issue by hiranandanisonal** [spotify/android-sdk#388]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
A concise description of what the problem is.

### Versions
Android SDK version
Spotify app version (if native SSO flow is involved)
Android OS version

### Severity
Trivial, Minor, Major, Catastrophic

## Steps to Reproduce
1. Step by step instructions on how to reproduce this bug.
2. The more detailed your list of instructions, the easier it is for the developer to track down the problem!

### Actual behaviour
Describe what happens when you perform the steps above.

### Expected behaviour
Describe what you expected to happen when performing the steps above.

## Logs
Please include any relevant log output that might assist in tracking down the problem.

**Comment by williammlu** [comment]
You download the latest release ([https://github.com/spotify/android-sdk/releases/latest](at the bottom of this page). The `.aar` file can be found by unzipping the file you just downloaded.

**Comment by arirawr** [comment]
Hi @hiranandanisonal - you need to **unzip** the file. Check out some instructions on how to do that [here](https://www.wikihow.com/Unzip-a-File).
