### ISSUE TITLE
Waze Allows Streaming For Free Spotify Users?

### ISSUE THREAD

**Issue by kevinmauro92** [spotify/android-sdk#389]
Hi,

I noticed that Waze allows for Spotify streaming for free users. I was wondering if it is possible to stream for free users using this API, as the readme says streaming is possible for Premium users only. If it is not possible for free users without some special requests from Spotify, is there a support e-mail for corporate requests like this?

Thanks

**Comment by arirawr** [comment]
Streaming for free users is not offered in the public Spotify Platform. _Some_ of our commercial partners do allow streaming for all users. If you wish to apply for commercial partnership, you may do so [here](https://docs.google.com/a/spotify.com/forms/d/e/1FAIpQLScddRrdBM0tglI1ijKF5uWgBUnxUDbHnxwzWxaqdR-PE4L5OQ/viewform?c=0&w=1).

**Comment by kevinmauro92** [comment]
Can you please push my request through? It's for Vybuds, brain stim headphones for studying and making people happier  @arirawr
