### ISSUE TITLE
Sign in problems

### ISSUE THREAD

**Issue by lhk** [spotify/android-sdk#391]
We are using this project to get authentication credentials: https://github.com/spotify/android-auth

Lately we have been experiencing connectivity problems, error messages after the login process: https://github.com/spotify/android-auth/issues/34

Does anyone else have this problem ?
Could someone with more experience with the spotify API give some tips what might cause this ?

We can't explain the sudden problems. Our code is in version control, so we are sure that nothing changed on our side.
This sdk and the authentication api haven't been updated in a long time.
And the web api changelog has nothing either: https://developer.spotify.com/web-api/change-log/

**Comment by bih** [comment]
Can you give us more information on how to replicate this issue? What steps you took and expected/actual behaviours?

**Comment by andreiblaji-cc** [comment]
Hi,

I'm having issues with authentication too, but i have different error code: -4. I tried same account in the browser on spotify.com to make sure it's working, but it fails when i do login through auth library. Any ideas ?

Thanks.

**Comment by arirawr** [comment]
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with reproduction steps if you are still seeing the issue!
