### ISSUE TITLE
Redirect URI Issue?

### ISSUE THREAD

**Issue by abechoi** [spotify/android-sdk#392]
Can someone tell me if I had set up my redirect URI correctly?

I've followed every step in the quick start guide almost verbatim... https://beta.developer.spotify.com/documentation/android-sdk/quick-start/

The only confusion I had with it was the setting up my redirect URI. On my dashboard I set the URI to http://(my ip address):8888/callback/

If I set "private static final String REDIRECT_URI" to "yourcustomprotocol://callback"
then I get a Invalid Redirect URI.

If I set "private static final String REDIRECT_URI" to "8888://callback"
then I get "Error Oops! Something went wrong"

What would be the correct way to format this?

Additional Information:

When I would try to login, I would get stuck on the login screen and this message would loop.

<img width="540" alt="screen shot 2017-12-11 at 12 33 14 am" src="https://user-images.githubusercontent.com/7634806/33822909-0c7f69d0-de0e-11e7-8882-8202071aee84.png">

**Comment by abechoi** [comment]
Resolved thanks to @arirawr 
I set both the dashboard Redirect URI and MainActivity.java REDIRECT_URI to simpleapp://callback and I logged in fine, saw the hello world!, and heard the music.

**Comment by arirawr** [comment]
🎉 🎉
