### ISSUE TITLE
/me report open/free user (part of Premium for Family)

### ISSUE THREAD

**Issue by gvargascl** [spotify/android-sdk#393]
## Description
We have an Android application with Spotify SDK integrated. We use the latest available version of -auth and -player.
We have an user which is part of a "Premium for Family" Plan (additional user).

If we login in the Desktop Spotify App we can see a Spotify Premium in the title.
if we login in the iOS Spotify App we can see a "Free subscription".
If we login in our App for Android, the app get the token and ask to /me endpoint to see which product is associated to the user. Normally if the user has an active subscription, we got premium in the product field, but with this user we got "open" user.

### Versions
Android SDK version: 7.1.1
Spotify app version (if native SSO flow is involved): 8.4.32.623
Android OS version: spotify-player-24-noconnect-2.20b@aar

### Severity
Major

## Steps to Reproduce
1. Open a Console API with a valid token and try to get information of the current user (/me endpoint).
2. Look for the product field.

### Actual behaviour
Product field return "open".

### Expected behaviour
Product field should return "premium". (Because is part of a Premium for Family Plan)

## Logs
Web request:
```
GET /v1/me HTTP/1.1
Host: api.spotify.com
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, compress
Authorization: Bearer BQD0691K..... 
User-Agent: Spotify API Console v0.1
```

Web response:

```
{
  "country" : "CL",
  "display_name" : "Paulina Vidal",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/user/XXXX-cl"
  },
  "followers" : {
    "href" : null,
    "total" : 1
  },
  "href" : "https://api.spotify.com/v1/users/XXXX-cl",
  "id" : "XXXX-cl",
  "images" : [ {
    "height" : null,
    "url" : "https://scontent.xx.fbcdn.net/v/t1.0-1/c2.0.200.200/p200x200/XXXXXX",
    "width" : null
  } ],
  "product" : "open",
  "type" : "user",
  "uri" : "spotify:user:XXXX-cl"
}
```
Spotify iOS App, Account area.
![img_2116](https://user-images.githubusercontent.com/34865836/34361394-7afb0234-ea48-11e7-96fc-48184dde3d73.png)

**Comment by bih** [comment]
The only thing it could be from our end is that your account is not considered premium. As we don't deal with account-related issues, I'll kindly ask you reach out to customer support and ask them to figure out how to make sure your account is tied to your Premium Family plan.

For that reason, I'll go ahead and close this issue. If there's any technical issues that arise relating to the APIs and SDKs themselves, please feel absolutely free to re-open this issue and we'll investigate :)
