### ISSUE TITLE
Getting "kSpErrorNeedsPremium" error when logging in with user (Premium for Family)

### ISSUE THREAD

**Issue by yamalight** [spotify/android-sdk#394]
## Description
Upon login Spotify returns the following error:
```
{ code: 93,
message: 'kSpErrorNeedsPremium',
domain: 'RCTSpotifyErrorDomain' }
```

### Versions
Android SDK version: 26.0.2
Spotify app version (if native SSO flow is involved): n/a
Android OS version: 27 (8.1.0)

### Severity
Catastrophic

## Steps to Reproduce
1. Create new app that only logs user in
2. Create a user that has Premium for Family (tested with "master" account)
3. Try to log into the app
4. Get the error mentioned above

### Actual behaviour
Spotify returns error saying user needs premium.

### Expected behaviour
Spotify should recognize family premium and correctly log user in.

**Comment by yamalight** [comment]
Just got a simple (non-Family) premium account from colleague - and exactly same code successfully logs in with it.

**Comment by bih** [comment]
Sorry to hear that you're having an issue. What's your Spotify username?

**Comment by yamalight** [comment]
@bih same as here - yamalight

**Comment by bih** [comment]
The only thing it could be from our end is that your account is not considered premium. As we don't deal with account-related issues, I'll kindly ask you [reach out to customer support](https://support.spotify.com) and ask them to figure out how to make sure your account is tied to your Premium Family plan.

For that reason, I'll go ahead and close this issue. If there's any technical issues that arise relating to the APIs and SDKs themselves, please feel absolutely free to re-open this issue and we'll investigate :)

**Comment by yamalight** [comment]
@bih alright, will try, thanks!
