### ISSUE TITLE
Question about Streaming Quality 

### ISSUE THREAD

**Issue by HwanChoi** [spotify/android-sdk#405]
1. I would want to use SDK for Streaming Quality.
It is same the function to official Spotify Android APK supported currently? 

2. how to support Connected Devices.
How Can I show Connected Devices in my application?
there is no API to show them (same account)

Thank you!

**Comment by arirawr** [comment]
Hi @HwanChoi !

(1) You can set the bitrate for playback. See https://spotify.github.io/android-sdk/player/index.html?com/spotify/sdk/android/player/PlaybackBitrate.html

(2) You will need to use the Spotify Connect Web API for that. See the "Get a User's Available Devices" endpoint here: https://beta.developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/

Hope that helps!
