### ISSUE TITLE
Play Track offline / Download Track

### ISSUE THREAD

**Issue by maracuja-juice** [spotify/android-sdk#406]
Is it already possible with the library to play a track when the user is offline?

Or is it possible to implement this yourself? Only had a quick look but it sounds promising to implement your own Audiocontroller and save the buffer to a database. But I'm not sure if it is then possible to read from that database and play the song.

**Comment by arirawr** [comment]
Hi @maracuja-juice - this is not available in the Android SDK. However, you can take a look at the new Android App Remote SDK, which allows remote control of playback in the Spotify app, which does offer this functionality: https://beta.developer.spotify.com/documentation/android-app-remote/

**Comment by maracuja-juice** [comment]
Thanks for the info. What I don't understand about the new SDK is the exact offline playing capabilities. See [this issue here](https://github.com/spotify/android-app-remote-sdk/issues/2#issuecomment-378557103)

**Comment by arirawr** [comment]
Cool, just gave a response over there 👍
