### ISSUE TITLE
Cannot reach website to authenticate user

### ISSUE THREAD

**Issue by clevertrevor** [spotify/android-sdk#412]
## Description
I am trying to have the user login to Spotify through the browser (Chrome). This fails because the browser returns an error: "This site can't be reached. accounts.spotify.com's server DNS address could not be found. DNS_PROBE_FINISHED_BAD_CONFIG". 
The url in the browser is [https://accounts.spotify.com/authorize?client_id=76edc333f1f74a99878e80d5b2874372&response_type=token&redirect_uri=playlistmessagesforspotify%3A%2F%2Fcallback&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=playlist-read-private%20playlist-modify-public%20playlist-modify-private%20playlist-read-collaborative](url)

### Versions
Android SDK version: 27
Spotify app version (if native SSO flow is involved): Spotify not installed
Android OS version:  8.1.0 (emulated) 

### Severity
Catastrophic

## Steps to Reproduce
1. Call `AuthenticationClient.openLoginInBrowser(activity, request)` with a valid request. 
`
### Actual behaviour
Receive an error in Chrome: "This site can't be reached. accounts.spotify.com's server DNS address could not be found. DNS_PROBE_FINISHED_BAD_CONFIG". 

### Expected behaviour
The browser successfully loads and redirects the user back to my app.

## Logs
There were no logs.

**Comment by arirawr** [comment]
Hi @clevertrevor - I'm not able to replicate this issue, and it seems to be an issue with your network. I suggest you try some of the remediations here: https://errorcodespro.com/fix-error-dns_probe_finished_bad_config-for-android-mac-chrome/

**Comment by clevertrevor** [comment]
Thanks @arirawr for the help. The issue went away on it's own.
