### ISSUE TITLE
What is the android-sdk licence

### ISSUE THREAD

**Issue by munhra** [spotify/android-sdk#415]
## Description
hello guys thanks for a good job on the sdk, it saves me hours of hard work. I'm here to ask you guys what is the open source license, AGPL, GPL, LGPL, APACHE, MIT or other,  that applies to the lib. I look inside document https://beta.developer.spotify.com/terms but I could not find it.

**Comment by arirawr** [comment]
Hi there! This library is not open source, so does not have a license. The android-auth SDK is open source, and its license can be found here: https://github.com/spotify/android-auth/blob/master/LICENSE. Use of any Spotify Developer tools falls under our [Developer Terms of Service](https://developer.spotify.com/terms).
