### ISSUE TITLE
Play without premium

### ISSUE THREAD

**Issue by droidmunkey** [spotify/android-sdk#49]
I would like to design a fancy widget or a wear app to remotely control my phone - it would be nice if I could still use play/pause functions on non-premium accounts

Something like mPlayer.play("spotify:free");

I would also need a way to check if the user had a premium account programmatically.

Every active user is a potential upgrade and increases your ad revenue :-)

**Comment by thelinmichael** [comment]
Hey @droidmunkey and @acelee95. There are no plans to drop the requirement of a premium account to stream music using the mobile SDKs.
