### ISSUE TITLE
Unsatisfied link error...couldn't find "libgnustl_shared.so"

### ISSUE THREAD

**Issue by markrebhan** [spotify/android-sdk#52]
Hi,

I got the sample app from the example to work with no problems but if I try to access the Player object on my project I wish to use this library for, I get an error. My project has the latest build tools and gradle version and has many dependencies including some other JNI bindings. Are there any known conflicts with other dependencies or with trying to include multiple native libraries?

**Comment by kaaes** [comment]
@markrebhan could you maybe post your app's build file? It would help us to reproduce your problem.

**Comment by kaaes** [comment]
Support for ARMv7 devices has been added to 1.0.0-beta7. Please give it a try
