### ISSUE TITLE
Could you please explain what exactly "useCache" does?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/android-sdk#54]
I wonder if it caches the current song, or the whole queue. Lets say i start my playlist with 10 songs... does it cache all 10 songs at once or does it cache a song when played. 

at the moment i turned it off, because i had some strange behavior while skipping tracks.sometimes it took a few seconds until the "track changed" event happened, altough  the song starts playing very fast.

it would be great if you could explain your roadmap for offline support.

Please think about an method cacheTracks(uri,uri,uri,uri....) and a method to find out which tracks are already cached. furthermore the time a token expires needs to be adjusted. At the moment the token expires after an hour, 24 hours would be great.

thanks for your feedback and keep on the good work..
Alex

**Comment by d-kunin** [comment]
What it does is caching the file being played on disk. It reduces latency and data consumption if you seek or play it again. 
We dont precache/prefetch other tracks from the queue.

**Comment by 3ammari** [comment]
What about the check if the track is cached or not ?
