### ISSUE TITLE
AudioManager.OnAudioFocusChangeListener for the Player class

### ISSUE THREAD

**Issue by Beeo4** [spotify/android-sdk#55]
I would like to have the Spotify Player that is currently playing a song duck its own volume while I play a short sound over it.

Currently it doesn't seem possible to adjust only the Player's volume.  The only way I've found to adjust its volume is with AudioManager:

`audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, volumeindex, 0);`

However, this is less than ideal since it lowers anything playing through STREAM_MUSIC -- including the sound I am attempting to play.

**Comment by yojihirose** [comment]
I could do it by using custom audio controller.
Add below code to the sample code on https://github.com/spotify/android-sdk/issues/91

```
    public void setVolume(float volume) {
        if (mTrack != null ) {
            mTrack.setVolume(volume);
        }
    }
```

references
https://developer.spotify.com/android-sdk-docs/player/com/spotify/sdk/android/player/Player.html
https://github.com/spotify/android-sdk/issues/91

**Comment by erdtman** [comment]
does the solution suggested by @yozhik-man work for you @Beeo4?

**Comment by erdtman** [comment]
I will close this, since there seem to exist a way to do this.
