### ISSUE TITLE
Throwing exception, failed SpPlayUri with error code 5 (An unexpected argument value was passed to a function)

### ISSUE THREAD

**Issue by mattjohnpowell** [spotify/android-sdk#56]
I'm using the Echonest API to get some songs based on certain criteria and then passing those tracks to the player. However the songs retrieved are in the format:
spotify-NZ:track:6swuK46NOakrmCPmLGEDs3

whereas the only tracks that seem playable are in the format:

spotify:track:2TpxZ7JUBn3uw46aR7qd6V

Stripping the "-NZ" also gives a playback error.

**Comment by kaaes** [comment]
@mattjohnpowell the track uri needs to be in the `spotify:tracks:xxxxxxxxxxx` format
If the track is not available you should get this information in the `onPlayerError` callback.
To register this callback use [addPlaybackNotificationCallback](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/Player.html#addPlayerNotificationCallback-com.spotify.sdk.android.playback.PlayerNotificationCallback-) method

**Comment by kaaes** [comment]
@mattjohnpowell did you solve this issue?

**Comment by mattjohnpowell** [comment]
@kaaes actually no but I understand there will be a new part of the Echonest api that allows you to search for local buckets and then filter for locally playable tracks. 
https://developer.echonest.com/forums/thread/3704
A Spotify.isTrackAvailable() method might be fantastic also though

**Comment by kaaes** [comment]
@mattjohnpowell I understand that you got the error mentioned in the title when you tried to play track using `spotify-NZ:track:6swuK46NOakrmCPmLGEDs3` uri and when it was `spotify:track:6swuK46NOakrmCPmLGEDs3` it gave you track unavailable error?

If this is the case I'd close this ticket as this is the expected behaviour.
