### ISSUE TITLE
What is happening if the user keeps playing for more than 1 hour and token is expired?

### ISSUE THREAD

**Issue by KeithYokoma** [spotify/android-sdk#58]
I don't know much about the detail of SDK implementation, but I would like to know what SDK will do when the token is expired during user playing music.

If Spotify player won't play right after token is expired, I need to refresh access token. But it does not seem to have any API to set a new access token to player.
For now I think I need to create a new player instance with the new access token as a workaround, but it sounds pretty weird...

**Comment by KeithYokoma** [comment]
Yes I know how to refresh my token with web api, but I would like to know how to set the refreshed access token to current Player instance during music playing.

**Comment by kaaes** [comment]
Currently the only way to update the player with the new token is to create a new instance. It is rather inconvenient and fixing it is on the list of coming updates.

**Comment by KeithYokoma** [comment]
I see.

Thanks for your reply.

**Comment by kaaes** [comment]
In the latest version of SDK (beta7) player has methods for logging in and out. If the player session is terminated for some reason (like losing the network) the `ConnectionStateCallback#onLoggedOut` callback will be triggered. When this happens you can log in again with a valid token using the `login` method

**Comment by kaaes** [comment]
I'll close this issue now. Please reopen if you think it needs more discussion
