### ISSUE TITLE
How can I check when playing song ends?

### ISSUE THREAD

**Issue by MattPL** [spotify/android-sdk#60]
Hi :-) I would like to check if song ends and choose another one right after it (can't choose it earlier). How can I do this? I tried to use `onPlaybackEvent` method but it didn't work (No message in logs shown). I suppose that in my case i should use `TRACK_END` constant but how?
Thanks for help!
```
    @Override
    public void onPlaybackEvent(EventType eventType, PlayerState playerState) {
        Log.d("MainActivity", "sdkdjksd");
    }
```

**Comment by kaaes** [comment]
@MattPL have you tried the suggestion in the previous comment?

**Comment by jotagutierrezmar** [comment]
I do it like this:


            mPlayer.addPlayerNotificationCallback(new PlayerNotificationCallback() {
                @Override
                public void onPlaybackEvent(EventType eventType, PlayerState playerState) {
                      if (eventType == EventType.TRACK_END) {
                          //do something
}
}

**Comment by kaaes** [comment]
@MattPL I'm going to close this issue. Please reopen if you think it needs more explanation
