### ISSUE TITLE
Too much CPU consumption on registering registerAudioDeliveredCallback().

### ISSUE THREAD

**Issue by acelee95** [spotify/android-sdk#61]
Hi,
Getting raw PCM is exactly what I'm trying to do now.
After digging into it, I finally succeeded to get raw PCM samples but my code seems to consume a lot CPU usage. (over 26% vs tutorial's 3 ~ 5%) I'd like to share and find what's the problem.

I created my own Player that is subclassing Spotify's Player class via calling create() with NativeSdkPlayer as the first argument. See my code snippet below.
// Test code for creating SpotifyPlayer subclassing Spotify's Player calss
```
private SpotifyPlayer mPlayer;
...
protected void onNewIntent(Intent intent) {
    ...
    AuthenticationResponse response = SpotifyAuthentication.parseOauthResponse(uri);
    Spotify spotify = new Spotify();
    Config playerConfig = new Config(this, response.getAccessToken(), CLIENT_ID);
    Player.InitializationObserver observer = new Player.InitializationObserver() {
        @Override
        public void onInitialized() {
            mPlayer.addConnectionStateCallback(MainActivity.this);
            mPlayer.addPlayerNotificationCallback(MainActivity.this);
            mPlayer.play("spotify:track:2TpxZ7JUBn3uw46aR7qd6V");
        }

        @Override
        public void onError(Throwable throwable) {
            Log.e("MainActivity", "Could not initialize player: " + throwable.getMessage());
        }
    };

    mPlayer = SpotifyPlayer.create(new NativeSdkPlayer(), playerConfig, observer);
    ...
}
```

And to get raw PCM samples delivered through onAudioDelivered() and redirect them
into AudioTrack for simple playback test, I wrote the following codes. (it works fine.)
// And here's the impl. of SpotifyPlayer.
```
public class SpotifyPlayer extends Player {

    private static NativeSdkPlayer mSdkPlayer;
    private AudioTrack mAudioTrack;
    ...

    protected SpotifyPlayer(InitializationObserver observer, NativePlayer nativePlayer) {
        super(observer, nativePlayer);
    }

    public static SpotifyPlayer create(NativePlayer nativePlayer, Config config,
                                       Player.InitializationObserver observer) {
        mSdkPlayer = (NativeSdkPlayer)nativePlayer;
        Player.create(mSdkPlayer, config, observer);// <-- This cosumes CPU a lot.
        return new SpotifyPlayer(observer, nativePlayer);
    }

    @Override
    public int onAudioDelivered(short[] frames,
                                int numFrames,
                                int sampleRate,
                                int channels) {

        ...
        byte[] pcm = shortArrayToByteArray(frames, numFrames);
        mAudioTrack.write(pcm, 0, pcm.length);
        return numFrames;
    }

    @Override
    public void play(String uri) {
        try {
            ...
            // Redirect to AudioTrack.
            int bufferSize =  AudioTrack.getMinBufferSize(44100, AudioFormat.CHANNEL_OUT_STEREO,
                    AudioFormat.ENCODING_PCM_16BIT);
            mAudioTrack = new AudioTrack(AudioManager.STREAM_MUSIC, 44100, AudioFormat.CHANNEL_OUT_STEREO,
                    AudioFormat.ENCODING_PCM_16BIT, bufferSize*3, AudioTrack.MODE_STREAM);
            mAudioTrack.play();

            mSdkPlayer.playUri(uri);
        } catch (NativeSpotifyException e) {
            e.printStackTrace();
        }
    }
...
}
```

The problem is that registering callback through registerAudioDeliveredCallback() or creating Player by calling Player.create() both consumes too much CPU usage(over 25%). Piping raw PCM from native SDK into java world's onAudioDelivered() has a problem? Please let me know how to reduce CPU consumption while registering callback or any other solution.
Thanks :)

**Comment by acelee95** [comment]
Any update? I'm still wondering if this could be fixed. Please let me know if there's any update.

**Comment by nikreiman** [comment]
We will change the API for how raw PCM samples may be accessed, which should eliminate this problem.

**Comment by kaaes** [comment]
Version 1.0.0-beta7 has a new way of getting access to PCM data. Instead of subclassing the Player you should implement a custom [`AudioController`](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/AudioController.html) and pass it to the player during creation.

**Comment by acelee95** [comment]
Awesome! Now it works very well with lower CPU usage. Thanks guys :)
