### ISSUE TITLE
How much kbps has a track?

### ISSUE THREAD

**Issue by oliverkrakora** [spotify/android-sdk#62]
I would like to know which bitrate the tracks have,there's currently no method(libspotify "
sp_error 	sp_session_preferred_bitrate (sp_session *session, sp_bitrate bitrate)") to change the preferred bitrate.

**Comment by kaaes** [comment]
This functionality has been added to 1.0.0-beta7. See [`Player#setPlaybackBitrate`](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/Player.html#setPlaybackBitrate-com.spotify.sdk.android.playback.PlaybackBitrate-),
