### ISSUE TITLE
Sample for Player subclass

### ISSUE THREAD

**Issue by Meisolsson** [spotify/android-sdk#63]
This would be a nice thing to have. I tried to extend it and it works but when I try to call <code>Spotify.destroyPlayer()</code> the app crashes.

**Comment by kaaes** [comment]
Version 1.0.0-beta7 has a new way of getting access to PCM data. Instead of subclassing the Player you should implement a custom [`AudioController`](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/AudioController.html) and pass it to the player during creation.
