### ISSUE TITLE
END_OF_CONTEXT with PlayerConfig

### ISSUE THREAD

**Issue by jotagutierrezmar** [spotify/android-sdk#64]
Hi,

I'm developing a little application that plays music either from a previously charged list or reading from a file. To charge the songs I do it like this:

 private void LoadSongs(){
        tracksUris.add(0,"spotify:track:7GBGXDmYOTHuBtPfRZc6Vu"); //Dead Air
        tracksUris.add(1,"spotify:track:7JeYK1pt9Kds0E62S7uiIU"); // Water Fountain
        tracksUris.add(2,"spotify:track:7GOAPpHfg8yb2jGxMIOx2y"); //CEO - Wonderland
        tracksUris.add(3, "spotify:track:4VrWlk8IQxevMvERoX08iC"); //Chandelier
        tracksUris.add(4,"spotify:track:78zp5yTpZWdrBrC1LAEP3c"); //Otra Era
        tracksUris.add(5,"spotify:track:73JwUp9K4GYUNnqz5onncr"); //Prenderemos fuego al cielo
        tracksUris.add(6,"spotify:track:03m03OVQGPuzt8Rw2r0a7t"); //Do you hear the people sing?
        tracksUris.add(7,"spotify:track:0PjkFSNBbpfYRYpAG4uuGb"); //Boom! Clap!
        songsNumber = tracksUris.size();
    }

And to play them:

pConfig = PlayConfig.createFor(tracksUris);
            pConfig.withTrackIndex(index);
            pConfig.withInitialPosition(position);
            mPlayer.play(pConfig);

(index and position are 0 by the moment)

When I push play, the first song starts playing, but when I try to skip to the next song I get an END_OF_CONTEXT event and the music stops playing. Why is this happening?

Also, do you plan to put a method to know the song name and the artist by the spotify URI?

Thanks!

**Comment by kaaes** [comment]
I tried your code and it worked for me (I was able to skip through the context).
Is there anything in the logcat that looks like it could be related to the issue? Is it possible that the track you're trying to play is not available in your market?

Song's metadata such as artist name or title can be retrieved from our Web API. There are some libraries you can use listed on our dev page: https://developer.spotify.com/web-api/code-examples/#libraries

**Comment by jotagutierrezmar** [comment]
It's happening something very weird:

I can load the tracks in two ways: by loading like this or by reading the URIs from a file. Now, if I do it like this, it works. 

In the file way, I receive the file from another device, read it and charge the songs. If I put the code of receiving the file before charging, it works ok, but if I receive the file in some other way (for example, the file is already on my device) it doesn't work, and the charge method is the same. I can listen to the first song, and I can see that tracksURIs has got all the songs, but when I skip to next I get an END_OF_CONTEXT event. What's more, I've got an index to see which song I'm playing on the list. When it doesn't work (when the END_OF_CONTEXT occurs), if i push "next" the index goes from 0 to 2. I'm a little bit desperate since I can't find what I'm doing wrong.

I'll try the wrappers, let's see how it works. Anyway, it would be interesting to have this feature in the android SDK :)

**Comment by jotagutierrezmar** [comment]
This is my new code for reading from the file, and I still have the problem. 

            this.chargeFile();
            for (int i = 0; i < songsNumber; i++) {
                tracksUris.add(i, playlist[i]);
            }
            pConfig = PlayConfig.createFor(tracksUris);
            pConfig.withTrackIndex(index);
            pConfig.withInitialPosition(position);
            mPlayer.play(pConfig);
            this.getSongTitle(index);
        }

playlist[] is the string where I save the tracks URIs read from the file. Also, I charge the position and the index from the file. I have checked that the saved values are ok, for index, position and both playlist and tracksUris. I can listen to the charged song from the position I want to, but when I push next it skips a song and then I get the END_OF_CONTEXT (and is not even the end of the playlist, for example, in my last try i have charged song 2 out of 8 and when clicking next it goes to song 4 and then the end of context comes).

Any idea?

**Comment by jotagutierrezmar** [comment]
And one more (sorry for the spam):

I've got this code (loaded == 1 says that the playlist comes from file):

 else if(loaded == 1){
                            pConfig = PlayConfig.createFor(tracksUris);
                            pConfig.withTrackIndex(index);
                            pConfig.withInitialPosition(position);
                            mPlayer.play(pConfig);
                        }

If I put this code inside the onClick for play button, when the user pushes play it works ok, but if I put this code outside (the song starts even if the user doesn't click play) I get the f***** END_OF_CONTEXT case.

**Comment by kaaes** [comment]
Hmm, it sounds like some kind of a race condition. Is it possible that the tracksUris content is modified after mPlayer.play is called? Could you try logging out all elements of the list just before playing it? Or adding some artificial delay (like a second or two) before playing and see if it works then?

**Comment by jotagutierrezmar** [comment]
No, tracksUris is never modified. I tried logging out and i still get the same error, but, putting the thread to sleep for 2 seconds has worked. THANK YOU VERY MUCH. 

Anyway, I don't get the error, but, hey, it works.

**Comment by kaaes** [comment]
I'm glad it worked but if adding a delay fixed it it is a pretty good clue there's something async going on that affects the context that you're trying to play. I think it's worth further investigation so it won't surface again in other places.
I'll close the issue now. Feel free to reopen if you think there's more to it.
