### ISSUE TITLE
Redirecting Into the Implementing App After Authenticating is Unreliable

### ISSUE THREAD

**Issue by sddamico** [spotify/android-sdk#65]
I just went through the process of implementing your SDK for the SeatGeek Android app. Everything went fairly smoothly with one caveat: different Android browsers handle their task stack differently.

Some Android browsers (Chrome) will maintain the current task of the source application so that navigating up in the stack is possible, while others (Firefox) will seemingly create a new task, preventing the type of navigation flow we want in our application. After authenticating with Spotify, we want to navigate back up the task stack to the `Activity` that initiated the authentication, this works differently with Chrome vs. Firefox vs. Browser.  Another issue is that some browsers pass different flags along with the redirect intent.

This level of inconsistency made it challenging to implement the authentication flow in the way that we wanted. As a result, we had to load the Spotify auth web inside our own `WebView` in an `Activity` that we control so that we could manage the task stack in the way that we wanted to. Then, using a `WebViewClient`, we're catching the redirect uri, parsing it ourselves, and then taking the user exactly where we wanted them to go.

I highly recommend packaging an `Activity` with the SDK that does this for the developer so that there's no ambiguity about how the redirect will be sent and what task it will be in.

**Comment by kaaes** [comment]
Thank you for your feedback. I agree that our current auth flow is far from perfect (especially the `singleInstance` part).
We are working on a better solution that will include login page in a WebView and is intended to be a part of the next release.
Stay tuned!

**Comment by kaaes** [comment]
We have now added authentication flow in the WebView to the 1.0.0-beta8. Please give it a try.
