### ISSUE TITLE
Cannot get correct index from PlayConfig.

### ISSUE THREAD

**Issue by pl4za** [spotify/android-sdk#67]
Hello !
After adding the tracks to the queue and calling skipToNext, i cannot retrieve the index, it always returns 0. 

Here is my code:
Config = PlayConfig.createFor(queue);
mPlayer.play(Config);

And after changing track:
System.out.println(Config.getIndex());

Is this a sdk problem or i'm not doing it right ?
Regards !

**Comment by kaaes** [comment]
PlayConfig contains a configuration of the thing you want to play. If you want to get information about what track is currently playing you need to subscribe to Player notifications and read it from there:

```java
mPlayer.addPlayerNotificationCallback(new PlayerNotificationCallback() {
    @Override
    public void onPlaybackEvent(EventType eventType, PlayerState playerState) {
                // Handle event and changes in player state
    }

    @Override
    public void onPlaybackError(ErrorType errorType, String errorDetails) {
        // Handle playback errors such as unavailable tracks
    }
});
```

**Comment by pl4za** [comment]
Thanks for the reply.
I make use of the PlayerNotificationCallback, but it doesn't give the track index, only the track URI.
So PlayConfig index doesn't update on track change ?

**Comment by kaaes** [comment]
PlayConfig is only used to send the information about the context to the player and doesn't update after it's played.
If you need an index of the track in the context you can fetch the list of tracks from Web API and find out from there.

**Comment by pl4za** [comment]
Ok, thank you. I'm now doing that.
Regards.
