### ISSUE TITLE
Login Through a WebView

### ISSUE THREAD

**Issue by JohnnyFirpo** [spotify/android-sdk#69]
Since Version 1.0.0-beta8 it should be possible to login through WebView as described here https://developer.spotify.com/technologies/spotify-android-sdk/android-sdk-authentication-guide/#login-through-a-webview
I tried to use it in my application but in "onActivityResult" the intent is empty and the result code is 0. 
I think the problem is that "onActivityResult" is called right after  AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request); and before I am asked to login and accept scopes. After login neither  "onActivityResult" nor "onNewIntent" are called.

**Comment by kaaes** [comment]
@JohnnyFirpo thanks for the report. I tried to reproduce this error but wasn't able to. Could you give me some more details?
* Are there any relevant looking messages in the logcat?
* Does REQUEST_CODE in the onActivityResult match the one that you pass to `openLoginActivity'?
* Can you show the code you're using to open/close the LoginActivity?
* What Android version and what device are you using?

**Comment by JohnnyFirpo** [comment]
@kaaes thanks a lot for your answer and pointing me to the logcat. I figured out that the problem was in my AndroidManifest.xml. For my Activity that calls AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request); I had set android:launchMode="singleInstance".
As  explained here http://stackoverflow.com/questions/6428070/android-home-activity-launching-a-sub-activity this will immediately cancel the request and call "onActivityResult".  I removed it and everything works fine.
So Issue can be closed

**Comment by kaaes** [comment]
I'm happy to hear you made it work.
I'll add a check and some logs for similar cases. Thanks!
