### ISSUE TITLE
Fail to find com.spotify.sdk:spotifysdk:1.0.0-beta6 

### ISSUE THREAD

**Issue by krunal131987** [spotify/android-sdk#70]
I am also getting same error Fail to find com.spotify.sdk:spotifysdk:1.0.0-beta6 
![screenshot from 2015-02-17 16 47 19](https://cloud.githubusercontent.com/assets/2108134/6227383/e7428382-b6c4-11e4-9329-7feddc2c60f3.png)

![screenshot from 2015-02-17 16 51 57](https://cloud.githubusercontent.com/assets/2108134/6227418/75f99584-b6c5-11e4-9fec-855118ad94f8.png)

![screenshot from 2015-02-17 16 49 52](https://cloud.githubusercontent.com/assets/2108134/6227397/2b6edb3c-b6c5-11e4-82d9-1a78e8a1e95f.png)

**Comment by kaaes** [comment]
Have you added `libs` as a local repository?

```
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}
```

**Comment by krunal131987** [comment]
yes, I was solved out

**Comment by kaaes** [comment]
Great to hear. I'll close this issue then.
