### ISSUE TITLE
Way to refreseh token without reconnect user

### ISSUE THREAD

**Issue by FrancoisLegrand2013** [spotify/android-sdk#72]
I'm looking for a good way to refresh my token after one hour without calling AuthenticationClient.openLoginInBrowser(context, request). Is it possible ?

**Comment by krunal131987** [comment]
Is there any swap url like for iPhone for re-authenticate user without user interation?

**Comment by kaaes** [comment]
You can refresh token if you use the [authorization code flow](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow). This requires a backend service that will be able to perform a swap and that you need to build (it's not the part of the SDK)

If you use LoginActivity it is possible to get a new access token from an [implicit grant flow](https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flow) that the SDK is using.
Once you [authenticate the user in the WebView](https://developer.spotify.com/technologies/spotify-android-sdk/android-sdk-authentication-guide/#login-through-a-webview) you can trigger openLoginActivity again and a new token will be issued.

**Comment by FrancoisLegrand2013** [comment]
Ok, Thank You !
