### ISSUE TITLE
AuthenticationClient#openLoginActivity with a Fragment

### ISSUE THREAD

**Issue by CedrickFlocon** [spotify/android-sdk#73]
Hello, 

We can only call  `AuthenticationClient#openLoginActivity` with an `Activity` the `Activity#onActivityResult` as the callback. But `Fragment#startActivityForResult` also exist and have `Fragment#onActivityResult` as the callback.

Version 
beta8

Regards
Cédrick

**Comment by kaaes** [comment]
1.0.0-beta9 provides a method that creates an intent that can be used to open LoginActivity from the Fragment
