### ISSUE TITLE
If you are using Netbeans/Eclipse with JAR based  project definition, read this

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#74]
Unzipping the Gradle file and moving the "classes.jar" into the \libs folder, the folder may be opened as a traditional Android project in Netbeans. But to be able to BUILD the project, Android SDK seems to need a \src folder to be present, else it will try it best to confuse you with the following error "source does not exist". This is because the .aar file contains no such \src folder. 

Thus, add an empty \src subfolder into the project folder prior to building.  Hope this will help somebody else in not spending a day trying to figure out the mystery.

Would it be possible for Spotify developers to include this empty \src folder in forthcoming releases, or is this given by the Gradle system?

**Comment by kaaes** [comment]
@chjan thank you for providing this instruction. Even though we don't officially support Eclipse/Netbeans I'll be happy to test it and link to it from our documentation.

I don't think we should add `/src` folder to the binary as `aar` format is defined by the Android Gradle plugin (http://tools.android.com/tech-docs/new-build-system/aar-format) and I would rather not change its structure.
I would instead add a clear step in the instruction that you need to create this folder in order for the project to build.
