### ISSUE TITLE
Spotify player does not stop.

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#75]
Hi I have made a little application using spotify. I have a stop button to stop audio streaming on button click and resume on same button. I found the resume() method but not able to find any stop button. Is it not possible to stop the music?

Issue 2: For stoping music if i use player.pause() method on the second time its re-connects again successfully but on double tap on the button music play's again what's  going bad into this?

**Comment by kaaes** [comment]
To stop the playback you should use `player.pause()`, to resume use `player.resume()`.
If you'd like to change the button's behavior depending on player state you should subscribe to player events and read player state from there:

```java
boolean playerIsPlaying = false;
        
mPlayer.addPlayerNotificationCallback(new PlayerNotificationCallback() {
    @Override
    public void onPlaybackEvent(EventType eventType, PlayerState playerState) {
        playerIsPlaying = playerState.playing;
    }

    @Override
    public void onPlaybackError(ErrorType errorType, String errorDetails) {}
});

mPlayer.play("spotify:track:0ShaTPtLlfWw0styNARd3d");
        
button.setOnClickListener(new View.OnClickListener() {
    @Override
     public void onClick(View v) {
         if (playerIsPlaying) {
             mPlayer.pause();
         } else {
             mPlayer.resume();
         }
     }
});
```
