### ISSUE TITLE
seekToPosition issues.

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#76]
When calling seekToPosition the current playback is paused without resuming it back. I have to do a player.resume () immediatly after every seekToPosition call.

**Comment by kaaes** [comment]
How are you calling `seekToPosition`? I checked on the latest version of the SDK and it seems to work as expected.
Please note that `seekToPosition` will only work if called on the track that is already playing. If you want to start playing a song from a specified position you should use `player.play(playConfig)` where play config has initial position set: `PlayConfig#withInitialPosition(positionInMs)`

**Comment by Wolftein** [comment]
I was calling seekToPosition at the middle of the track; The reason was #77, it is working now.
