### ISSUE TITLE
Not able to play playlist directly in android.

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#79]
How to fetch user play list in android saved in spotify account.

In iOS application we are using following method to fetch the playlist of the user:

[SPTRequest playlistsForUserInSession:session callback:^(NSError *error, id object)

Is their any way or similar method in android SDK to fetch the playlist of user from saved at spotify account.

**Comment by kaaes** [comment]
If you want to play an album you need to resolve the list of tracks from the Web API and play that list in the player:

```java
List<String> tracksList = Arrays.asList(
    "spotify:track:2To3PTOTGJUtRsK3nQemP4",
    "spotify:track:0tDoBMgyAzGgLhs73KPrJL",
    "spotify:track:5YkSQuB8i7J4TTyj0xw6ol",
    "spotify:track:3WpLfCkrlQxj8SISLzhs06"
);

mPlayer.play(trackList);
```
There are some Android libraries that provide access to the Web API - please see: https://developer.spotify.com/web-api/code-examples/#libraries

**Comment by deepakvvdn** [comment]
can i get the list of all the playlists? which user has already made on spotify account and fetch all the tracks from it right?

**Comment by kaaes** [comment]
Yes, it is possible. Please refer to the [Web API endpoints reference](https://developer.spotify.com/web-api/endpoint-reference/) for more details

**Comment by deepakvvdn** [comment]
kaaes i know this is a silly question but im getting some error with API 

https://api.spotify.com/v1/users/{user_id}/playlists

what is users here?
and user_id ?

this will help me a lot. Advance thanks for your support.

**Comment by JMPerez** [comment]
@deepakvvdn You have the information about that endpoint on https://developer.spotify.com/web-api/get-list-users-playlists/

`users` is just part of the url. You need to replace `user_id` with the id of the user from which you want to fetch their playlists.

Also, note that this endpoint needs an access token. Once you obtain an access token you can read any user's public playlists. If you want to read the current user's private playlists, you will need an access token with the `playlist-read-private` scope (see https://developer.spotify.com/web-api/using-scopes/ for more information about scopes).

**Comment by lunae** [comment]
Make sure that you have an access token. The [Android SDK](https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/#authenticating-the-user) tutorial demonstrates how to do this.

To fetch a users lists do something like the following : 
```java
SpotifyApi api = new SpotifyApi();
api.setAccessToken(token);
SpotifyService spotify = api.getService();
spotify.getPlaylists("USERID", new Callback<Pager<Playlist>>() {
	@Override
        public void success(Pager<Playlist> playlistPager, Response response) {
        	Log.d("TEST", "Got the playlists");
		List<Playlist> playlists = playlistPager.items;
                for (Playlist p : playlists) {
                	Log.e("TEST", p.name + " - " + p.id);
		}
	}
        @Override
        public void failure(RetrofitError error) {
        	Log.e("TEST", "Could not get playlists");
	}
});
```

Once you know the playlist ID, you can then fetch the tracks of the playlist with something like this :

```java
spotify.getPlaylistTracks("","", new Callback<Pager<PlaylistTrack>>() {
	@Override
        public void success(Pager<PlaylistTrack> playlistTrackPager, Response response) {
		Log.e("TEST", "GOT the tracks in playlist");
		List<PlaylistTrack> items = playlistTrackPager.items;
		for( PlaylistTrack pt : items){
			Log.e("TEST", pt.track.name + " - " + pt.track.id);
		}
	}
	@Override
        public void failure(RetrofitError error) {
        	Log.e("TEST", "Could not get playlist tracks");
        }
});
```

Hope this helps.

**Comment by deepakvvdn** [comment]
api.setAccessToken(token);
                final SpotifyService spotify = api.getService();
                spotify.getPlaylists(USER_ID, new Callback<Pager<Playlist>>() {
                    @Override
                    public void success(Pager<Playlist> playlistPager, Response response) {

                        List<Playlist> playlists = playlistPager.items;
                        for (final Playlist p : playlists) {

//                            DemoUtils.showLogs(TAG, "Got the playlist : ------------------" + p.name + "   id:" + p.id + " Tracks : ");
                            mActivity.runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    songsListDataNew.add(p.name + "_spotify");
                                    localAndSpotifyMusicListAdapter.setMusicListData(songsListDataNew);
                                    localAndSpotifyMusicListAdapter.notifyDataSetChanged();
                                    playlistValues.setPlaylistName(songsListDataNew);
                                }
                            });


                            music_spotify_relative_layout.setClickable(false);
                            spotify.getPlaylistTracks(USER_ID, p.id, new Callback<Pager<PlaylistTrack>>() {
                                @Override
                                public void success(Pager<PlaylistTrack> playlistTrackPager, Response response) {
//                                    DemoUtils.showLogs(TAG, "GOT the tracks in playlist");
                                    List<PlaylistTrack> items = playlistTrackPager.items;
                                    
                                    playlistValues.setSizeOfTracks(items.size());

                                    for (PlaylistTrack pt : items) {
//                                        DemoUtils.showLogs(TAG, "Track Name : " + pt.track.name + "   Track Id : " + pt.track.id);
                                        songsURI.add(pt.track.id);
                                        playlistValues.setURI(songsURI);
                                    }

                                }

                                @Override
                                public void failure(RetrofitError error) {
                                    Log.e("TEST", "Could not get playlist tracks");
                                }
                            });

                        }
                    }

                    @Override
                    public void failure(RetrofitError error) {
                        Log.e("TEST", "Could not get playlists");
                    }
                });

**Comment by deepakvvdn** [comment]
thanks a lot this help's me a lot !! but one of my playlist their is around 30 songs . I am not able to fetch the list of all the tracks , otherwise from the others playlist which has only 2-3 tracks I am able to fetch that one!!!

Just asking Its some issue from mys side or their is some limitation their to fetch more tracks!!

**Comment by lunae** [comment]
I just tested and confirmed the snippet below with a playlist that has over 30 songs and it was able to retrieve all tracks. 

```java
spotify.getPlaylistTracks("USERID","PLAYLISTID", new Callback<Pager<PlaylistTrack>>() {
    @Override
        public void success(Pager<PlaylistTrack> playlistTrackPager, Response response) {
        List<PlaylistTrack> items = playlistTrackPager.items;
        for( PlaylistTrack pt : items){
            Log.e("TEST", pt.track.name + " - " + pt.track.id);
        }
        Log.e("TEST", "Total of " + items.size() + " tracks");
    }
    @Override
        public void failure(RetrofitError error) {
            Log.e("TEST", "Could not get playlist tracks");
        }
});
```

**Comment by deepakvvdn** [comment]
yaa it shd do but nt doing well!!!

can u add me on skype : deepak.kumar3038

**Comment by kaaes** [comment]
I'm going to close this issue as it doesn't seem to be a bug in the SDK. Please open again if you think this is a problem.
