### ISSUE TITLE
Service leaks in LoginActivity

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#81]
If there is a mandatory setting lacking in our setup, please notify me, but: I get recurring exceptions due to LoginActivity leaking the services "EyesFree" and "TextToSpeech". Are these services properly unbind-ed prior to destroying the LoginActivity?

**Comment by kaaes** [comment]
These services are not the part of this SDK. Please check your project's code for how they're used.

**Comment by chjan** [comment]
Thought so. And neither in our code. Looks like Google Chrome modules. Could it simply be an indirect effect of using Chrome for the Authentication procedure? I shall try the native browser...
