### ISSUE TITLE
Incomprehensible Retrofit error is camouflaging comprehensible Spotify search error

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#82]
This is FYC, no need to comment unless you like to.

When I due to code blunder send an empty search string to the api, it results in retroFit error "bad request", which is incomprehensible and requires debugging (at least on first encounter). RetroFit also sends the url causing the error, and when launching that url in a browser, a comprehensible Spotify (?) error message is shown: "No such query"

The combination of the url and its Spotify error message leads me directly to the cause of the error. It is suggested that the original error message (by far) is more pinpointing and helpful than the abstraction presented by Retrofit. If possible, pass the real cause along as a sub-error message or similar.

**Comment by kaaes** [comment]
Thanks for the report. This is related to the API wrapper so I moved it to that project https://github.com/kaaes/spotify-web-api-android/issues/32
