### ISSUE TITLE
getPlayer return null if call from two different Activity or Service

### ISSUE THREAD

**Issue by krunal131987** [spotify/android-sdk#83]
I am using getPlayer method in two different Activity A and B. onDestroy method of activity 'A', i am destroying player using this code Spotify.destroyPlayer(this);

when open 'B' Activity and initializing player using getPlayer(), it return null value

How to manage instance of Player in multiple Activity or Service?

**Comment by kaaes** [comment]
This is probably a timing issue related to the fact that Player runs in a separate thread and stopping it is asynchronous. There's a [Spotify#awaitDestroyPlayer](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/Spotify.html#awaitDestroyPlayer-java.lang.Object-long-java.util.concurrent.TimeUnit-) method for stopping Player synchronously that should work better in this situation

**Comment by kaaes** [comment]
@krunal131987 were you able to solve this problem?

**Comment by krunal131987** [comment]
yes, i am creating static object for player class
