### ISSUE TITLE
Same token is not working after two days!!

### ISSUE THREAD

**Issue by deepakvvdn** [spotify/android-sdk#84]
I have face one issue:

I run the app two days ago and I saved the oath token in my local application preference class.I expected for next time i need not to login again to get list of user playlist. But after two days when i run the app again its not getting playlist with same token. I uninstall the app , install again login again and working fine for me!!

Now my question is how can i save the token for long time after once login.

The same issue I  have faced with spotify web gui. I was accessing the playlist with last token generated before two days back but does not work. It was giving error 401. But after generating new toekn it works fine for me!!

**Comment by iKenndac** [comment]
Tokens using the implicit grant flow expire after an hour. If you used the authorisation code flow, you need to use your refresh token to get a new access token. 

Documentation is here: https://developer.spotify.com/web-api/authorization-guide/
