### ISSUE TITLE
onPlayBackEvent : no systematic reception of BECAME_ACTIVE

### ISSUE THREAD

**Issue by trileude** [spotify/android-sdk#86]
Hi,
I'm not really sure of it, but it seems that we do not receive the BECAME_ACTIVE notification in the callback onPlayBackEvent. I see it in the logs of the sdk, but not in my callback. I don't know if anybody else has the issue, maybe it's me.
Here is the log :
03-10 18:12:41.005    9813-9876/com.example.developper.deezerspotify I/SpotifySDK﹕ Got notification: Became active playing device
03-10 18:12:48.127    9813-9876/com.example.developper.deezerspotify I/SpotifySDK﹕ Temporary connection error occurred
03-10 18:12:48.127    9813-9813/com.example.developper.deezerspotify I/TrackListActivity﹕ onTemporaryError
03-10 18:12:50.645    9813-9876/com.example.developper.deezerspotify I/SpotifySDK﹕ Login complete
03-10 18:12:50.646    9813-9813/com.example.developper.deezerspotify I/TrackListActivity﹕ onLoggedIn
03-10 18:12:52.611    9813-9876/com.example.developper.deezerspotify I/SpotifySDK﹕ Got notification: Play
03-10 18:12:52.612    9813-9813/com.example.developper.deezerspotify I/TrackListActivity﹕ playback event : PLAY
03-10 18:12:52.622    9813-9876/com.example.developper.deezerspotify I/SpotifySDK﹕ Got notification: Track started
03-10 18:12:52.624    9813-9813/com.example.developper.deezerspotify I/TrackListActivity﹕ playback event : TRACK_START

**Comment by kaaes** [comment]
Probably BECAME_ACTIVE event is triggered before notification callbacks are registered.
Do you need to get it? It will only happen once (when player initializes) and is not particularly interesting ;)
If you do need it try registering playback notifications callbacks immediately after Spotify#getPlayer is called

**Comment by trileude** [comment]
Yes I need to get it because I activate the control buttons of my UI only when BECAME_ACTIVE is received. Maybe it is not the right way to do it ?
I try what you asked me to do : I call addPlayerNotificationCallback juste after Spotify#getPlayer instead of in the InitializationObserver#onInitialized callback and it's better.
Thank you.
