### ISSUE TITLE
Please remove Apache LICENSE file

### ISSUE THREAD

**Issue by SchnWalter** [spotify/android-sdk#87]
Posting an Apache LICENSE file into an empty repository and creating a release with binaries attached does not make it open source.

Please remove the LICENSE file or upload the source code as you said in this commit: https://github.com/spotify/android-sdk/commit/5cb92950c4dc213fa2eb66f3d8380433d7758e26

Thank you!

**Comment by nikreiman** [comment]
We are currently in the process of getting the code approved by our legal team for open-sourcing. Part of this process includes adding the LICENSE file to the repository.

**Comment by NOlivNeto** [comment]
hue.

**Comment by d-kunin** [comment]
And it is gone
