### ISSUE TITLE
Service leak in the process subsequent to .openLoginActivity (again)

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#88]
Allow me to report this again, since it points to Spotify SDK and thus could be of relevance. I pose it as a question:  Could the reason behind the exception be that the browser allows for services available as JavaScripts, i.e., if the Spotify SDK had set spotifyWebView.getSettings().setJavaScriptEnabled(false);, then this exception would perhaps be prevented? Could the reason behind be that a screen tilt is not properly handled by the browser app? 

Explanation:
This is a rare error, typically "twice a day". There are two or more service leaks in the default browser used during the login process. Something is going on, seemingly when a "bad token" is discovered, and activity is not found, causing interrupt of the whole procedure, again seemingly causing service leak of services started by the browser, services that are of no direct relevance to the login process, namely text-to-speech, etc. Here is my complete code for initiation of the process:

![image](https://cloud.githubusercontent.com/assets/69140/6614223/c9ddc326-c897-11e4-9117-58dbc12b073b.png)

In main activity, the .onActivityResult() reports to logcat all other events than a successful reception of a TOKEN, but no such messages are logged.

Here is a logcat screenshot of the exception. Observe the "badTokenException": Unable to add window...". I am not 100% sure that this is the Spotify token or something else.

![image](https://cloud.githubusercontent.com/assets/69140/6614371/a5f3cc7e-c899-11e4-80d8-958fe37d19a3.png)

**Comment by kaaes** [comment]
Hm, I have never seen it happen but I'll have a look at this.
Thank you for providing the details.

**Comment by kaaes** [comment]
@chjan are you by any chance using accessibility services such as Talkback? I think leaking services is an issue in Chromium that occurs when both accessibility services and JavaScript in the WebView are enabled.

The BadTokenException is another bug and fix for it will be released with the next version.

**Comment by chjan** [comment]
Not using Talkback, but on Lollipop voice notifications of messages is enabled. On both KitKat and Lollipop TTSpeech is checked and not that easy to turn off, it seems.

 

Kind regards

 

Carl Henrik Janson

+47 951 048 00

 

 <http://www.soundpimp.com> www.soundpimp.com

**Comment by d-kunin** [comment]
This is Andoroid OS issues. Bad token is an internal error http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-0/android/view/WindowManager.java#57

Sorry, we cant fix it :)
