### ISSUE TITLE
Player implementation

### ISSUE THREAD

**Issue by trileude** [spotify/android-sdk#89]
Hi, 
I have a question about the player implementation. Is it based on android.media.MediaPlayer ?
I would like to add an Equalizer to my app, but it needs the audioSessionId (MediaPlayer#getAudioSessionId). Is there a way to get it from the Player ? 
Thanks

**Comment by kaaes** [comment]
The Player uses AudioTrack to play audio.
It is however possible to override the default implementation and create your own [audio controller](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/AudioController.html) if you need more control.

**Comment by trileude** [comment]
Ok I will try to implement it.
But I think it would be useful to add a method like getAudioSessionId to your Player implementation (and I think it's not very hard to do it ;) to allow users to add Equalizer or other Android AudioEffect.
Thanks.

**Comment by trileude** [comment]
It's okay I succeed in implementing the AudioController. It was really easy thanks to the AudioRingBuffer.
Thanks.

**Comment by kaaes** [comment]
Great to hear it worked! :)

**Comment by Rahul-kAgrawal** [comment]
Hi,

I tried to to apply sound effects using AudioController,

@Override
    public int onAudioDataDelivered(short[] samples, int sampleCount, int sampleRate, int channels) {

       /* here apply sound effects on samples and get short[]  out */

        AudioRingBuffer buffer = new AudioRingBuffer(CAPACITY);
        return buffer.write(out, sampleCount);
    }

but not able to play audio. Can you please help me to find where i am doing mistakes.

Thanks

**Comment by dhavalshah60** [comment]
Hello there!! i am not getting AudioSessionId in Spotify.So, can you please provide me some guidance to Implement Equalizer in Spotify. Here above link for "Audio Controller" getting 404.

Thanks in advance.
