### ISSUE TITLE
Exception in Player at line1149; failed attempt to send callback .onPlaybackEvent

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#90]
Any suggestions as to the cause of this problem shall be much appreciated. Interface is properly implemented but no callbacks are received.

![image](https://cloud.githubusercontent.com/assets/69140/6634171/709d9a80-c954-11e4-892d-71c8da4da35f.png)

 Would the source be available for my own analysis?

**Comment by kaaes** [comment]
It is trying to invoke the method on apparently null callback object.
Could it be that `Player#addPlayerNotification` is called with a null object somewhere?
In any case this should not behave this way. I will look into this.

**Comment by chjan** [comment]
Please close this. The configuration of callback was not proper (null). Hope you didn't spend time on it yet.
