### ISSUE TITLE
Custom AudioController Noise

### ISSUE THREAD

**Issue by rog536** [spotify/android-sdk#91]
I'm trying to implement my own AudioController, but I'm getting some kind of beeping-noise. I can hear the actual track in the background of the noise if I listen carefully.

I tried adding an AudioRingBuffer and moving the writing to the AudioTrack to a separate thread, but that made no difference.

Below is the AudioController  i test with.

Anyone know what I'm doing wrong?

```
Player.Builder b = new  Player.Builder(playerConfig);
b.setAudioController(new AudioController() {	
AudioTrack mTrack = null;
	@Override
	public void start() {
		Log.d(PLAYER_TAG,"start");
	}

	@Override
	public void stop() {
		Log.d(PLAYER_TAG,"stop");
	}

	@Override
	public int onAudioDataDelivered(short[] frames, int numFrames, int sampleRate, int channels) {

		if (mTrack == null ) {
			int intSize = android.media.AudioTrack.getMinBufferSize(
					sampleRate,
					AudioFormat.CHANNEL_OUT_STEREO,
					AudioFormat.ENCODING_PCM_16BIT);
			Log.d(PLAYER_TAG, "AUDIO DELIVERED CREATING TRACK " + intSize);
			mTrack = new AudioTrack(
					AudioManager.STREAM_MUSIC,
					sampleRate,
					AudioFormat.CHANNEL_OUT_STEREO,
					AudioFormat.ENCODING_PCM_16BIT,
					intSize,
					AudioTrack.MODE_STREAM);
			mTrack.play();
		}
		int written = mTrack.write(frames, 0, frames.length) / channels;
		Log.d(PLAYER_TAG, "numFrames " + numFrames + " frames length " + frames.length + " written " + written + " sampleRate " + sampleRate + " channels " + channels);
		return written;
	}

	@Override
	public void onAudioFlush() {
		Log.d(PLAYER_TAG,"onAudioFlush");
		if(mTrack!= null)
			mTrack.flush();
	}

	@Override
	public void onAudioPaused() {
		Log.d(PLAYER_TAG,"onAudioPaused");
	}

	@Override
	public void onAudioResumed() {
		Log.d(PLAYER_TAG,"onAudioResumed");
	}
});
```

**Comment by nikreiman** [comment]
I'm guessing that your call to `write` is wrong. You should try:

    int written = mTrack.write(frames, 0, numFrames);

**Comment by nikreiman** [comment]
Oh yeah, also, Spotify does have some mono material in the catalog (for example, `spotify:track:1FqY3uJypma5wkYw66QOUi`). You shouldn't hardcode `CHANNEL_OUT_STEREO`; use the value the API passes to you in `onAudioDataDelivered`.

Also you might want to multiply the value returned by `getMinBufferSize` by a factor of 2 (or some other small-ish number). This number is only the minimum buffer size that Android thinks it can handle for realtime audio streaming, however you might end up dropping samples if the system comes under pressure and you have initialized with a buffersize that's too small. This is optional though; on newer Android hardware, it's usually more than fast enough to deal with the buffersizes returned from that call (which tend to be rather large for realtime audio streaming applications IMHO).

**Comment by rog536** [comment]
Thank you so much! It works now.
I changed 
```
int written = mTrack.write(frames, 0, frames.length) / channels;
```
to
```
int written = mTrack.write(frames, 0, numFrames);
```

And I will do as you recommend and check the number of channels if they change.
