### ISSUE TITLE
seekToPosition(0) cause error.

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#94]
If i'm playing a song and i seek to other position rather than 0 works, but if i seek to 0ms the track pause and raise a playback error.

I/SpotifySDK(16281): playbackCallbackOnSeek (to 0ms)
I/SpotifySDK(16281): Got notification: Pause
D/MyApp(16281): ERROR: Playback error occurred
I/SpotifySDK(16281): Got notification: Track ended

**Comment by kaaes** [comment]
I tried skipping to 0 and it worked for me (the song started playing from the beginning).
What type of playback error are you getting? Are you calling `player.seekToPosition(0);` after song started playing? (seeking will only work after first AUDIO_FLUSH happened)

**Comment by Wolftein** [comment]
Happend rarely sometimes when i start a song from a position other than the beginning and then seek to 0 then after a few seconds i seek to 0.

**Comment by Wolftein** [comment]
03-23 18:33:39.510: I/SpotifySDK(1701): Got notification: Play
03-23 18:33:39.510: I/SpotifySDK(1701): Got notification: Track started
03-23 18:33:39.526: I/SpotifySDK(1701): Got notification: Audio flush
03-23 18:33:42.494: I/SpotifySDK(1701): playbackCallbackOnSeek (to 0ms)
03-23 18:33:42.502: D/MyApp(1701): ERROR: Playback error occurred TYPE: ERROR_PLAYBACK
03-23 18:33:42.502: I/SpotifySDK(1701): Got notification: Pause
03-23 18:33:42.502: I/SpotifySDK(1701): Got notification: Track ended

**Comment by d-kunin** [comment]
Should not be an issue in beta 21.
