### ISSUE TITLE
Spotify SDK CPU useage

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/android-sdk#98]
After following the tutorial and getting my app to play a track; I noticed that my device was using up battler very quickly. So I attached it to Android Studio and used their new CPU profiler, I found that after logging in to Spotify that the CPU usage jumped around 60%; however when I played a song there was only a small CPU increase.

When the song finished playing the CPU usage jumped back up. I then locked the phone and the App continued to use the same amount of CPU in the background. Before I added the SDK the CPU usage when locked as almost 0%.

I have noticed this bug on the previous release of the SDK as well as this version. Let me know if you need more information.

**Comment by nikreiman** [comment]
Is there any chance that you could share with us some of the playback code that you have in your app? I have a feeling that if you are doing too much extra work in the music delivery callback then it could spike the application's CPU usage (assuming that you are actually doing any work to get the PCM samples).

**Comment by kaaes** [comment]
I had a quick look today and I think I found the source of this problem. I'll bring it up with the team and we'll get it fixed with the next release.
Thank you for the report!

**Comment by Brad-Jackson** [comment]
Great thanks very much.

**Comment by mrmaffen** [comment]
I have noticed the same thing. Even though playback is paused the CPU is being used quite heavily. A quick method profiling showed that com.spotify.sdk.android.player.NativeSdkPlayer.nativePumpEvents()V (82% of incl cpu time) and com.spotify.sdk.android.player.NativeSdkPlayer.nativeRefreshCache()V (16% of incl cpu time) seem to be causing this. Hope this helps!

**Comment by jherskowitz** [comment]
@kaaes, any idea of roughly when that next release will be? Thanks.

**Comment by mrmaffen** [comment]
Here's another output of the method profiling tool in Android Device Monitor. I was playing a track with the Spotify Android SDK, then I paused it, put my Nexus5 (5.1.0) on the desk and waited a few minutes before starting the tool.
![spotify_android_sdk_battery_drain](https://cloud.githubusercontent.com/assets/1526877/7161314/c7a0e0b8-e38e-11e4-96d2-7bb0b3eb4146.png)

**Comment by Wolftein** [comment]
Default audio controller's thread runs all the time even if there isn't any music playing, my cpu drop to 1% using a custom audio controller https://gist.github.com/Wolftein/cf05009e08faa12c187c

**Comment by mrmaffen** [comment]
@Wolftein Your audio controller fixed the issue for me, although there were some slight modifications needed. ty! https://github.com/tomahawk-player/tomahawk-android/blob/d4ed3e472ee2d382083a94eb0ad6a5ed1a6caa9e/src/org/tomahawk/tomahawk_android/utils/SimpleAudioController.java

**Comment by Brad-Jackson** [comment]
Sorry guys, these versions still have a problem; if you let the song finish the CPU usage goes back to 100%. The code works if you pause the song. I have found another area where the CPU usage goes up, and that is when the user logs out of Spotify.

**Comment by kaaes** [comment]
We'll try to get the new release with this fix out this or next week.
As you mentioned above the AudioController's thread is responsible for this behaviour. In fixed version it will only run when the music is playing.
We will test all cases you mentioned in this thread to make sure it behaves well. Please keep posting if you notice some more!

**Comment by kaaes** [comment]
This issue should be fixed in 1.0.0-beta10

**Comment by mrmaffen** [comment]
I quickly tested the new version and the issue seems fixed. Thanks!

**Comment by Brad-Jackson** [comment]
Looks good, thanks.
